# Generated by Django 4.2.27 on 2025-12-19 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0004_remove_chief_complaint'),
        ('nursing', '0002_alter_nursingorder_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursingorder',
            name='consultation_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nursing_orders', to='consultation.consultationsession'),
        ),
    ]
