# Generated by Django 4.2.27 on 2026-01-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursing', '0003_add_consultation_session_to_nursing_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='procedure_type',
            field=models.CharField(choices=[('injection', 'Injection'), ('dressing', 'Dressing'), ('wound_care', 'Wound Care'), ('catheterization', 'Catheterization'), ('iv_insertion', 'IV Insertion'), ('ward_admission', 'Ward Admission'), ('other', 'Other')], max_length=50),
        ),
    ]
