# Generated by Django 4.2.27 on 2026-04-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursing', '0007_alter_procedure_performed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='doctor_initials',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='procedure',
            name='dosage',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='procedure',
            name='medication_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='procedure',
            name='nurse_initials',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='procedure',
            name='patient_status_category',
            field=models.CharField(blank=True, help_text='e.g. Pensioner, ED, Employee, Dependent', max_length=50),
        ),
        migrations.AddField(
            model_name='procedure',
            name='route',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='procedure',
            name='staff_category',
            field=models.CharField(blank=True, help_text='Officer or Staff', max_length=30),
        ),
        migrations.AddField(
            model_name='procedure',
            name='wound_intervention',
            field=models.CharField(blank=True, help_text='dressing, i_and_d, sutures, suture_removal', max_length=30),
        ),
    ]
