# Generated by Django 4.2.30 on 2026-06-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursing', '0009_nursingorder_location_clinic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='procedure_type',
            field=models.CharField(choices=[('injection', 'Injection'), ('dressing', 'Dressing'), ('wound_care', 'Wound Care'), ('medication', 'Medication'), ('catheterization', 'Catheterization'), ('iv_insertion', 'IV Insertion'), ('ward_admission', 'Ward Admission'), ('other', 'Other')], max_length=50),
        ),
    ]
