# Generated by Django 4.2.27 on 2025-12-05 16:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('category', models.CharField(choices=[('employee', 'Employee'), ('retiree', 'Retiree'), ('nonnpa', 'NonNPA'), ('dependent', 'Dependent')], default='employee', max_length=20)),
                ('title', models.CharField(blank=True, choices=[('mr', 'Mr'), ('mrs', 'Mrs'), ('ms', 'Ms'), ('dr', 'Dr'), ('chief', 'Chief'), ('engr', 'Engr'), ('prof', 'Prof'), ('alhaji', 'Alhaji'), ('hajia', 'Hajia')], max_length=20)),
                ('surname', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='patients/photos/')),
                ('personal_number', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('employee_type', models.CharField(blank=True, max_length=20, null=True)),
                ('division', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('nonnpa_type', models.CharField(blank=True, max_length=50, null=True)),
                ('dependent_type', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('state_of_residence', models.CharField(blank=True, max_length=100)),
                ('residential_address', models.TextField(blank=True)),
                ('state_of_origin', models.CharField(blank=True, max_length=100)),
                ('lga', models.CharField(blank=True, max_length=100)),
                ('permanent_address', models.TextField(blank=True)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('genotype', models.CharField(blank=True, choices=[('AA', 'AA'), ('AS', 'AS'), ('SS', 'SS'), ('AC', 'AC'), ('SC', 'SC')], max_length=5)),
                ('nok_first_name', models.CharField(blank=True, max_length=100)),
                ('nok_middle_name', models.CharField(blank=True, max_length=100)),
                ('nok_relationship', models.CharField(blank=True, max_length=50)),
                ('nok_address', models.TextField(blank=True)),
                ('nok_phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patients', to=settings.AUTH_USER_MODEL)),
                ('principal_staff', models.ForeignKey(blank=True, limit_choices_to={'category__in': ['employee', 'retiree']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependents', to='patients.patient')),
            ],
            options={
                'db_table': 'patients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('visit_type', models.CharField(choices=[('consultation', 'Consultation'), ('follow_up', 'Follow-up'), ('emergency', 'Emergency'), ('routine', 'Routine Checkup')], default='consultation', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('clinic', models.CharField(blank=True, max_length=100)),
                ('chief_complaint', models.TextField(blank=True)),
                ('clinical_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_visits', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(limit_choices_to={'system_role': 'Medical Doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_visits', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='patients.patient')),
            ],
            options={
                'db_table': 'visits',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergies', models.JSONField(blank=True, default=list, help_text='List of allergies')),
                ('diagnoses', models.JSONField(blank=True, default=list, help_text='List of diagnoses with status')),
                ('current_medications', models.JSONField(blank=True, default=list, help_text='List of current medications')),
                ('surgical_history', models.JSONField(blank=True, default=list, help_text='List of past surgeries')),
                ('family_history', models.JSONField(blank=True, default=list, help_text='Family medical history')),
                ('social_history', models.JSONField(blank=True, default=dict, help_text='Smoking, alcohol, exercise, etc.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to='patients.patient')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_medical_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Medical Histories',
                'db_table': 'medical_history',
            },
        ),
        migrations.CreateModel(
            name='VitalReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, help_text='Temperature in Celsius', max_digits=5, null=True)),
                ('blood_pressure_systolic', models.IntegerField(blank=True, null=True)),
                ('blood_pressure_diastolic', models.IntegerField(blank=True, null=True)),
                ('heart_rate', models.IntegerField(blank=True, help_text='Beats per minute', null=True)),
                ('respiratory_rate', models.IntegerField(blank=True, help_text='Breaths per minute', null=True)),
                ('oxygen_saturation', models.DecimalField(blank=True, decimal_places=2, help_text='SpO2 percentage', max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=5, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, help_text='Body Mass Index', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_readings', to='patients.patient')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_vitals', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vital_readings', to='patients.visit')),
            ],
            options={
                'db_table': 'vital_readings',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['patient', '-recorded_at'], name='vital_readi_patient_800333_idx'), models.Index(fields=['visit'], name='vital_readi_visit_i_21df0b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['visit_id'], name='visits_visit_i_55c4ed_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['patient', '-date'], name='visits_patient_b20a5c_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['status'], name='visits_status_79e0cd_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['patient_id'], name='patients_patient_e63b14_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['personal_number'], name='patients_persona_f4d6ea_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['category'], name='patients_categor_daefed_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['surname', 'first_name'], name='patients_surname_78078c_idx'),
        ),
    ]
