# Generated by Django 4.2.27 on 2025-12-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='visit_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, unique=True),
        ),
    ]
