# Generated by Django 4.2.27 on 2025-12-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_visit_visit_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='nok_surname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
