# Generated by Django 4.2.27 on 2025-12-13 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_add_nok_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='religion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='tribe',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
