# Generated by Django 4.2.27 on 2025-12-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_normalize_clinic_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
