# Generated by Django 4.2.27 on 2025-12-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_add_location_to_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True, help_text='Known allergies (comma-separated or newline-separated)'),
        ),
    ]
