# Generated by Django 4.2.27 on 2025-12-19 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_add_allergies_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='chief_complaint',
        ),
    ]
