# Generated by Django 4.2.27 on 2026-01-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_remove_chief_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='admission_status',
            field=models.CharField(choices=[('outpatient', 'Outpatient'), ('inpatient', 'Inpatient'), ('day_case', 'Day Case')], default='outpatient', max_length=20),
        ),
    ]
