# Generated by Django 4.2.27 on 2026-01-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_visit_admission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='admission_status',
            field=models.CharField(choices=[('outpatient', 'Outpatient'), ('observation', 'Observation/Short Stay'), ('admitted', 'Ward Admission'), ('day_case', 'Day Case')], default='outpatient', max_length=20),
        ),
    ]
