# Generated by Django 4.2.27 on 2026-01-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_alter_visit_admission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='title',
            field=models.CharField(blank=True, choices=[('mr', 'Mr'), ('mrs', 'Mrs'), ('ms', 'Ms'), ('miss', 'Miss'), ('dr', 'Dr'), ('chief', 'Chief'), ('engr', 'Engr'), ('prof', 'Prof'), ('alhaji', 'Alhaji'), ('hajia', 'Hajia'), ('mallam', 'Mallam'), ('lady', 'Lady')], max_length=20),
        ),
    ]
