# Generated by Django 4.2.27 on 2026-02-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_alter_patient_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='clinics',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='visit',
            name='completed_clinics',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
