# Generated by Django 4.2.27 on 2026-02-28 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('patients', '0012_multi_clinic_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='location_clinic',
            field=models.ForeignKey(blank=True, help_text='Clinic/facility from Clinics & Departments (replaces free-text location when set)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='organization.clinic'),
        ),
        migrations.AddField(
            model_name='visit',
            name='location_clinic',
            field=models.ForeignKey(blank=True, help_text='Clinic/facility from Clinics & Departments (replaces free-text location when set)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='organization.clinic'),
        ),
    ]
