# Generated by Django 4.2.29 on 2026-03-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0017_vitalreading_random_blood_sugar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalreading',
            name='blood_sugar',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Blood sugar in mg/dL (e.g. fasting or general capillary glucose)', max_digits=6, null=True),
        ),
    ]
