# Generated by Django 4.2.27 on 2026-04-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0020_canonical_visit_clinic_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='visit_type',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('follow_up', 'Follow-up'), ('emergency', 'Emergency'), ('routine', 'Routine Checkup'), ('responsibility_form', 'Responsibility Form')], default='consultation', max_length=20),
        ),
        migrations.AlterField(
            model_name='vitalreading',
            name='blood_sugar',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Random blood sugar (RBS) in mg/dL', max_digits=6, null=True),
        ),
    ]
