# Generated by Django 4.2.27 on 2026-05-18 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0021_add_responsibility_form_visit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patient',
            name='title',
            field=models.CharField(blank=True, choices=[('mr', 'Mr'), ('mrs', 'Mrs'), ('ms', 'Ms'), ('master', 'Master'), ('miss', 'Miss'), ('dr', 'Dr'), ('chief', 'Chief'), ('engr', 'Engr'), ('prof', 'Prof'), ('alhaji', 'Alhaji'), ('hajia', 'Hajia'), ('mallam', 'Mallam'), ('lady', 'Lady')], max_length=20),
        ),
    ]
