# Generated by Django 4.2.27 on 2026-06-04 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0022_add_updated_by_to_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='merge_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='merged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='merged_into',
            field=models.ForeignKey(blank=True, help_text='If set, this record was merged into the referenced patient.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_records', to='patients.patient'),
        ),
        migrations.CreateModel(
            name='PatientMerge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merged_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(help_text='Why these records were merged.')),
                ('winner_snapshot', models.JSONField()),
                ('loser_snapshot', models.JSONField()),
                ('visits_repointed', models.PositiveIntegerField(default=0)),
                ('vital_readings_repointed', models.PositiveIntegerField(default=0)),
                ('lab_orders_repointed', models.PositiveIntegerField(default=0)),
                ('lab_results_repointed', models.PositiveIntegerField(default=0)),
                ('prescriptions_repointed', models.PositiveIntegerField(default=0)),
                ('consult_sessions_repointed', models.PositiveIntegerField(default=0)),
                ('queue_items_repointed', models.PositiveIntegerField(default=0)),
                ('referrals_repointed', models.PositiveIntegerField(default=0)),
                ('diagnoses_repointed', models.PositiveIntegerField(default=0)),
                ('admissions_repointed', models.PositiveIntegerField(default=0)),
                ('physio_orders_repointed', models.PositiveIntegerField(default=0)),
                ('eye_orders_repointed', models.PositiveIntegerField(default=0)),
                ('nursing_orders_repointed', models.PositiveIntegerField(default=0)),
                ('procedures_repointed', models.PositiveIntegerField(default=0)),
                ('radiology_orders_repointed', models.PositiveIntegerField(default=0)),
                ('radiology_reports_repointed', models.PositiveIntegerField(default=0)),
                ('appointments_repointed', models.PositiveIntegerField(default=0)),
                ('medical_certs_repointed', models.PositiveIntegerField(default=0)),
                ('medical_history_repointed', models.PositiveIntegerField(default=0)),
                ('medical_history_merged', models.PositiveIntegerField(default=0)),
                ('dependents_repointed', models.PositiveIntegerField(default=0)),
                ('loser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merge_loser_rows', to='patients.patient')),
                ('merged_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_merges', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merge_winner_rows', to='patients.patient')),
            ],
            options={
                'db_table': 'patient_merges',
                'ordering': ['-merged_at'],
                'indexes': [models.Index(fields=['winner'], name='patient_mer_winner__ed038b_idx'), models.Index(fields=['loser'], name='patient_mer_loser_i_b05714_idx'), models.Index(fields=['merged_at'], name='patient_mer_merged__e500e1_idx')],
            },
        ),
    ]
