# Generated by Django 4.2.30 on 2026-06-20 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0031_scalability_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='patient',
            name='patients_surname_trgm_idx',
        ),
        migrations.RemoveIndex(
            model_name='patient',
            name='patients_first_name_trgm_idx',
        ),
        migrations.RemoveIndex(
            model_name='visit',
            name='visits_date_status_idx',
        ),
        migrations.RenameIndex(
            model_name='annualcheckup',
            new_name='annual_chec_patient_59d667_idx',
            old_name='annual_chec_patient_0f0f0f_idx',
        ),
        migrations.RenameIndex(
            model_name='annualcheckup',
            new_name='annual_chec_status_e9e0a3_idx',
            old_name='annual_chec_status_1a1a1a_idx',
        ),
    ]
