# Generated by Django 4.2.30 on 2026-08-09 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0034_patient_clinical_document'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='patientclinicaldocument',
            new_name='patient_cli_patient_fdae5f_idx',
            old_name='patient_cli_patient_docdate_idx',
        ),
        migrations.RenameIndex(
            model_name='patientclinicaldocument',
            new_name='patient_cli_patient_c3ff0f_idx',
            old_name='patient_cli_patient_doctype_idx',
        ),
        migrations.RenameIndex(
            model_name='patientrecordsnote',
            new_name='patient_rec_patient_bbda9e_idx',
            old_name='patient_rec_patient_7c1a2b_idx',
        ),
    ]
