# Generated by Django 4.2.30 on 2026-09-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0035_rename_patient_cli_patient_docdate_idx_patient_cli_patient_fdae5f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_first_time_patient',
            field=models.BooleanField(default=False, help_text='Checked when the patient is coming to the clinic for the first time (no prior paper records).'),
        ),
    ]
