# Generated by Django 4.2.27 on 2025-12-09 13:26

from django.db import migrations, models
import django.db.models.deletion


def convert_empty_department_to_null(apps, schema_editor):
    """Convert empty string department values to NULL before changing field type."""
    User = apps.get_model('accounts', 'User')
    # Use raw SQL to avoid model field type issues
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("UPDATE users SET department = NULL WHERE department = ''")


def reverse_convert_empty_department_to_null(apps, schema_editor):
    """Reverse migration - convert NULL back to empty string (if needed)."""
    User = apps.get_model('accounts', 'User')
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("UPDATE users SET department = '' WHERE department IS NULL")


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        # Step 1: Make department field nullable first (if it's not already)
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        # Step 2: Convert empty strings to NULL
        migrations.RunPython(
            convert_empty_department_to_null,
            reverse_convert_empty_department_to_null,
        ),
        # Step 3: Add clinic field
        migrations.AddField(
            model_name='user',
            name='clinic',
            field=models.ForeignKey(blank=True, help_text='Clinic where the user works (e.g., Bode Thomas, HQ)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='organization.clinic'),
        ),
        # Step 4: Now alter department field to ForeignKey
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department/Module the user belongs to (e.g., Medical Records, Nursing, Consultation)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='organization.department'),
        ),
        # Step 5: Add index
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['clinic', 'department'], name='users_clinic__d0f33b_idx'),
        ),
    ]
