# Generated by Django 4.2.30 on 2026-05-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_custom_pages_overrides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='system_role',
            field=models.CharField(blank=True, choices=[('System Administrator', 'System Administrator'), ('Medical Doctor', 'Medical Doctor'), ('Nursing Officer', 'Nursing Officer'), ('Laboratory Scientist', 'Laboratory Scientist'), ('Pharmacist', 'Pharmacist'), ('Radiologist', 'Radiologist'), ('Optamologist', 'Optamologist'), ('Medical Records Officer', 'Medical Records Officer'), ('Admin Staff', 'Admin Staff')], max_length=50),
        ),
    ]
