# Generated by Django 4.2.30 on 2026-05-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_systemrole_user_system_role_obj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='system_role',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
