# Generated by Django 4.2.28 on 2026-05-20 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_systemconfig_clinic_default_processing_clinic'),
        ('accounts', '0007_alter_user_system_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_clinic',
            field=models.ForeignKey(blank=True, help_text='Current clinic the user is actively working from (set at login/switch)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_staff', to='organization.clinic'),
        ),
        migrations.AddField(
            model_name='user',
            name='clinics',
            field=models.ManyToManyField(blank=True, help_text='All clinics this user can access (for rotational staff)', related_name='assigned_staff', to='organization.clinic'),
        ),
        migrations.AlterField(
            model_name='user',
            name='clinic',
            field=models.ForeignKey(blank=True, help_text='Home clinic where the user primarily works (e.g., Bode Thomas, HQ)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='organization.clinic'),
        ),
    ]
