# Generated by Django 4.2.30 on 2026-08-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_permissions_version'),
        # ``organization.0006_backfill_multi_clinic`` (a data migration) reads
        # ``User.clinic`` / ``User.clinics``. It must run before this rename.
        ('organization', '0006_backfill_multi_clinic'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_clinic__d0f33b_idx',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='clinic',
            new_name='location_clinic',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='clinics',
            new_name='location_clinics',
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['location_clinic', 'department'], name='users_locatio_ca99e7_idx'),
        ),
    ]
