# Generated by Django 4.2.27 on 2025-12-05 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clinics',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='organization.clinic')),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_led', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'departments',
                'ordering': ['clinic__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('room_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('room_type', models.CharField(choices=[('consultation', 'Consultation'), ('procedure', 'Procedure'), ('emergency', 'Emergency'), ('examination', 'Examination'), ('other', 'Other')], default='consultation', max_length=50)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('floor', models.CharField(blank=True, max_length=50)),
                ('specialty', models.CharField(blank=True, max_length=100)),
                ('capacity', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], default='active', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='organization.clinic')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='organization.department')),
            ],
            options={
                'db_table': 'rooms',
                'ordering': ['room_number'],
            },
        ),
        migrations.AddIndex(
            model_name='clinic',
            index=models.Index(fields=['name'], name='clinics_name_040576_idx'),
        ),
        migrations.AddIndex(
            model_name='clinic',
            index=models.Index(fields=['code'], name='clinics_code_ec9584_idx'),
        ),
        migrations.AddIndex(
            model_name='clinic',
            index=models.Index(fields=['is_active'], name='clinics_is_acti_5ab494_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['room_number'], name='rooms_room_nu_5c8eca_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['clinic', 'status'], name='rooms_clinic__bd764f_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['room_type', 'status'], name='rooms_room_ty_359c15_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['clinic', 'is_active'], name='departments_clinic__8f7c4e_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['name'], name='departments_name_c59a45_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('clinic', 'name')},
        ),
    ]
