# Generated by Django 4.2.30 on 2026-04-30 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_outpatient_clinic_types'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='facilityoutpatientclinic',
            new_name='facility_ou_facilit_08db53_idx',
            old_name='facility_ou_facilit_idx',
        ),
    ]
