# Generated by Django 4.2.30 on 2026-05-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_rename_facility_ou_facilit_idx_facility_ou_facilit_08db53_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'work_locations',
                'ordering': ['name'],
            },
        ),
    ]
