# Generated by Django 4.2.28 on 2026-05-20 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_worklocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System configuration',
                'verbose_name_plural': 'System configurations',
                'db_table': 'system_config',
            },
        ),
        migrations.AddField(
            model_name='clinic',
            name='default_processing_clinic',
            field=models.ForeignKey(blank=True, help_text='Default clinic where lab/radiology orders are processed (e.g. Tin Can → Bode Thomas)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinics_that_route_here', to='organization.clinic'),
        ),
    ]
