# Generated by Django 4.2.30 on 2026-06-20 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0008_seed_idle_session_timeout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='deputy_head',
            field=models.ForeignKey(blank=True, help_text='Deputy / assistant head with the same department user-management scope as head.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_deputied', to=settings.AUTH_USER_MODEL),
        ),
    ]
