# Generated by Django 4.2.30 on 2026-08-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_alter_department_deputy_head'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['location_clinic__name', 'name']},
        ),
        migrations.RemoveIndex(
            model_name='department',
            name='departments_clinic__8f7c4e_idx',
        ),
        migrations.RemoveIndex(
            model_name='room',
            name='rooms_clinic__bd764f_idx',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='clinic',
            new_name='location_clinic',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='clinic',
            new_name='location_clinic',
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('location_clinic', 'name')},
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['location_clinic', 'is_active'], name='departments_locatio_867e19_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['location_clinic', 'status'], name='rooms_locatio_8e5bfd_idx'),
        ),
    ]
