# Generated by Django 4.2.27 on 2025-12-05 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=False)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('lab_results_enabled', models.BooleanField(default=True)),
                ('radiology_results_enabled', models.BooleanField(default=True)),
                ('prescriptions_enabled', models.BooleanField(default=True)),
                ('appointments_enabled', models.BooleanField(default=True)),
                ('system_alerts_enabled', models.BooleanField(default=True)),
                ('low_priority_enabled', models.BooleanField(default=True)),
                ('normal_priority_enabled', models.BooleanField(default=True)),
                ('high_priority_enabled', models.BooleanField(default=True)),
                ('urgent_priority_enabled', models.BooleanField(default=True)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='e.g., 22:00', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='e.g., 08:00', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('workflow', 'Workflow'), ('lab_result', 'Lab Result'), ('radiology_result', 'Radiology Result'), ('prescription', 'Prescription'), ('appointment', 'Appointment'), ('system', 'System'), ('alert', 'Alert'), ('reminder', 'Reminder')], db_index=True, default='system', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='normal', max_length=10)),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read'), ('archived', 'Archived')], db_index=True, default='unread', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('action_url', models.URLField(blank=True, help_text='URL to navigate when notification is clicked')),
                ('object_type', models.CharField(blank=True, help_text='patient, lab_order, prescription, etc.', max_length=50)),
                ('object_id', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status', '-created_at'], name='notificatio_user_id_a34568_idx'), models.Index(fields=['type', 'priority'], name='notificatio_type_7e50f5_idx'), models.Index(fields=['created_at'], name='notificatio_created_e4c995_idx')],
            },
        ),
    ]
