# Generated by Django 4.2.27 on 2026-04-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, help_text='URL or path to navigate when notification is clicked', max_length=500),
        ),
    ]
