# Generated by Django 4.2.30 on 2026-05-10 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_rename_type_to_notification_type'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_type_7e50f5_idx',
        ),
        migrations.AddField(
            model_name='notificationpreferences',
            name='desktop_alerts_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreferences',
            name='sound_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreferences',
            name='sound_urgent_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', 'priority'], name='notificatio_notific_5536b0_idx'),
        ),
    ]
