# Generated by Django 4.2.30 on 2026-05-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_add_alerter_prefs'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreferences',
            name='auto_archive_days',
            field=models.PositiveIntegerField(default=30, help_text='Auto-archive read notifications after this many days. 0 = never.'),
        ),
    ]
