# Generated by Django 4.2.27 on 2026-01-24 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.JSONField(blank=True, default=list, help_text='List of allowed page URLs'),
        ),
    ]
