# Generated by Django 4.2.28 on 2026-02-26 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultation', '0009_remove_consultationqueue_consult_q_active_queued_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0012_multi_clinic_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='EyeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_complaint', models.TextField(blank=True)),
                ('visual_acuity_od', models.CharField(blank=True, help_text='Right eye visual acuity', max_length=50)),
                ('visual_acuity_os', models.CharField(blank=True, help_text='Left eye visual acuity', max_length=50)),
                ('visual_acuity_ou', models.CharField(blank=True, help_text='Both eyes visual acuity', max_length=50)),
                ('refraction_od', models.CharField(blank=True, help_text='Right eye refraction', max_length=100)),
                ('refraction_os', models.CharField(blank=True, help_text='Left eye refraction', max_length=100)),
                ('iop_od', models.DecimalField(blank=True, decimal_places=1, help_text='Intraocular pressure OD (mmHg)', max_digits=5, null=True)),
                ('iop_os', models.DecimalField(blank=True, decimal_places=1, help_text='Intraocular pressure OS (mmHg)', max_digits=5, null=True)),
                ('diagnosis', models.CharField(blank=True, max_length=500)),
                ('treatment_plan', models.TextField(blank=True)),
                ('special_instructions', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('stat', 'STAT')], default='routine', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('consultation_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eye_orders', to='consultation.consultationsession')),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eye_orders_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eye_orders', to='patients.patient')),
                ('visit', models.ForeignKey(blank=True, help_text='Visit this eye order is associated with', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eye_orders', to='patients.visit')),
            ],
            options={
                'db_table': 'eye_orders',
                'ordering': ['-ordered_at'],
            },
        ),
        migrations.CreateModel(
            name='EyeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('scheduled_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('procedures_performed', models.TextField(blank=True)),
                ('findings', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='eyecare.eyeorder')),
            ],
            options={
                'db_table': 'eye_sessions',
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
