# Generated by Django 4.2.27 on 2026-04-30 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyecare', '0003_eyesessiondiagnosticfile'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='eyesessiondiagnosticfile',
            index=models.Index(fields=['session', 'category'], name='eye_session_session_87d898_idx'),
        ),
    ]
