# Generated by Django 4.2.30 on 2026-05-03 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eyecare', '0004_eyesessiondiagnosticfile_eye_session_session_87d898_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eyesession',
            name='order',
        ),
        migrations.RemoveField(
            model_name='eyesessiondiagnosticfile',
            name='session',
        ),
        migrations.DeleteModel(
            name='EyeOrder',
        ),
        migrations.DeleteModel(
            name='EyeSession',
        ),
        migrations.DeleteModel(
            name='EyeSessionDiagnosticFile',
        ),
    ]
