# Generated by Django 4.2.30 on 2026-06-20 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eyecare', '0009_eyesession_status_completed_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='eyesession',
            name='eye_sess_status_completed_idx',
        ),
    ]
