# Generated by Django 4.2.29 on 2026-03-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_clinics_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='clinics',
            field=models.JSONField(blank=True, default=list, help_text='List of clinic names for this appointment (matches standard clinic list)'),
        ),
    ]
