# Generated by Django 4.2.27 on 2025-12-09 21:04

from django.db import migrations, models
import django.db.models.deletion


def link_consultation_rooms_to_clinic(apps, schema_editor):
    """Link all existing ConsultationRooms to Bode Thomas Clinic."""
    ConsultationRoom = apps.get_model('consultation', 'ConsultationRoom')
    Clinic = apps.get_model('organization', 'Clinic')
    
    # Find or create Bode Thomas Clinic
    clinic = Clinic.objects.filter(code='BODE-THOMAS').first()
    if not clinic:
        clinic = Clinic.objects.filter(name__icontains='Bode Thomas').first()
    
    # If clinic exists, link all ConsultationRooms without a clinic
    if clinic:
        ConsultationRoom.objects.filter(clinic__isnull=True).update(clinic=clinic)


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('consultation', '0002_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationroom',
            name='clinic',
            field=models.ForeignKey(blank=True, help_text='Clinic where this consultation room is located', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultation_rooms', to='organization.clinic'),
        ),
        migrations.AlterField(
            model_name='consultationqueue',
            name='priority',
            field=models.IntegerField(default=0, help_text='Lower number = higher priority. Automatically set from visit_type.'),
        ),
        migrations.AddIndex(
            model_name='consultationroom',
            index=models.Index(fields=['clinic', 'status'], name='consultatio_clinic__f1134a_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationroom',
            index=models.Index(fields=['room_number'], name='consultatio_room_nu_090fb6_idx'),
        ),
        # Data migration: Link all existing ConsultationRooms to Bode Thomas Clinic
        migrations.RunPython(
            code=link_consultation_rooms_to_clinic,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
