# Generated by Django 4.2.27 on 2025-12-19 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0003_add_clinic_to_consultation_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationsession',
            name='chief_complaint',
        ),
    ]
