# Generated by Django 4.2.27 on 2026-01-05 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0008_remove_chief_complaint'),
        ('consultation', '0004_remove_chief_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICD10Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='ICD-10 code (e.g., A00.0, J00)', max_length=10, unique=True)),
                ('description', models.TextField(help_text='Full description of the diagnosis')),
                ('category', models.CharField(blank=True, help_text='ICD-10 category/chapter', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this code is currently active')),
            ],
            options={
                'db_table': 'icd10_codes',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='icd10_codes_code_8fbace_idx'), models.Index(fields=['category'], name='icd10_codes_categor_e05097_idx'), models.Index(fields=['is_active'], name='icd10_codes_is_acti_352da1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_text', models.TextField(blank=True, help_text='Additional diagnosis details or free text')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('suspected', 'Suspected'), ('ruled_out', 'Ruled Out')], default='confirmed', max_length=20)),
                ('certainty', models.CharField(choices=[('confirmed', 'Confirmed'), ('probable', 'Probable'), ('possible', 'Possible')], default='confirmed', max_length=20)),
                ('diagnosed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('diagnosed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnoses_made', to=settings.AUTH_USER_MODEL)),
                ('icd10_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnoses', to='consultation.icd10code')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='patients.patient')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnoses', to='consultation.consultationsession')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnoses', to='patients.visit')),
            ],
            options={
                'db_table': 'diagnoses',
                'ordering': ['-diagnosed_at'],
                'unique_together': {('patient', 'visit', 'icd10_code')},
            },
        ),
    ]
