# Generated by Django 4.2.27 on 2026-01-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0005_add_icd10_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationsession',
            name='presentation_complaint',
            field=models.TextField(blank=True, help_text='Chief complaint or presenting symptoms'),
        ),
    ]
