# Generated by Django 4.2.27 on 2026-01-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0006_add_presentation_complaint'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consultationqueue',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='consultationqueue',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('room', 'patient'), name='unique_active_queue_item'),
        ),
    ]
