# Generated by Codex on 2026-02-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0007_fix_queue_unique_constraint'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='consultationqueue',
            index=models.Index(fields=['is_active', 'queued_at'], name='consult_q_active_queued_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationqueue',
            index=models.Index(fields=['queued_at'], name='consult_q_queued_idx'),
        ),
    ]

