# Generated by Django 4.2.28 on 2026-02-26 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0008_queue_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='consultationqueue',
            name='consult_q_active_queued_idx',
        ),
        migrations.RemoveIndex(
            model_name='consultationqueue',
            name='consult_q_queued_idx',
        ),
    ]
