# Generated by Django 4.2.27 on 2026-03-23 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultation', '0010_backfill_room_clinic_from_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='accepted_at',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='scheduled_at',
        ),
        migrations.AddField(
            model_name='referral',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted_to_records', 'Submitted to Records'), ('records_review', 'Records Review'), ('returned_for_correction', 'Returned for Correction'), ('approved_for_forms', 'Approved for Forms'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=40),
        ),
        migrations.CreateModel(
            name='ResponsibilityFormIssuance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.PositiveIntegerField(default=1)),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('used', 'Used')], default='active', max_length=20)),
                ('hospital_name_snapshot', models.CharField(blank=True, max_length=200)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='referral_forms/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_responsibility_forms', to=settings.AUTH_USER_MODEL)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsibility_forms', to='consultation.referral')),
            ],
            options={
                'db_table': 'responsibility_form_issuances',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='responsibilityformissuance',
            constraint=models.UniqueConstraint(fields=('referral', 'sequence_number'), name='uniq_referral_form_sequence'),
        ),
    ]
