# Generated by Django 4.2.27 on 2026-04-02 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0017_consultationsession_pause_resume_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentingComplaintCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'presenting_complaint_categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PresentingComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('normalized_label', models.CharField(db_index=True, editable=False, max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='consultation.presentingcomplaintcategory')),
            ],
            options={
                'db_table': 'presenting_complaints',
                'ordering': ['category__sort_order', 'category__name', 'sort_order', 'label'],
            },
        ),
        migrations.AddConstraint(
            model_name='presentingcomplaint',
            constraint=models.UniqueConstraint(fields=('category', 'normalized_label'), name='uniq_presenting_complaint_per_category_normalized'),
        ),
    ]
