# Generated by Django 4.2.27 on 2026-05-09 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0019_seed_presenting_complaints_library'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(blank=True, help_text='Optional short code (e.g. for reports / search).', max_length=50)),
                ('facility_type', models.CharField(choices=[('internal', 'Internal - Same Facility'), ('external', 'External - Other Facility'), ('specialist', 'Specialist Clinic')], default='external', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True, help_text='Multi-line postal address printed on referral letters and responsibility forms (e.g. street, area, city).')),
                ('contact_person_title', models.CharField(blank=True, default='The Medical Director', help_text="Addressee role used in the 'To:' block on letters (e.g. 'The Medical Director', 'The Chief Executive Officer').", max_length=100)),
                ('specialties', models.TextField(blank=True, help_text='Optional comma-separated list of specialties this facility accepts (used to prefilter the referral typeahead).')),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Referral facility',
                'verbose_name_plural': 'Referral facilities',
                'db_table': 'referral_facilities',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='referral',
            name='facility_address_snapshot',
            field=models.TextField(blank=True, help_text='Postal address copied from ``facility_partner.address`` at issue time so PDFs always print what was current when the referral was made.'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='facility',
            field=models.CharField(help_text='Receiving facility name. Snapshot copied from ``facility_partner.name`` on save when a partner is selected; free-typed for one-off referrals.', max_length=200),
        ),
        migrations.AddField(
            model_name='referral',
            name='facility_partner',
            field=models.ForeignKey(blank=True, help_text='Catalog row for the receiving facility. May be null when the user typed a one-off facility name.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='consultation.referralfacility'),
        ),
    ]
