# Generated by Django 4.2.30 on 2026-05-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0022_consultationroom_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationroom',
            name='room_type',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('procedure', 'Procedure'), ('emergency', 'Emergency'), ('examination', 'Examination')], db_index=True, default='consultation', max_length=20),
        ),
    ]
