# Generated by Django 4.2.28 on 2026-05-20 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_systemconfig_clinic_default_processing_clinic'),
        ('consultation', '0023_alter_consultationroom_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationsession',
            name='location_clinic',
            field=models.ForeignKey(blank=True, help_text='Clinic where this consultation session takes place', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_sessions', to='organization.clinic'),
        ),
    ]
