# Generated by Django 4.2.27 on 2026-05-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0024_consultationsession_location_clinic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationroom',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='consultationroom',
            name='room_number',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AddConstraint(
            model_name='consultationroom',
            constraint=models.UniqueConstraint(fields=('name', 'clinic'), name='uq_room_name_per_clinic'),
        ),
        migrations.AddConstraint(
            model_name='consultationroom',
            constraint=models.UniqueConstraint(fields=('room_number', 'clinic'), name='uq_room_number_per_clinic'),
        ),
    ]
