# Generated by Django 4.2.30 on 2026-08-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0030_shared_room_multi_doctor_capacity'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='consultationroom',
            name='uq_room_name_per_clinic',
        ),
        migrations.RemoveConstraint(
            model_name='consultationroom',
            name='uq_room_number_per_clinic',
        ),
        migrations.RemoveIndex(
            model_name='consultationroom',
            name='consultatio_clinic__f1134a_idx',
        ),
        migrations.RenameField(
            model_name='consultationroom',
            old_name='clinic',
            new_name='location_clinic',
        ),
        migrations.RenameIndex(
            model_name='consultationroomoccupancy',
            new_name='consultatio_doctor__0d84a0_idx',
            old_name='consultatio_doctor__8f0a2d_idx',
        ),
        migrations.AddIndex(
            model_name='consultationroom',
            index=models.Index(fields=['location_clinic', 'status'], name='consultatio_locatio_2b4fc7_idx'),
        ),
        migrations.AddConstraint(
            model_name='consultationroom',
            constraint=models.UniqueConstraint(fields=('name', 'location_clinic'), name='uq_room_name_per_clinic'),
        ),
        migrations.AddConstraint(
            model_name='consultationroom',
            constraint=models.UniqueConstraint(fields=('room_number', 'location_clinic'), name='uq_room_number_per_clinic'),
        ),
    ]
