# Generated by Django 4.2.30 on 2026-08-07 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wards', '0012_rename_clinic_ward_location_clinic'),
        ('consultation', '0031_remove_consultationroom_uq_room_name_per_clinic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='wards.patientadmission'),
        ),
    ]
