# Generated by Django 4.2.27 on 2026-01-11 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nursing', '0003_add_consultation_session_to_nursing_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0008_remove_chief_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(help_text='Bed number within the ward', max_length=20)),
                ('bed_type', models.CharField(choices=[('standard', 'Standard Bed'), ('icu', 'ICU Bed'), ('ventilator', 'Ventilator Bed'), ('isolation', 'Isolation Bed'), ('maternity', 'Maternity Bed'), ('pediatric', 'Pediatric Bed')], default='standard', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Under Maintenance'), ('reserved', 'Reserved'), ('out_of_service', 'Out of Service')], default='available', max_length=20)),
                ('has_oxygen', models.BooleanField(default=False)),
                ('has_suction', models.BooleanField(default=False)),
                ('has_monitor', models.BooleanField(default=False)),
                ('has_ventilator', models.BooleanField(default=False)),
                ('has_iv_pole', models.BooleanField(default=True)),
                ('admission_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_bed', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Bed',
                'verbose_name_plural': 'Beds',
                'db_table': 'ward_beds',
                'ordering': ['bed_number'],
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_code', models.CharField(db_index=True, help_text='Unique ward code (e.g., WARD-001)', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Ward name (e.g., General Medicine Ward)', max_length=100)),
                ('ward_type', models.CharField(choices=[('general', 'General Medicine'), ('surgical', 'Surgical'), ('medical', 'Medical'), ('pediatric', 'Pediatric'), ('maternity', 'Maternity'), ('icu', 'Intensive Care Unit'), ('ccu', 'Coronary Care Unit'), ('emergency', 'Emergency'), ('isolation', 'Isolation'), ('psychiatric', 'Psychiatric')], default='general', max_length=20)),
                ('floor', models.CharField(blank=True, help_text='Floor location', max_length=50)),
                ('building', models.CharField(blank=True, help_text='Building name', max_length=100)),
                ('total_beds', models.PositiveIntegerField(default=0, help_text='Total number of beds in the ward')),
                ('occupied_beds', models.PositiveIntegerField(default=0, help_text='Currently occupied beds')),
                ('description', models.TextField(blank=True, help_text='Ward description and facilities')),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Under Maintenance'), ('closed', 'Closed')], default='active', max_length=20)),
                ('phone_extension', models.CharField(blank=True, help_text='Ward phone extension', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_wards', to=settings.AUTH_USER_MODEL)),
                ('head_nurse', models.ForeignKey(blank=True, limit_choices_to={'system_role__in': ['Nurse', 'Nursing Officer']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_wards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ward',
                'verbose_name_plural': 'Wards',
                'db_table': 'wards',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PatientAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_id', models.CharField(blank=True, db_index=True, max_length=50, unique=True)),
                ('admission_type', models.CharField(choices=[('emergency', 'Emergency'), ('elective', 'Elective'), ('transfer', 'Transfer from Another Ward'), ('readmission', 'Readmission')], default='elective', max_length=20)),
                ('admission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('admission_diagnosis', models.TextField(help_text='Primary diagnosis for admission')),
                ('presenting_complaint', models.TextField(blank=True)),
                ('admission_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('admitted', 'Admitted'), ('discharged', 'Discharged'), ('transferred', 'Transferred'), ('absconded', 'Absconded'), ('deceased', 'Deceased')], default='admitted', max_length=20)),
                ('current_condition', models.TextField(blank=True, help_text='Current clinical condition')),
                ('discharge_date', models.DateTimeField(blank=True, null=True)),
                ('discharge_type', models.CharField(blank=True, choices=[('regular', 'Regular Discharge'), ('against_medical_advice', 'Against Medical Advice'), ('transfer', 'Transfer to Another Facility'), ('deceased', 'Deceased')], max_length=30)),
                ('discharge_diagnosis', models.TextField(blank=True)),
                ('discharge_notes', models.TextField(blank=True)),
                ('discharge_summary', models.TextField(blank=True)),
                ('follow_up_instructions', models.TextField(blank=True)),
                ('transfer_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admitting_doctor', models.ForeignKey(limit_choices_to={'system_role__in': ['Medical Doctor', 'Consultant', 'Resident Doctor']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to=settings.AUTH_USER_MODEL)),
                ('bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='wards.bed')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_admissions', to=settings.AUTH_USER_MODEL)),
                ('discharge_doctor', models.ForeignKey(blank=True, limit_choices_to={'system_role__in': ['Medical Doctor', 'Consultant', 'Resident Doctor']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discharges', to=settings.AUTH_USER_MODEL)),
                ('nursing_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='nursing.nursingorder')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='patients.patient')),
                ('transfer_to_ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_in', to='wards.ward')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='patients.visit')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='wards.ward')),
            ],
            options={
                'verbose_name': 'Patient Admission',
                'verbose_name_plural': 'Patient Admissions',
                'db_table': 'patient_admissions',
                'ordering': ['-admission_date'],
            },
        ),
        migrations.AddField(
            model_name='bed',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='wards.ward'),
        ),
        migrations.CreateModel(
            name='WardAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('primary', 'Primary Nurse'), ('secondary', 'Secondary Nurse'), ('shift', 'Shift Assignment'), ('specialist', 'Specialist Care')], default='primary', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('transferred', 'Transferred')], default='active', max_length=20)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('responsibilities', models.TextField(blank=True, help_text='Specific nursing responsibilities')),
                ('shift_notes', models.TextField(blank=True, help_text='Shift handover notes')),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_assignments', to='wards.patientadmission')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_nurses', to=settings.AUTH_USER_MODEL)),
                ('nurse', models.ForeignKey(limit_choices_to={'system_role__in': ['Nurse', 'Nursing Officer', 'Midwife']}, on_delete=django.db.models.deletion.CASCADE, related_name='ward_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ward Assignment',
                'verbose_name_plural': 'Ward Assignments',
                'db_table': 'ward_assignments',
                'ordering': ['-assigned_at'],
                'unique_together': {('admission', 'nurse', 'assignment_type')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='bed',
            unique_together={('ward', 'bed_number')},
        ),
    ]
