# Generated by Django 4.2.27 on 2026-01-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientadmission',
            name='ward_assignment',
            field=models.CharField(blank=True, help_text="Specific ward assignment details (e.g., 'Room 201, Bed 3')", max_length=100),
        ),
    ]
