# Generated by Django 4.2.27 on 2026-04-06 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wards', '0004_add_pending_discharge_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionTreatmentRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(blank=True, max_length=200)),
                ('route', models.CharField(blank=True, max_length=100)),
                ('time_administered', models.TimeField(blank=True, null=True)),
                ('time_completed', models.TimeField(blank=True, null=True)),
                ('drug_reaction', models.CharField(blank=True, max_length=500)),
                ('nurse_initials', models.CharField(blank=True, max_length=12)),
                ('doctor_initials', models.CharField(blank=True, max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_sheet_rows', to='wards.patientadmission')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_treatment_sheet_rows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admission_treatment_sheet_rows',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionObservationVital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('pulse', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('respiratory_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bp_systolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bp_diastolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fbs_mmol', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rbs_mmol', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observation_vitals', to='wards.patientadmission')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_observation_vitals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admission_observation_vitals',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
