# Generated by Django 4.2.27 on 2026-05-20 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_backfill_multi_clinic'),
        ('wards', '0007_admission_summary_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='clinic',
            field=models.ForeignKey(blank=True, help_text='Care facility this ward belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wards', to='organization.clinic'),
        ),
    ]
