# Generated by Django 4.2.30 on 2026-08-06 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wards', '0011_backfill_admitting_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ward',
            old_name='clinic',
            new_name='location_clinic',
        ),
    ]
