# Generated by Django 4.2.30 on 2026-08-07 11:31

from django.db import migrations


def backfill_orders_to_admission(apps, schema_editor):
    PatientAdmission = apps.get_model("wards", "PatientAdmission")
    order_models = [
        ("pharmacy", "Prescription", "prescribed_at"),
        ("laboratory", "LabOrder", "ordered_at"),
        ("radiology", "RadiologyOrder", "ordered_at"),
    ]
    for admission in PatientAdmission.objects.select_related("visit").all():
        if not admission.visit_id or not admission.patient_id:
            continue
        start = admission.admission_date
        end = admission.discharge_date
        for app_label, model_name, date_field in order_models:
            Model = apps.get_model(app_label, model_name)
            qs = Model.objects.filter(
                visit_id=admission.visit_id,
                admission__isnull=True,
                **{f"{date_field}__gte": start},
            )
            if end:
                qs = qs.filter(**{f"{date_field}__lte": end})
            qs.update(admission_id=admission.pk)


class Migration(migrations.Migration):

    dependencies = [
        ('wards', '0012_rename_clinic_ward_location_clinic'),
        ('pharmacy', '0045_prescription_admission'),
        ('laboratory', '0025_laborder_admission'),
        ('radiology', '0021_radiologyorder_admission'),
    ]

    operations = [
        migrations.RunPython(backfill_orders_to_admission, migrations.RunPython.noop),
    ]
