# Generated by Django 4.2.30 on 2026-08-10 11:28

from django.db import migrations, models
import django.db.models.deletion


def backfill_consultation_session(apps, schema_editor):
    PatientAdmission = apps.get_model('wards', 'PatientAdmission')
    ConsultationSession = apps.get_model('consultation', 'ConsultationSession')
    rows = []
    for admission in PatientAdmission.objects.filter(consultation_session__isnull=True) \
                                             .exclude(visit__isnull=True) \
                                             .only('id', 'visit_id', 'admission_date'):
        session = (
            ConsultationSession.objects
            .filter(visit_id=admission.visit_id)
            .filter(started_at__lte=admission.admission_date)
            .order_by('-started_at', '-id')
            .first()
        )
        if session is not None:
            rows.append((admission.id, session.id))
    for pk, session_id in rows:
        PatientAdmission.objects.filter(pk=pk).update(consultation_session_id=session_id)


def reverse_backfill(apps, schema_editor):
    pass  # field drop handles cleanup


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0032_referral_admission'),
        ('wards', '0013_backfill_admission_on_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientadmission',
            name='consultation_session',
            field=models.ForeignKey(blank=True, help_text='Consultation session that motivated this admission.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='consultation.consultationsession'),
        ),
        migrations.RunPython(backfill_consultation_session, reverse_backfill),
    ]
