/**
 * Patient-related constants and data
 * Standardized source for all patient forms and medical records
 */

// NPA Divisions
export const NPA_DIVISIONS = [
  "Engineering",
  "Land & Asset Administration",
  "Marine and Operations",
  "Monitoring & Regulation",
  "HSE",
  "Security",
  "Port Managers",
  "HR",
  "Medical",
  "Admin",
  "Finance",
  "Superannuation & Investment",
  "Enterprise Risk Management",
  "Procurement",
  "Corporate & Strategic Communications",
  "Corporate & Strategic Planning",
  "Legal Services",
  "Audit",
  "ICT",
  "PPP",
  "Abuja Liaison Office",
  "Servicom",
  "Overseas Liaison Office",
  "MD's Office"
];

// Non-NPA Types
export const NON_NPA_TYPES = [
  "Police",
  "IT",
  "NYSC",
  "CSR",
  "MD Outfit",
  "Board Member",
  "Seaview"
];

// Employee Types
export const EMPLOYEE_TYPES = [
  "Officer",
  "Staff"
];

// Dependent Types
export const DEPENDENT_TYPES = [
  "Employee Dependent",
  "Retiree Dependent"
];

/**
 * Patient title options — ``value`` must match ``Patient.TITLE_CHOICES`` keys in the backend.
 * Use labels for display (e.g. Hajiya maps to stored value ``hajia``).
 */
export type PatientTitleOption = { readonly value: string; readonly label: string };

export const PATIENT_TITLE_OPTIONS: readonly PatientTitleOption[] = [
  { value: 'mr', label: 'Mr' },
  { value: 'mrs', label: 'Mrs' },
  { value: 'ms', label: 'Ms' },
  { value: 'master', label: 'Master' },
  { value: 'miss', label: 'Miss' },
  { value: 'dr', label: 'Dr' },
  { value: 'chief', label: 'Chief' },
  { value: 'engr', label: 'Engr' },
  { value: 'prof', label: 'Prof' },
  { value: 'alhaji', label: 'Alhaji' },
  { value: 'hajia', label: 'Hajiya' },
  { value: 'mallam', label: 'Mallam' },
  { value: 'lady', label: 'Lady' },
];

const PATIENT_TITLE_VALUE_SET = new Set(PATIENT_TITLE_OPTIONS.map((o) => o.value));

/** Map legacy / mistaken stored values to a valid backend title key (lowercase). */
export function normalizePatientTitleValue(raw: string | null | undefined): string {
  if (!raw) return '';
  const k = String(raw).trim().toLowerCase();
  const aliases: Record<string, string> = { hajiya: 'hajia' };
  const resolved = aliases[k] ?? k;
  return PATIENT_TITLE_VALUE_SET.has(resolved) ? resolved : '';
}

/** Display label for a stored title value (handles legacy keys). */
export function patientTitleLabel(raw: string | null | undefined): string {
  const key = normalizePatientTitleValue(raw);
  if (key) {
    const opt = PATIENT_TITLE_OPTIONS.find((o) => o.value === key);
    if (opt) return opt.label;
  }
  const fallback = String(raw ?? '').trim();
  return fallback ? fallback : '';
}

/** @deprecated Prefer ``PATIENT_TITLE_OPTIONS`` for selects (value/label). */
export const TITLES = PATIENT_TITLE_OPTIONS.map((o) => o.label);

// Marital Statuses
export const MARITAL_STATUSES = [
  'Single',
  'Married',
  'Divorced',
  'Widowed'
];

// Religions
export const RELIGIONS = [
  'Christianity',
  'Islam',
  'Traditional',
  'Other',
  'None'
];

// NOK Relationships
export const NOK_RELATIONSHIPS = [
  'Spouse',
  'Parent',
  'Child',
  'Sibling',
  'Relative',
  'Friend',
  'Other'
];

// Comprehensive list of Nigerian tribes (alphabetical)
export const NIGERIAN_TRIBES = [
  'Abayon',
  'Abua (Odual)',
  'Achipa (Achipawa)',
  'Adara (Kadara)',
  'Affade',
  'Afizere',
  'Afo (Eloyi)',
  'Agbo',
  'Akaju-Ndem (Akajuk)',
  'Akweya-Yachi',
  'Alago (Arago)',
  'Amo',
  'Anaguta',
  'Anang',
  'Andoni',
  'Ankwei',
  'Anyima',
  'Atyap (Kataf/Katab/Attakar/Kagoro)',
  'Auyoka (Sub-Hausa)',
  'Awori',
  'Ayu',
  'Bachama',
  'Bachere',
  'Bada',
  'Bade',
  'Bahumono',
  'Bajju (Kaje/Kajji)',
  'Bakulung',
  'Bali',
  'Bambora (Bambarawa)',
  'Bambuko',
  'Banda (Bandawa)',
  'Banka (Bankalawa)',
  'Banso (Panso)',
  'Bara (Barawa)',
  'Barke',
  'Baruba (Batonu)',
  'Bashiri (Bashirawa)',
  'Bassa',
  'Batta',
  'Baushi',
  'Baya',
  'Bekwarra',
  'Bele (Buli/Belewa)',
  'Berom (Birom)',
  'Betso (Bete)',
  'Bette',
  'Bille (Adamawa)',
  'Bille (Rivers)',
  'Bina (Binawa)',
  'Bini',
  'Bobua',
  'Boki (Nki)',
  'Bokkos',
  'Boko (Bussawa/Bargawa)',
  'Bole (Bolewa)',
  'Boma (Bomawa/Burmano)',
  'Bomboro',
  'Botlere',
  'Buduma',
  'Buji',
  'Buli',
  'Bunu',
  'Burak',
  'Bura-Pabir',
  'Burma (Burmawa)',
  'Buru',
  'Buta (Butawa)',
  'Bwall',
  'Bwatiye',
  'Bwazza',
  'Challa',
  'Chama (Chamawa Fitilai)',
  'Chamba',
  'Chamo',
  'Chibok (Kibaku)',
  'Chinine',
  'Chip',
  'Chokobo',
  'Chukkol',
  'Daba',
  'Dadiya',
  'Daka',
  'Dakarkari',
  'Danda (Dandawa)',
  'Dangsa',
  'Daza (Dere/Derewa)',
  'Deno (Denawa)',
  'Dghwede',
  'Diba',
  'Doemak (Dumuk)',
  'Duguri',
  'Duka (Dukawa)',
  'Duma (Dumawa)',
  'Dundudun (Dunka)',
  'Ebana (Ebani)',
  'Ebira (Egbira)',
  'Ebu',
  'Efik',
  'Egede (Igede)',
  'Eggon',
  'Egun (Gu)',
  'Ejagham',
  'Ekajuk',
  'Eket',
  'Ekoi',
  'Engenni (Ngene)',
  'Epie',
  'Esan (Ishan)',
  'Esit Ekid',
  'Etolu (Etilo)',
  'Etsako',
  'Etung',
  'Etuno',
  'Fulani (Fulbe)',
  'Fyam (Fyem)',
  'Fyer (Fer)',
  'Ga\'anda',
  'Gade',
  'Galambi',
  'Gamergu-Mulgwa',
  'Ganawuri',
  'Gavako',
  'Gbedde',
  'Geji',
  'Gengle',
  'Gera (Gere/Gerawa)',
  'Geruma (Gerumawa)',
  'Gingwak',
  'Gira',
  'Gizigz',
  'Goemai',
  'Gokana (Kana)',
  'Gombi',
  'Gonia',
  'Gornun (Gmun)',
  'Gubi (Gubawa)',
  'Gude',
  'Gudu',
  'Gure',
  'Gurmana',
  'Gururntum',
  'Gusu',
  'Gwa (Gurawa)',
  'Gwamba',
  'Gwandara',
  'Gwari (Gbagyi)',
  'Gwom',
  'Gwong (Kagoma)',
  'Gwoza (Waha)',
  'Gyem',
  'Ham (Hyam/Jaba)',
  'Hausa',
  'Holma',
  'Hona',
  'Ibani',
  'Ibeno',
  'Ibibio',
  'Ichen',
  'Idoma',
  'Igala',
  'Igbira',
  'Igbo',
  'Igede',
  'Ijumu',
  'Ika',
  'Ikom',
  'Iman',
  'Irigwe',
  'Isoko',
  'Itsekiri (Isekiri)',
  'Itu',
  'Itu Mbon Uso',
  'Iyala (Iyalla)',
  'Izon (Ijaw)',
  'Jahuna (Jahunawa)',
  'Jaku',
  'Jara (Jaar Jarawa)',
  'Jere (Jera)',
  'Jero',
  'Jibu',
  'Jidda-Abu',
  'Jimbin',
  'Jipal',
  'Jirai',
  'Joinkrama',
  'Jonjo (Jenjo)',
  'Jukun',
  'Kaba',
  'Kadung',
  'Kajuru',
  'Kaka',
  'Kalabari',
  'Kamaku',
  'Kambari',
  'Kambu',
  'Kamwe',
  'Kanakuru (Dera)',
  'Kanembu',
  'Kanikon',
  'Kantana',
  'Kanuri',
  'Karai-karai',
  'Karimjo',
  'Kariya',
  'Ke',
  'Kenern (Koenoem)',
  'Kenton',
  'Kiballo',
  'Kilba',
  'Kirfi',
  'Kodei',
  'Kona',
  'Kono',
  'Koro (Kwaro)',
  'Kubi',
  'Kudachano',
  'Kugama',
  'Kugbo',
  'Kulere (Kaler)',
  'Kunini',
  'Kurama (Akurmi)',
  'Kurdul',
  'Kushi',
  'Kuteb',
  'Kutin',
  'Kwale',
  'Kwalla',
  'Kwami (Kwom)',
  'Kwanchi',
  'Kwaro',
  'Kwato',
  'Kyenga (Kengawa)',
  'Laaru (Larawa)',
  'Lakka',
  'Lala',
  'Lama',
  'Lamja',
  'Lau',
  'Limono',
  'Longuda',
  'Lopa (Lupa)',
  'Mabo',
  'Mada',
  'Mafa',
  'Mama',
  'Mambilla',
  'Mandara (Wandala)',
  'Manga',
  'Margi (Marghi)',
  'Mbol',
  'Mbembe',
  'Mbube',
  'Mbula',
  'Mbum',
  'Memyang (Meryan)',
  'Milighili (Mighili)',
  'Miya (Miyawa)',
  'Mobber',
  'Montol',
  'Moruwa',
  'Muchaila',
  'Mumuye',
  'Mundang',
  'Munga (Lelau)',
  'Munga (Mupang)',
  'Mupun',
  'Mushere',
  'Mwahavul (Mwaghavul)',
  'Ndoro',
  'Ngas (Angas)',
  'Ngizim',
  'Ngweshe',
  'Ningi',
  'Ninzam (Ninzo)',
  'Njayi',
  'Nkim',
  'Nkum',
  'Nokere',
  'Nunku',
  'Nupe',
  'Nyam',
  'Nyandang',
  'Nyiffon',
  'Obolo',
  'Ododop',
  'Ogba',
  'Ogori',
  'Okobo (Okkobor)',
  'Okirika',
  'Okpamheri',
  'Olukumi',
  'Oron',
  'Ososo',
  'Owan',
  'Owe',
  'Oworo',
  'Pa\'a (Pa\'awa Afawa)',
  'Pai',
  'Palli',
  'Panyam',
  'Pero',
  'Pire',
  'Pkanzom',
  'Polchi Habe',
  'Poll',
  'Pongo (Pongu)',
  'Potopo',
  'Pyapun (Piapung)',
  'Qua',
  'Rebina (Rebinawa)',
  'Reshe',
  'Rindire',
  'Rishuwa',
  'Ron',
  'Rubu',
  'Rukuba',
  'Rumada',
  'Rumaya',
  'Sakbe',
  'Sanga',
  'Sate',
  'Saya (Sayawa Za\'ar)',
  'Segidi (Sigidawa)',
  'Shanga',
  'Shangawa',
  'Shan-Shan',
  'Shira',
  'Shomo',
  'Shuwa (Baggara Arabs)',
  'Sikdi',
  'Siri (Sirawa)',
  'Srubu (Surubu)',
  'Sukur',
  'Sura',
  'Tangale',
  'Tarok (Yergam)',
  'Teme',
  'Tera (Terawa)',
  'Teshena (Teshenawa)',
  'Tigon',
  'Tikar',
  'Tiv',
  'Tula',
  'Tur',
  'Ubbo',
  'Udekeama',
  'Ufia',
  'Ukelle',
  'Uncinda',
  'Uneme (Ineme)',
  'Ura (Ula)',
  'Urhobo',
  'Utonkong',
  'Uwanno (Weppa-Wanno)',
  'Uyanga',
  'Vemgo',
  'Verre',
  'Vommi',
  'Wagga',
  'Waja',
  'Waka',
  'Warja',
  'Warji',
  'Wurbo',
  'Wurkun',
  'Yache',
  'Yagba',
  'Yakurr (Yako)',
  'Yalla',
  'Yandang',
  'Yoruba',
  'Yungur',
  'Yuom',
  'Zabara',
  'Zaranda',
  'Zarma (Zarmawa)',
  'Zayam (Zeam)',
  'Zul (Zulawa)',
  'Other',
];

// Nigeria States (alphabetical)
export const NIGERIA_STATES = [
  'Abia', 'Adamawa', 'Akwa Ibom', 'Anambra', 'Bauchi', 'Bayelsa', 'Benue', 'Borno',
  'Cross River', 'Delta', 'Ebonyi', 'Edo', 'Ekiti', 'Enugu', 'FCT', 'Gombe', 'Imo',
  'Jigawa', 'Kaduna', 'Kano', 'Katsina', 'Kebbi', 'Kogi', 'Kwara', 'Lagos', 'Nasarawa',
  'Niger', 'Ogun', 'Ondo', 'Osun', 'Oyo', 'Plateau', 'Rivers', 'Sokoto', 'Taraba',
  'Yobe', 'Zamfara'
];

// Nigeria States with LGAs
export type StateWithLGAs = {
  name: string;
  lgas: string[];
};

export const NIGERIA_STATES_AND_LGAS: StateWithLGAs[] = [
  { name: "Abia", lgas: ["Aba North", "Aba South", "Arochukwu", "Bende", "Ikwuano", "Isiala Ngwa North", "Isiala Ngwa South", "Isuikwuato", "Obi Ngwa", "Ohafia", "Osisioma", "Ugwunagbo", "Ukwa East", "Ukwa West", "Umuahia North", "Umuahia South", "Umu Nneochi"] },
  { name: "Adamawa", lgas: ["Demsa", "Fufure", "Ganye", "Gayuk", "Gombi", "Grie", "Hong", "Jada", "Lamurde", "Madagali", "Maiha", "Mayo Belwa", "Michika", "Mubi North", "Mubi South", "Numan", "Shelleng", "Song", "Toungo", "Yola North", "Yola South"] },
  { name: "Akwa Ibom", lgas: ["Abak", "Eastern Obolo", "Eket", "Esit Eket", "Essien Udim", "Etim Ekpo", "Etinan", "Ibeno", "Ibesikpo Asutan", "Ibiono-Ibom", "Ika", "Ikono", "Ikot Abasi", "Ikot Ekpene", "Ini", "Itu", "Mbo", "Mkpat-Enin", "Nsit-Atai", "Nsit-Ibom", "Nsit-Ubium", "Obot Akara", "Okobo", "Onna", "Oron", "Oruk Anam", "Udung-Uko", "Ukanafun", "Uruan", "Urue-Offong/Oruko", "Uyo"] },
  { name: "Anambra", lgas: ["Aguata", "Anambra East", "Anambra West", "Anaocha", "Awka North", "Awka South", "Ayamelum", "Dunukofia", "Ekwusigo", "Idemili North", "Idemili South", "Ihiala", "Njikoka", "Nnewi North", "Nnewi South", "Ogbaru", "Onitsha North", "Onitsha South", "Orumba North", "Orumba South", "Oyi"] },
  { name: "Bauchi", lgas: ["Alkaleri", "Bauchi", "Bogoro", "Damban", "Darazo", "Dass", "Gamawa", "Ganjuwa", "Giade", "Itas/Gadau", "Jama'are", "Katagum", "Kirfi", "Misau", "Ningi", "Shira", "Tafawa Balewa", "Toro", "Warji", "Zaki"] },
  { name: "Bayelsa", lgas: ["Brass", "Ekeremor", "Kolokuma/Opokuma", "Nembe", "Ogbia", "Sagbama", "Southern Ijaw", "Yenagoa"] },
  { name: "Benue", lgas: ["Agatu", "Apa", "Ado", "Buruku", "Gboko", "Guma", "Gwer East", "Gwer West", "Katsina-Ala", "Konshisha", "Kwande", "Logo", "Makurdi", "Obi", "Ogbadibo", "Ohimini", "Oju", "Okpokwu", "Oturkpo", "Tarka", "Ukum", "Ushongo", "Vandeikya"] },
  { name: "Borno", lgas: ["Abadam", "Askira/Uba", "Bama", "Bayo", "Biu", "Chibok", "Damboa", "Dikwa", "Gubio", "Guzamala", "Gwoza", "Hawul", "Jere", "Kaga", "Kala/Balge", "Konduga", "Kukawa", "Kwaya Kusar", "Mafa", "Magumeri", "Maiduguri", "Marte", "Mobbar", "Monguno", "Ngala", "Nganzai", "Shani"] },
  { name: "Cross River", lgas: ["Abi", "Akamkpa", "Akpabuyo", "Bakassi", "Bekwarra", "Biase", "Boki", "Calabar Municipal", "Calabar South", "Etung", "Ikom", "Obanliku", "Obubra", "Obudu", "Odukpani", "Ogoja", "Yakuur", "Yala"] },
  { name: "Delta", lgas: ["Aniocha North", "Aniocha South", "Bomadi", "Burutu", "Ethiope East", "Ethiope West", "Ika North East", "Ika South", "Isoko North", "Isoko South", "Ndokwa East", "Ndokwa West", "Okpe", "Oshimili North", "Oshimili South", "Patani", "Sapele", "Udu", "Ughelli North", "Ughelli South", "Ukwuani", "Uvwie", "Warri North", "Warri South", "Warri South West"] },
  { name: "Ebonyi", lgas: ["Abakaliki", "Afikpo North", "Afikpo South", "Ebonyi", "Ezza North", "Ezza South", "Ikwo", "Ishielu", "Ivo", "Izzi", "Ohaozara", "Ohaukwu", "Onicha"] },
  { name: "Edo", lgas: ["Akoko-Edo", "Egor", "Esan Central", "Esan North-East", "Esan South-East", "Esan West", "Etsako Central", "Etsako East", "Etsako West", "Igueben", "Ikpoba Okha", "Orhionmwon", "Oredo", "Ovia North-East", "Ovia South-West", "Owan East", "Owan West", "Uhunmwonde"] },
  { name: "Ekiti", lgas: ["Ado Ekiti", "Efon", "Ekiti East", "Ekiti South-West", "Ekiti West", "Emure", "Gbonyin", "Ido Osi", "Ijero", "Ikere", "Ikole", "Ilejemeje", "Irepodun/Ifelodun", "Ise/Orun", "Moba", "Oye"] },
  { name: "Enugu", lgas: ["Aninri", "Awgu", "Enugu East", "Enugu North", "Enugu South", "Ezeagu", "Igbo Etiti", "Igbo Eze North", "Igbo Eze South", "Isi Uzo", "Nkanu East", "Nkanu West", "Nsukka", "Oji River", "Udenu", "Udi", "Uzo Uwani"] },
  { name: "FCT", lgas: ["Abaji", "Bwari", "Gwagwalada", "Kuje", "Kwali", "Municipal Area Council"] },
  { name: "Gombe", lgas: ["Akko", "Balanga", "Billiri", "Dukku", "Funakaye", "Gombe", "Kaltungo", "Kwami", "Nafada", "Shongom", "Yamaltu/Deba"] },
  { name: "Imo", lgas: ["Aboh Mbaise", "Ahiazu Mbaise", "Ehime Mbano", "Ezinihitte", "Ideato North", "Ideato South", "Ihitte/Uboma", "Ikeduru", "Isiala Mbano", "Isu", "Mbaitoli", "Ngor Okpala", "Njaba", "Nkwerre", "Nwangele", "Obowo", "Oguta", "Ohaji/Egbema", "Okigwe", "Orlu", "Orsu", "Oru East", "Oru West", "Owerri Municipal", "Owerri North", "Owerri West", "Unuimo"] },
  { name: "Jigawa", lgas: ["Auyo", "Babura", "Biriniwa", "Birnin Kudu", "Buji", "Dutse", "Gagarawa", "Garki", "Gumel", "Guri", "Gwaram", "Gwiwa", "Hadejia", "Jahun", "Kafur", "Kaita", "Kankara", "Kankia", "Katsina", "Kurfi", "Kusada", "Mai'Adua", "Malumfashi", "Mani", "Mashi", "Matazu", "Musawa", "Rimi", "Roni", "Sule Tankarkar", "Taura", "Yankwashi"] },
  { name: "Kaduna", lgas: ["Birnin Gwari", "Chikun", "Giwa", "Igabi", "Ikara", "Jaba", "Jema'a", "Kachia", "Kaduna North", "Kaduna South", "Kagarko", "Kajuru", "Kaura", "Kauru", "Kubau", "Kudan", "Lere", "Makarfi", "Sabon Gari", "Sanga", "Soba", "Zangon Kataf", "Zaria"] },
  { name: "Kano", lgas: ["Ajingi", "Albasu", "Bagwai", "Bebeji", "Bichi", "Bunkure", "Dala", "Dambatta", "Dawakin Kudu", "Dawakin Tofa", "Doguwa", "Fagge", "Gabasawa", "Garko", "Garun Mallam", "Gaya", "Gezawa", "Gwale", "Gwarzo", "Kabo", "Kano Municipal", "Karaye", "Kibiya", "Kiru", "Kumbotso", "Kunchi", "Kura", "Madobi", "Makoda", "Minjibir", "Nasarawa", "Rano", "Rimin Gado", "Rogo", "Shanono", "Sumaila", "Takai", "Tarauni", "Tofa", "Tsanyawa", "Tudun Wada", "Ungogo", "Warawa", "Wudil"] },
  { name: "Katsina", lgas: ["Bakori", "Batagarawa", "Batsari", "Baure", "Bindawa", "Charanchi", "Dandume", "Danja", "Dan Musa", "Daura", "Dutsi", "Dutsin Ma", "Faskari", "Funtua", "Ingawa", "Jibia", "Kafur", "Kaita", "Kankara", "Kankia", "Katsina", "Kurfi", "Kusada", "Mai'Adua", "Malumfashi", "Mani", "Mashi", "Matazu", "Musawa", "Rimi", "Sabuwa", "Safana", "Sandamu", "Zango"] },
  { name: "Kebbi", lgas: ["Aleiro", "Arewa Dandi", "Argungu", "Augie", "Bagudo", "Birnin Kebbi", "Bunza", "Dandi", "Fakai", "Gwandu", "Jega", "Kalgo", "Koko/Besse", "Maiyama", "Ngaski", "Sakaba", "Shanga", "Suru", "Wasagu/Danko", "Yauri", "Zuru"] },
  { name: "Kogi", lgas: ["Adavi", "Ajaokuta", "Ankpa", "Bassa", "Dekina", "Ibaji", "Idah", "Igalamela Odolu", "Ijumu", "Kabba/Bunu", "Kogi", "Lokoja", "Mopa Muro", "Ofu", "Ogori/Magongo", "Okehi", "Okene", "Olamaboro", "Omala", "Yagba East", "Yagba West"] },
  { name: "Kwara", lgas: ["Asa", "Baruten", "Edu", "Ekiti", "Ifelodun", "Ilorin East", "Ilorin South", "Ilorin West", "Irepodun", "Isin", "Kaiama", "Moro", "Offa", "Oke Ero", "Oyun", "Pategi"] },
  { name: "Lagos", lgas: ["Agege", "Ajeromi-Ifelodun", "Alimosho", "Amuwo-Odofin", "Apapa", "Badagry", "Epe", "Eti Osa", "Ibeju-Lekki", "Ifako-Ijaiye", "Ikeja", "Ikorodu", "Kosofe", "Lagos Island", "Lagos Mainland", "Mushin", "Ojo", "Oshodi-Isolo", "Shomolu", "Surulere"] },
  { name: "Nasarawa", lgas: ["Akwanga", "Awe", "Doma", "Karu", "Keana", "Keffi", "Kokona", "Lafia", "Nasarawa", "Nasarawa Egon", "Obi", "Toto", "Wamba"] },
  { name: "Niger", lgas: ["Agaie", "Agwara", "Bida", "Borgu", "Bosso", "Chanchaga", "Edati", "Gbako", "Gurara", "Katcha", "Kontagora", "Lapai", "Lavun", "Magama", "Mariga", "Mashegu", "Mokwa", "Moya", "Paikoro", "Rafi", "Rijau", "Shiroro", "Suleja", "Tafa", "Wushishi"] },
  { name: "Ogun", lgas: ["Abeokuta North", "Abeokuta South", "Ado-Odo/Ota", "Egbado North", "Egbado South", "Ewekoro", "Ifo", "Ijebu East", "Ijebu North", "Ijebu North East", "Ijebu Ode", "Ikenne", "Imeko Afon", "Ipokia", "Obafemi Owode", "Odeda", "Odogbolu", "Ogun Waterside", "Remo North", "Shagamu"] },
  { name: "Ondo", lgas: ["Akoko North-East", "Akoko North-West", "Akoko South-West", "Akoko South-East", "Akure North", "Akure South", "Ese Odo", "Idanre", "Ifedore", "Ilaje", "Ile Oluji/Okeigbo", "Irele", "Odigbo", "Okitipupa", "Ondo East", "Ondo West", "Ose", "Owo"] },
  { name: "Osun", lgas: ["Atakunmosa East", "Atakunmosa West", "Aiyedaade", "Aiyedire", "Boluwaduro", "Boripe", "Ede North", "Ede South", "Ife Central", "Ife East", "Ife North", "Ife South", "Egbedore", "Ejigbo", "Ifedayo", "Ifelodun", "Ila", "Ilesa East", "Ilesa West", "Irepodun", "Irewole", "Isokan", "Iwo", "Obokun", "Odo Otin", "Ola Oluwa", "Olorunda", "Oriade", "Orolu", "Osogbo"] },
  { name: "Oyo", lgas: ["Afijio", "Akinyele", "Atiba", "Atisbo", "Egbeda", "Ibadan North", "Ibadan North-East", "Ibadan North-West", "Ibadan South-East", "Ibadan South-West", "Ibarapa Central", "Ibarapa East", "Ibarapa North", "Ido", "Irepo", "Iseyin", "Itesiwaju", "Iwajowa", "Kajola", "Lagelu", "Ogbomosho North", "Ogbomosho South", "Ogo Oluwa", "Olorunsogo", "Oluyole", "Ona Ara", "Orelope", "Ori Ire", "Oyo East", "Oyo West", "Saki East", "Saki West", "Surulere"] },
  { name: "Plateau", lgas: ["Barkin Ladi", "Bassa", "Bokkos", "Jos East", "Jos North", "Jos South", "Kanam", "Kanke", "Langtang North", "Langtang South", "Mangu", "Mikang", "Pankshin", "Qua'an Pan", "Riyom", "Shendam", "Wase"] },
  { name: "Rivers", lgas: ["Abua/Odual", "Ahoada East", "Ahoada West", "Akuku-Toru", "Andoni", "Asari-Toru", "Bonny", "Degema", "Eleme", "Emohua", "Etche", "Gokana", "Ikwerre", "Khana", "Obio/Akpor", "Ogba/Egbema/Ndoni", "Ogu/Bolo", "Okrika", "Omuma", "Opobo/Nkoro", "Oyigbo", "Port Harcourt", "Tai"] },
  { name: "Sokoto", lgas: ["Binji", "Bodinga", "Dange Shuni", "Gada", "Goronyo", "Gudu", "Gwadabawa", "Illela", "Isa", "Kebbe", "Kware", "Rabah", "Sabon Birni", "Shagari", "Silame", "Sokoto North", "Sokoto South", "Tambuwal", "Tangaza", "Tureta", "Wamako", "Wurno", "Yabo"] },
  { name: "Taraba", lgas: ["Ardo Kola", "Bali", "Donga", "Gashaka", "Gassol", "Ibi", "Jalingo", "Karim Lamido", "Kumi", "Lau", "Sardauna", "Takum", "Ussa", "Wukari", "Yorro", "Zing"] },
  { name: "Yobe", lgas: ["Bade", "Bursari", "Damaturu", "Fika", "Fune", "Geidam", "Gujba", "Gulani", "Jakusko", "Karasuwa", "Machina", "Nangere", "Nguru", "Potiskum", "Tarmuwa", "Yunusari", "Yusufari"] },
  { name: "Zamfara", lgas: ["Anka", "Bakura", "Birnin Magaji/Kiyaw", "Bukkuyum", "Bungudu", "Gummi", "Gusau", "Kaura Namoda", "Maradun", "Maru", "Shinkafi", "Talata Mafara", "Chafe", "Zurmi"] }
];