
export const MEDICATION_CATEGORIES = [
  { value: 'All Categories', label: 'All Categories' },
  { value: 'Antibiotics', label: 'Antibiotics' },
  { value: 'Antimalarials', label: 'Antimalarials' },
  { value: 'Antihypertensives', label: 'Antihypertensives' },
  { value: 'Antidiabetics', label: 'Antidiabetics' },
  { value: 'Analgesics', label: 'Analgesics (painkillers)' },
  { value: 'Antipyretics', label: 'Antipyretics' },
  { value: 'NSAIDs', label: 'Anti-inflammatory drugs (NSAIDs)' },
  { value: 'Antidepressants', label: 'Antidepressants' },
  { value: 'Antipsychotics', label: 'Antipsychotics' },
  { value: 'Anxiolytics', label: 'Anxiolytics' },
  { value: 'Sedatives', label: 'Sedatives & hypnotics' },
  { value: 'Anticonvulsants', label: 'Anticonvulsants (antiepileptics)' },
  { value: 'Antiemetics', label: 'Antiemetics' },
  { value: 'Antihistamines', label: 'Antihistamines' },
  { value: 'AntiAsthmatics', label: 'Anti-asthmatics / bronchodilators' },
  { value: 'Antitussives', label: 'Antitussives (cough suppressants)' },
  { value: 'Expectorants', label: 'Expectorants' },
  { value: 'Antacids', label: 'Antacids' },
  { value: 'AntiUlcer', label: 'Anti-ulcer drugs' },
  { value: 'Laxatives', label: 'Laxatives' },
  { value: 'Antidiarrhoeals', label: 'Antidiarrhoeals' },
  { value: 'Anthelmintics', label: 'Anthelmintics (anti-worm)' },
  { value: 'Antifungals', label: 'Antifungals' },
  { value: 'Antivirals', label: 'Antivirals' },
  { value: 'Antiprotozoals', label: 'Antiprotozoals' },
  { value: 'Antitubercular', label: 'Antitubercular drugs' },
  { value: 'Antiretrovirals', label: 'Antiretrovirals (HIV drugs)' },
  { value: 'Immunosuppressants', label: 'Immunosuppressants' },
  { value: 'Vaccines', label: 'Vaccines & immunologicals' },
  { value: 'Vitamins', label: 'Vitamins' },
  { value: 'Minerals', label: 'Minerals & supplements' },
  { value: 'Hormonal', label: 'Hormonal drugs' },
  { value: 'Contraceptives', label: 'Contraceptives' },
  { value: 'Corticosteroids', label: 'Corticosteroids' },
  { value: 'Diuretics', label: 'Diuretics' },
  { value: 'Cardiac', label: 'Cardiac drugs (anti-arrhythmics, etc.)' },
  { value: 'LipidLowering', label: 'Lipid-lowering agents' },
  { value: 'Haematinics', label: 'Haematinics (iron, folic acid)' },
  { value: 'Anticoagulants', label: 'Anticoagulants' },
  { value: 'Antiplatelet', label: 'Antiplatelet drugs' },
  { value: 'Antigout', label: 'Antigout drugs' },
  { value: 'MuscleRelaxants', label: 'Muscle relaxants' },
  { value: 'LocalAnaesthetics', label: 'Local anaesthetics' },
  { value: 'GeneralAnaesthetics', label: 'General anaesthetics' },
  { value: 'Ophthalmic', label: 'Ophthalmic preparations' },
  { value: 'Dermatological', label: 'Dermatological agents' },
  { value: 'ENT', label: 'ENT preparations' },
  { value: 'Urological', label: 'Urological drugs' },
  { value: 'Obstetric', label: 'Obstetric & gynaecological drugs' },
  { value: 'Emergency', label: 'Emergency / resuscitation drugs' },
  { value: 'AntiParkinson', label: 'Anti-Parkinson’s drugs' },
  { value: 'AntiAlzheimer', label: 'Anti-Alzheimer’s drugs' },
  { value: 'AntiMigraine', label: 'Anti-migraine drugs' },
  { value: 'Antispasmodics', label: 'Antispasmodics' },
  { value: 'Anticholinergics', label: 'Anticholinergics' },
  { value: 'Cholinergic', label: 'Cholinergic agents' },
  { value: 'Antifibrinolytics', label: 'Antifibrinolytics' },
  { value: 'Thrombolytics', label: 'Thrombolytics' },
  { value: 'PlasmaExpanders', label: 'Plasma expanders' },
  { value: 'BloodProducts', label: 'Blood products' },
  { value: 'Erythropoiesis', label: 'Erythropoiesis-stimulating agents' },
  { value: 'GrowthHormones', label: 'Growth hormones' },
  { value: 'Thyroid', label: 'Thyroid & antithyroid drugs' },
  { value: 'Osteoporosis', label: 'Osteoporosis drugs' },
  { value: 'CalciumRegulators', label: 'Calcium regulators' },
  { value: 'Bisphosphonates', label: 'Bisphosphonates' },
  { value: 'AntiObesity', label: 'Anti-obesity drugs' },
  { value: 'AppetiteStimulants', label: 'Appetite stimulants' },
  { value: 'ChemoAntiemetics', label: 'Anti-emetics (chemo-related)' },
  { value: 'Cytotoxic', label: 'Cytotoxic / anticancer drugs' },
  { value: 'TargetedCancer', label: 'Targeted cancer therapies' },
  { value: 'Radiopharmaceuticals', label: 'Radiopharmaceuticals' },
  { value: 'Antidotes', label: 'Antidotes & chelating agents' },
  { value: 'AntiSnakeVenom', label: 'Anti-snake venom & antisera' },
  { value: 'Immunostimulants', label: 'Immunostimulants' },
  { value: 'Biologicals', label: 'Biologicals / monoclonal antibodies' },
  { value: 'EnzymeReplacement', label: 'Enzyme replacement therapies' },
  { value: 'Fertility', label: 'Fertility drugs' },
  { value: 'Tocolytics', label: 'Tocolytics' },
  { value: 'Uterotonics', label: 'Uterotonics' },
  { value: 'ErectileDysfunction', label: 'Erectile dysfunction drugs' },
  { value: 'BPH', label: 'Benign prostatic hyperplasia (BPH) drugs' },
  { value: 'UrinaryAlkalinisers', label: 'Urinary alkalinisers' },
  { value: 'UrinaryAcidifiers', label: 'Urinary acidifiers' },
  { value: 'RespiratoryStimulants', label: 'Respiratory stimulants' },
  { value: 'PulmonaryHypertension', label: 'Pulmonary hypertension drugs' },
  { value: 'SmokingCessation', label: 'Smoking cessation drugs' },
  { value: 'AlcoholDependence', label: 'Alcohol dependence drugs' },
  { value: 'OpioidDependence', label: 'Opioid dependence drugs' },
  { value: 'AntiGlaucoma', label: 'Anti-glaucoma drugs' },
  { value: 'Mydriatics', label: 'Mydriatics & miotics' },
  { value: 'Otic', label: 'Otic (ear) preparations' },
  { value: 'NasalDecongestants', label: 'Nasal decongestants' },
  { value: 'Photosensitising', label: 'Photosensitising agents' },
  { value: 'Sunscreens', label: 'Sunscreens & photoprotectives' },
  { value: 'WoundCare', label: 'Wound-care agents' },
  { value: 'Antiseptics', label: 'Antiseptics & disinfectants' },
  { value: 'Diagnostic', label: 'Diagnostic agents' },
  { value: 'ContrastMedia', label: 'Contrast media' },
  { value: 'Nutritional', label: 'Nutritional formulas / enteral feeds' },
  { value: 'AntiLeprosy', label: 'Anti-leprosy drugs' },
  { value: 'AntiAmoebic', label: 'Anti-amoebic drugs' },
  { value: 'AntiGiardial', label: 'Anti-giardial drugs' },
  { value: 'AntiTrypanosomal', label: 'Anti-trypanosomal drugs' },
  { value: 'AntiToxoplasmosis', label: 'Anti-toxoplasmosis drugs' },
  { value: 'AntiCryptosporidial', label: 'Anti-cryptosporidial drugs' },
  { value: 'AntiOpportunistic', label: 'Anti-opportunistic infection drugs' },
  { value: 'Antifilarial', label: 'Antifilarial drugs' },
  { value: 'Antischistosomal', label: 'Antischistosomal drugs' },
  { value: 'Antiscabies', label: 'Antiscabies drugs' },
  { value: 'Antipediculosis', label: 'Antipediculosis drugs' },
  { value: 'AntiPruritic', label: 'Anti-pruritic drugs' },
  { value: 'AntiPsoriatic', label: 'Anti-psoriatic drugs' },
  { value: 'AntiAcne', label: 'Anti-acne drugs' },
  { value: 'SkinDepigmenting', label: 'Skin depigmenting agents' },
  { value: 'Keratolytic', label: 'Keratolytic agents' },
  { value: 'Emollients', label: 'Emollients & moisturisers' },
  { value: 'AntiDandruff', label: 'Anti-dandruff agents' },
  { value: 'Dental', label: 'Dental & oral care drugs' },
  { value: 'SalivaSubstitutes', label: 'Saliva substitutes' },
  { value: 'ArtificialTears', label: 'Artificial tears' },
  { value: 'ContactLens', label: 'Contact-lens solutions' },
  { value: 'NasalSaline', label: 'Nasal saline preparations' },
  { value: 'ThroatLozenges', label: 'Throat lozenges & sprays' },
  { value: 'Probiotics', label: 'Probiotics' },
  { value: 'Prebiotics', label: 'Prebiotics' },
  { value: 'DigestiveEnzymes', label: 'Digestive enzymes' },
  { value: 'BileAcid', label: 'Bile acid sequestrants' },
  { value: 'Gallstone', label: 'Gallstone dissolution drugs' },
  { value: 'Hepatoprotective', label: 'Hepatoprotective agents' },
  { value: 'PancreaticEnzymes', label: 'Pancreatic enzyme replacements' },
  { value: 'AntiEmeticRehydration', label: 'Anti-emetic rehydration agents' },
  { value: 'OralRehydration', label: 'Oral rehydration solutions' },
  { value: 'ParenteralNutrition', label: 'Parenteral nutrition products' },
  { value: 'Dialysis', label: 'Dialysis solutions' },
  { value: 'PeritonealDialysis', label: 'Peritoneal dialysis fluids' },
  { value: 'IVFluids', label: 'Intravenous fluids' },
  { value: 'Electrolytes', label: 'Electrolyte preparations' },
  { value: 'AcidBase', label: 'Acid-base correcting agents' },
  { value: 'Oxygen', label: 'Oxygen & medical gases' },
  { value: 'PlasmaSubstitutes', label: 'Plasma substitutes' },
  { value: 'VaccinationAdjuvants', label: 'Vaccination adjuvants' },
  { value: 'ColdChain', label: 'Cold-chain biologicals' },
  { value: 'VeterinaryCrossover', label: 'Veterinary-human crossover drugs' },
  { value: 'EmergencyAntidotal', label: 'Emergency antidotal kits' },
  { value: 'DisasterResponse', label: 'Disaster-response medicines' },
  { value: 'TravelMedicine', label: 'Travel-medicine drugs' },
  { value: 'OccupationalHealth', label: 'Occupational-health medicines' },
  { value: 'Geriatric', label: 'Geriatric-specific medicines' },
  { value: 'Paediatric', label: 'Paediatric-specific medicines' },
  { value: 'Other', label: 'Other' },
];

export const DOSAGE_FORMS = ['Tablet', 'Capsule', 'Softgel Capsule', 'Syrup', 'Injection', 'Cream', 'Ointment', 'Drops', 'Inhaler', 'Suspension', 'Powder', 'Lozenge', 'Suppository', 'Patch', 'Gel', 'Spray', 'Solution', 'Other'];

export const MEDICATION_STRENGTHS = [
  // Solids (mg)
  '1mg', '2mg', '2.5mg', '4mg', '5mg', '10mg', '12.5mg', '20mg', '25mg', '30mg', '40mg', '50mg', '60mg', '75mg', '81mg', '100mg', '125mg', '150mg', '200mg', '250mg', '300mg', '350mg', '400mg', '450mg', '500mg', '600mg', '650mg', '750mg', '800mg', '850mg', '875mg', '1000mg',
  // Solids (g)
  '0.5g', '1g', '2g', '3g', '4g', '5g', '10g',
  // Solids (mcg)
  '10mcg', '20mcg', '25mcg', '30mcg', '50mcg', '75mcg', '88mcg', '100mcg', '125mcg', '150mcg', '175mcg', '200mcg', '300mcg', '400mcg', '500mcg',
  // Liquids (mg/ml)
  '0.5mg/ml', '1mg/ml', '2mg/ml', '4mg/ml', '5mg/ml', '8mg/ml', '10mg/ml', '15mg/ml', '20mg/ml', '25mg/ml', '30mg/ml', '40mg/ml', '50mg/ml', '60mg/ml', '80mg/ml', '100mg/ml', '150mg/ml', '200mg/ml', '250mg/ml',
  // Syrups/Suspensions (mg/5ml)
  '5mg/5ml', '10mg/5ml', '15mg/5ml', '100mg/5ml', '120mg/5ml', '125mg/5ml', '200mg/5ml', '250mg/5ml', '400mg/5ml', '600mg/5ml',
  // Percentages (Topical/Drops)
  '0.01%', '0.02%', '0.025%', '0.05%', '0.1%', '0.2%', '0.25%', '0.5%', '1%', '2%', '2.5%', '3%', '4%', '5%', '10%', '15%', '20%',
  // Units (IU)
  '10IU', '20IU', '40IU', '50IU', '100IU', '500IU', '1000IU', '2000IU', '5000IU', '10000IU', '20000IU', '40000IU', '50000IU', '100000IU',
  // Volume (ml - for IV fluids etc)
  '2ml', '5ml', '10ml', '15ml', '20ml', '30ml', '50ml', '100ml', '200ml', '500ml', '1000ml',
  // Combinations
  '5mg/1.25mg', '20mg/12.5mg', '50mg/12.5mg', '100mg/25mg', '100mg/6.25mg', '500mg/125mg', '200mg/500mg', '50mg/500mg', '80mg/480mg',
  // Other
  'Other'
];

export const MEDICATION_MANUFACTURERS = [
  'Pfizer', 'GSK', 'Novartis', 'Roche', 'Merck & Co.', 'Sanofi', 'AstraZeneca', 'Johnson & Johnson', 
  'AbbVie', 'Bayer', 'Eli Lilly', 'Amgen', 'Gilead Sciences', 'Bristol-Myers Squibb', 'Novo Nordisk', 
  'Takeda', 'Boehringer Ingelheim', 'Teva', 'Mylan (Viatris)', 'Sandoz', 'Sun Pharma', 'Cipla', 
  'Dr. Reddy\'s', 'Lupin', 'Aurobindo', 'Intas', 'Torrent', 'Zydus Cadila', 'Abbott', 'Alkem',
  'Other'
];
