export interface PresentingComplaintCategory {
  category: string;
  complaints: readonly string[] | string[];
}

export interface PresentingComplaintOption {
  category: string;
  label: string;
  normalizedLabel: string;
}

export const PRESENTING_COMPLAINT_LIBRARY: readonly PresentingComplaintCategory[] = [
  {
    category: 'Cardiovascular',
    complaints: [
      'Chest pain / chest tightness / pressure',
      'Chest pain with exertion',
      'Palpitations / irregular heartbeat',
      'Shortness of breath on exertion',
      'Orthopnea (shortness of breath when lying flat)',
      'Paroxysmal nocturnal dyspnea (waking breathless at night)',
      'Peripheral edema / leg swelling',
      'Syncope / fainting / passed out',
      'Near-syncope / lightheadedness / presyncope',
      'Hypertension (elevated blood pressure)',
      'Hypotension / low blood pressure symptoms',
    ],
  },
  {
    category: 'Respiratory',
    complaints: [
      'Shortness of breath / dyspnea',
      'Cough (dry)',
      'Cough (productive/with sputum)',
      'Cough with hemoptysis (coughing blood)',
      'Wheezing',
      'Asthma exacerbation',
      'COPD exacerbation',
      'Sore throat / pharyngitis',
      'Hoarseness / voice changes',
      'Nasal congestion / rhinorrhea (runny nose)',
      'Epistaxis (nosebleed)',
      'Pleuritic chest pain (pain with breathing)',
      'Tachypnea (rapid breathing)',
    ],
  },
  {
    category: 'Gastrointestinal',
    complaints: [
      'Abdominal pain / stomach pain (general)',
      'Abdominal pain (right upper quadrant)',
      'Abdominal pain (right lower quadrant)',
      'Abdominal pain (left upper quadrant)',
      'Abdominal pain (left lower quadrant)',
      'Abdominal pain (epigastric/upper middle)',
      'Abdominal pain (diffuse/generalized)',
      'Nausea',
      'Vomiting / emesis',
      'Vomiting blood / hematemesis',
      'Diarrhea (acute)',
      'Diarrhea (bloody)',
      'Constipation',
      'Melena (black tarry stools)',
      'Hematochezia (bright red blood per rectum)',
      'Dysphagia / difficulty swallowing',
      'Odynophagia / painful swallowing',
      'Heartburn / reflux / indigestion',
      'Bloating / abdominal distension',
      'Change in bowel habits',
      'Rectal pain / tenesmus',
      'Jaundice / yellowing of skin/eyes',
      'Loss of appetite / anorexia',
    ],
  },
  {
    category: 'Neurological',
    complaints: [
      'Headache (general)',
      'Headache (thunderclap/sudden severe)',
      'Headache with aura (migraine)',
      'Headache (tension-type)',
      'Dizziness / vertigo (spinning sensation)',
      'Dizziness (lightheadedness/presyncope)',
      'Altered mental status / confusion',
      'Loss of consciousness / syncope',
      'Seizure / convulsion',
      'Witnessed seizure',
      'Focal weakness / hemiparesis (one-sided weakness)',
      'Numbness / tingling / paresthesia',
      'Difficulty speaking / aphasia / slurred speech',
      'Visual changes / vision loss',
      'Double vision / diplopia',
      'Ataxia / difficulty walking / unsteady gait',
      'Tremor',
      'Stiff neck / nuchal rigidity',
      'Memory problems / amnesia',
    ],
  },
  {
    category: 'Musculoskeletal / Trauma',
    complaints: [
      'Back pain (lower)',
      'Back pain (upper)',
      'Back pain (general)',
      'Neck pain',
      'Joint pain / arthralgia',
      'Joint swelling / effusion',
      'Muscle pain / myalgia',
      'Muscle weakness (generalized)',
      'Fall / mechanical fall',
      'Fall with injury',
      'Trauma (motor vehicle accident)',
      'Trauma (assault)',
      'Trauma (sports injury)',
      'Laceration / cut',
      'Abrasion / scrape',
      'Contusion / bruise',
      'Fracture / suspected fracture',
      'Dislocation / suspected dislocation',
      'Sprain / strain',
      'Head trauma / head injury',
      'Chest trauma',
      'Abdominal trauma',
      'Extremity pain (upper)',
      'Extremity pain (lower)',
      'Hip pain',
      'Shoulder pain',
      'Knee pain',
      'Ankle pain / foot pain',
      'Wrist pain / hand pain',
    ],
  },
  {
    category: 'Genitourinary / Gynecological',
    complaints: [
      'Dysuria / painful urination',
      'Urinary frequency',
      'Urinary urgency',
      'Urinary retention / inability to urinate',
      'Hematuria (blood in urine)',
      'Oliguria / decreased urine output',
      'Polyuria / increased urination',
      'Flank pain / renal colic (suspected kidney stone)',
      'Incontinence (urinary)',
      'Urinary tract infection symptoms',
      'Pelvic pain (female)',
      'Pelvic pain (male)',
      'Vaginal bleeding (abnormal)',
      'Vaginal bleeding (heavy)',
      'Vaginal discharge',
      'Vulvar pain / itching',
      'Testicular pain / scrotal pain',
      'Penile discharge',
      'Erectile dysfunction',
      'Amenorrhea (absent periods)',
      'Dysmenorrhea (painful periods)',
      'Pregnancy-related complaint',
      'Possible ectopic pregnancy symptoms',
      'Labor / contractions',
      'Rupture of membranes (water breaking)',
      'Postpartum complaint',
    ],
  },
  {
    category: 'Dermatological',
    complaints: [
      'Rash (generalized)',
      'Rash (localized)',
      'Rash with fever',
      'Itching / pruritus (generalized)',
      'Itching / pruritus (localized)',
      'Urticaria / hives',
      'Cellulitis / skin infection (suspected)',
      'Abscess / boil',
      'Wound infection',
      'Animal bite',
      'Human bite',
      'Insect bite / sting',
      'Burn (thermal)',
      'Burn (chemical)',
      'Burn (electrical)',
      'Sunburn',
      'Skin lesion / growth / mole changes',
      'Petechiae / purpura (non-blanching rash)',
      'Erythema / redness',
      'Blistering',
      'Hair loss / alopecia',
      'Nail changes / paronychia',
    ],
  },
  {
    category: 'Infectious / Constitutional',
    complaints: [
      'Fever / pyrexia',
      'Fever with rash',
      'Fever with chills / rigors',
      'Night sweats',
      'Fatigue / tiredness / malaise',
      'Weakness / generalized weakness',
      'Body aches / myalgias (generalized)',
      'Flu-like symptoms / viral syndrome',
      'Chills without fever',
      'Lymphadenopathy / swollen glands',
      'Suspected sepsis / septic shock',
      'Immunocompromised with fever',
    ],
  },
  {
    category: 'Psychiatric / Behavioral',
    complaints: [
      'Anxiety / panic attack',
      'Depression / low mood',
      'Suicidal ideation',
      'Homicidal ideation',
      'Psychosis / hallucinations / delusions',
      'Agitation / aggressive behavior',
      'Altered mental status / confusion',
      'Insomnia / difficulty sleeping',
      'Substance use / intoxication (alcohol)',
      'Substance use / intoxication (drugs)',
      'Withdrawal symptoms',
      'Eating disorder symptoms',
      'Self-harm / self-injury',
      'Behavioral change / personality change',
    ],
  },
  {
    category: 'Endocrine / Metabolic',
    complaints: [
      'Polydipsia (excessive thirst)',
      'Polyphagia (excessive hunger)',
      'Unexplained weight loss',
      'Unexplained weight gain',
      'Hypoglycemia symptoms / low blood sugar',
      'Hyperglycemia symptoms / high blood sugar',
      'Diabetic ketoacidosis symptoms (suspected)',
      'Thyroid-related symptoms (hyperthyroid)',
      'Thyroid-related symptoms (hypothyroid)',
      'Electrolyte imbalance symptoms',
      'Dehydration',
    ],
  },
  {
    category: 'Hematological / Oncological',
    complaints: [
      'Anemia symptoms / pallor',
      'Easy bruising / bleeding tendency',
      'Suspected deep vein thrombosis (DVT) - leg pain/swelling',
      'Suspected pulmonary embolism (PE) - sudden dyspnea/chest pain',
      'Lymphadenopathy (generalized)',
      'Suspected malignancy / cancer-related symptoms',
      'Neutropenic fever',
    ],
  },
  {
    category: 'Ophthalmological',
    complaints: [
      'Eye pain',
      'Red eye / conjunctivitis',
      'Vision loss (sudden)',
      'Vision loss (gradual)',
      'Blurred vision',
      'Double vision / diplopia',
      'Floaters / flashes of light',
      'Eye trauma / foreign body',
      'Chemical splash to eye',
      'Photophobia / light sensitivity',
      'Excessive tearing / epiphora',
      'Dry eyes',
      'Eyelid swelling / stye',
    ],
  },
  {
    category: 'Otolaryngological (ENT)',
    complaints: [
      'Ear pain / otalgia',
      'Ear discharge / otorrhea',
      'Hearing loss (sudden)',
      'Hearing loss (gradual)',
      'Tinnitus / ringing in ears',
      'Ear fullness / pressure',
      'Sore throat / odynophagia',
      'Difficulty swallowing / dysphagia',
      'Hoarseness / voice changes',
      'Neck mass / lump',
      'Dental pain / toothache',
      'Jaw pain / TMJ symptoms',
      'Oral lesion / ulcer',
    ],
  },
  {
    category: 'Pediatric Specific',
    complaints: [
      'Poor feeding / feeding difficulties (infant)',
      'Failure to thrive',
      'Irritability / inconsolable crying',
      'Colic',
      'Fever in infant (<3 months)',
      'Febrile seizure',
      'Developmental delay concerns',
      'Growth concerns',
      'School performance issues',
      'Behavioral concerns (child)',
    ],
  },
  {
    category: 'Geriatric Specific',
    complaints: [
      'Falls / recurrent falls',
      'Confusion / delirium (acute)',
      'Functional decline',
      'Memory loss / dementia concerns',
      'Polypharmacy concerns',
      'Urinary incontinence',
      'Gait abnormalities / mobility issues',
      'Failure to thrive (elderly)',
    ],
  },
  {
    category: 'Occupational / Environmental',
    complaints: [
      'Occupational exposure (chemical)',
      'Occupational exposure (biological)',
      'Smoke inhalation',
      'Drowning / near-drowning',
      'Heat exhaustion / heat stroke',
      'Hypothermia / cold exposure',
      'Altitude sickness',
      'Motion sickness',
      'Foreign body aspiration',
      'Foreign body ingestion',
      'Contact lens-related problem',
    ],
  },
  {
    category: 'Administrative / Non-clinical',
    complaints: [
      'Medication refill request',
      'Prescription renewal',
      'Work clearance / return to work',
      'School clearance / return to school',
      'Disability evaluation',
      'Pre-operative clearance',
      'Travel medicine consultation',
      'Immunization / vaccination',
      'Follow-up visit (routine)',
      'Follow-up visit (post-procedure)',
      'Second opinion requested',
      'Transfer from other facility',
      'Social admission / placement issues',
    ],
  },
] as const;

export function getPresentingComplaintOptions(
  library: readonly PresentingComplaintCategory[] = PRESENTING_COMPLAINT_LIBRARY
): PresentingComplaintOption[] {
  const seen = new Set<string>();
  const options: PresentingComplaintOption[] = [];

  for (const entry of library) {
    for (const complaint of entry.complaints) {
      const normalizedLabel = complaint.trim().toLowerCase();
      if (!normalizedLabel || seen.has(normalizedLabel)) {
        continue;
      }
      seen.add(normalizedLabel);
      options.push({
        category: entry.category,
        label: complaint,
        normalizedLabel,
      });
    }
  }

  return options;
}
