# Generated by Django 4.2.27 on 2025-12-19 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0004_remove_chief_complaint'),
        ('laboratory', '0002_labtest_rejected_at_labtest_rejected_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborder',
            name='consultation_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders', to='consultation.consultationsession'),
        ),
    ]
