# Generated by Django 4.2.27 on 2026-01-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0003_add_consultation_session_to_lab_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtemplate',
            name='turnaround_time',
            field=models.CharField(blank=True, help_text="Expected turnaround time (e.g., '30 min', '2 hours', '1 day')", max_length=50),
        ),
    ]
