# Generated by Django 4.2.27 on 2026-01-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0005_labtest_lab_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtemplate',
            name='category',
            field=models.CharField(choices=[('hematology', 'Hematology'), ('chemistry', 'Chemistry'), ('microbiology', 'Microbiology'), ('immunology', 'Immunology'), ('endocrinology', 'Endocrinology'), ('toxicology', 'Toxicology'), ('urinalysis', 'Urinalysis'), ('parasitology', 'Parasitology'), ('histopathology', 'Histopathology'), ('serology', 'Serology'), ('molecular', 'Molecular Biology'), ('cytology', 'Cytology')], default='chemistry', max_length=50),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='lab_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
    ]
