# Generated by Django 4.2.30 on 2026-05-04 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0015_remove_laborder_provisional_diagnosis'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='laborder',
            new_name='lab_orders_source__e9248c_idx',
            old_name='lab_orders_source__e9899c_idx',
        ),
    ]
