# Generated by Django 4.2.30 on 2026-05-18 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0019_labreferraldispatch_partner_address_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateFieldOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('sort_order', models.IntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_options', to='laboratory.labtemplate')),
            ],
            options={
                'verbose_name': 'Template field option',
                'verbose_name_plural': 'Template field options',
                'db_table': 'lab_template_field_options',
                'ordering': ['field_name', 'sort_order'],
                'unique_together': {('template', 'field_name', 'value')},
            },
        ),
    ]
