# Generated by Django 4.2.28 on 2026-05-20 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_systemconfig_clinic_default_processing_clinic'),
        ('laboratory', '0020_templatefieldoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborder',
            name='location_clinic',
            field=models.ForeignKey(blank=True, help_text='Clinic where this lab order was placed (requesting clinic)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders', to='organization.clinic'),
        ),
        migrations.AddField(
            model_name='laborder',
            name='processing_clinic',
            field=models.ForeignKey(blank=True, help_text="Clinic processing this lab order (defaults from requesting clinic's config, overridable)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders_processed', to='organization.clinic'),
        ),
    ]
