# Generated by Django 4.2.30 on 2026-05-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0021_laborder_location_clinic_laborder_processing_clinic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labtemplate',
            options={'ordering': ['sort_order', 'name']},
        ),
        migrations.AddField(
            model_name='labtemplate',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='Display order (lower = first)'),
        ),
    ]
