# Generated by Django 4.2.30 on 2026-06-20 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0023_labtest_status_verified_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='labtest',
            name='lab_tests_status_verified_idx',
        ),
    ]
