# Generated by Django 4.2.30 on 2026-08-07 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wards', '0012_rename_clinic_ward_location_clinic'),
        ('laboratory', '0024_remove_labtest_lab_tests_status_verified_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborder',
            name='admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders', to='wards.patientadmission'),
        ),
    ]
