# Generated by Django 4.2.30 on 2026-08-09 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_alter_department_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laboratory', '0025_laborder_admission'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='processing_clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_tests_processed', to='organization.clinic'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='routing_status',
            field=models.CharField(choices=[('pending_triage', 'Pending triage'), ('approved_local', 'Approved local'), ('sent_to_processing', 'Sent to processing'), ('referred_external', 'Referred external'), ('cancelled', 'Cancelled')], default='pending_triage', max_length=30),
        ),
        migrations.CreateModel(
            name='LabTestRoutingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_type', models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], max_length=20)),
                ('external_destination', models.CharField(blank=True, max_length=200)),
                ('reason', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_route_events_from', to='organization.clinic')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_events', to='laboratory.labtest')),
                ('to_clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_route_events_to', to='organization.clinic')),
            ],
        ),
        migrations.CreateModel(
            name='LabSampleBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('collection_clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.clinic')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_batches', to='laboratory.laborder')),
            ],
        ),
        migrations.AddField(
            model_name='labtest',
            name='sample_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='laboratory.labsamplebatch'),
        ),
    ]
