# Generated by Django 4.2.30 on 2026-08-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0026_lab_sample_batch_and_test_routing'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='labtestroutingevent',
            constraint=models.CheckConstraint(
                check=(
                    models.Q(destination_type='external')
                    | (models.Q(to_clinic__isnull=False) & models.Q(external_destination=''))
                ),
                name='lab_route_internal_requires_clinic',
            ),
        ),
        migrations.AddConstraint(
            model_name='labtestroutingevent',
            constraint=models.CheckConstraint(
                check=(
                    models.Q(destination_type='internal')
                    | (models.Q(to_clinic__isnull=True) & ~models.Q(external_destination=''))
                ),
                name='lab_route_external_requires_destination',
            ),
        ),
    ]
