# Generated by Django 4.2.30 on 2026-08-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0029_resolve_bode_lab_id_collisions'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='labtest',
            index=models.Index(fields=['status', 'processed_at'], name='lab_tests_status_3eefb5_idx'),
        ),
        migrations.AddIndex(
            model_name='labtest',
            index=models.Index(fields=['status', 'verified_at'], name='lab_tests_status_78a5d3_idx'),
        ),
    ]
