# Generated by Django 4.2.27 on 2026-01-17 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_alter_visit_admission_status'),
        ('consultation', '0006_add_presentation_complaint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('physiotherapy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='physioorder',
            options={'ordering': ['-ordered_at']},
        ),
        migrations.AddField(
            model_name='physioorder',
            name='chief_complaint',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='physioorder',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physioorder',
            name='consultation_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physio_orders', to='consultation.consultationsession'),
        ),
        migrations.AddField(
            model_name='physioorder',
            name='priority',
            field=models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('stat', 'STAT')], default='routine', max_length=20),
        ),
        migrations.AddField(
            model_name='physioorder',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physioorder',
            name='special_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='physioorder',
            name='treatment_goal',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='physioorder',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='physioorder',
            name='ordered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physio_orders_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='physioorder',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physio_orders', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='physioorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
