# Generated by Django 4.2.27 on 2026-01-17 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('physiotherapy', '0002_alter_physioorder_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='physioorder',
            name='sessions_completed',
            field=models.PositiveIntegerField(default=0, help_text='Number of sessions completed so far'),
        ),
        migrations.AddField(
            model_name='physioorder',
            name='total_sessions',
            field=models.PositiveIntegerField(default=1, help_text='Total number of sessions planned for this treatment'),
        ),
        migrations.AddField(
            model_name='physiosession',
            name='session_number',
            field=models.PositiveIntegerField(default=1, help_text='Session number in the treatment plan (1, 2, 3, etc.)'),
        ),
        migrations.AlterField(
            model_name='physiosession',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='physiotherapy.physioorder'),
        ),
        migrations.AlterField(
            model_name='physiosession',
            name='physiotherapist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physio_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='physiosession',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20),
        ),
    ]
