# Generated by Django 4.2.27 on 2026-01-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physiotherapy', '0003_physioorder_sessions_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physiosession',
            name='notes',
        ),
        migrations.AddField(
            model_name='physiosession',
            name='allergies',
            field=models.TextField(blank=True, help_text='Known allergies'),
        ),
        migrations.AddField(
            model_name='physiosession',
            name='assessment_findings',
            field=models.TextField(blank=True, help_text='Key assessment findings'),
        ),
        migrations.AddField(
            model_name='physiosession',
            name='assistive_devices',
            field=models.TextField(blank=True, help_text='Current assistive devices used'),
        ),
        migrations.AddField(
            model_name='physiosession',
            name='balance_coordination',
            field=models.TextField(blank=True, help_text='Balance and coordination assessment'),
        ),
        migrations.AddField(
            model_name='physiosession',
            name='clinical_reasoning',
            field=models.TextField(blank=True, help_text='Rationale for treatment approach'),
        ),
        migrations.AddField(
            model_name='physiosession',
            name='diagnosis_impression',
            field=models.TextField(blank=True, help_text='Clinical impression and working diagnosis'),
        ),
        migrations.AddField(
            model_name='physiosession',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Actual session duration in minutes', null=True),
        ),
        migrations.AddField(
            model_name='physiosession',
            name='equipment_used',
            field=models.JSONField(blank=True, default=list, help_text='Equipment/modalities used'),
        ),
        migrations.AddField(
            model_name='physiosession',
            name='exercises_prescribed',
            field=models.JSONField(blank=True, default=list, help_text='Home exercise program'),
        ),
        migrations.AddField(
            model_name='physiosession',
            name='follow_up_instructions',
            field=models.TextField(blank=True, help_text='Instructions for patient between sessions'),
        ),
        migrations.AddField(
            model_name='physiosession',
            name='functional_assessment',
            field=models.TextField(blank=True, help_text='Activities of daily living assessment'),
        ),
        migrations.AddField(
            model_name='physiosession',
            name='functional_goals',
            field=models.TextField(blank=True, help_text='Short-term and long-term functional goals'),
        ),
        migrations.AddField(
            model_name='physiosession',
            name='functional_limitations',
            field=models.TextField(blank=True, help_text='Identified functional limitations'),
        ),
        migrations.AddField(
            model_name='physiosession',
            name='medical_history',
            field=models.TextField(blank=True, help_text='Relevant medical history'),
        ),
        migrations.AddField(
            model_name='physiosession',
            name='medications',
            field=models.TextField(blank=True, help_text='Current medications'),
        ),
        migrations.AddField(
            model_name='physiosession',
            name='muscle_strength',
            field=models.TextField(blank=True, help_text='Manual muscle testing results'),
        ),
        migrations.AddField(
            model_name='physiosession',
            name='next_session_plan',
            field=models.TextField(blank=True, help_text='Plan for next session'),
        ),
        migrations.AddField(
            model_name='physiosession',
            name='pain_level_after',
            field=models.PositiveIntegerField(blank=True, help_text='Pain level 0-10 after treatment', null=True),
        ),
        migrations.AddField(
            model_name='physiosession',
            name='pain_level_before',
            field=models.PositiveIntegerField(blank=True, help_text='Pain level 0-10 before treatment', null=True),
        ),
        migrations.AddField(
            model_name='physiosession',
            name='patient_education',
            field=models.TextField(blank=True, help_text='Education provided to patient'),
        ),
        migrations.AddField(
            model_name='physiosession',
            name='posture_gait',
            field=models.TextField(blank=True, help_text='Posture and gait assessment'),
        ),
        migrations.AddField(
            model_name='physiosession',
            name='presenting_complaint',
            field=models.TextField(blank=True, help_text='Chief complaint and symptoms'),
        ),
        migrations.AddField(
            model_name='physiosession',
            name='previous_treatments',
            field=models.TextField(blank=True, help_text='Previous physiotherapy or related treatments'),
        ),
        migrations.AddField(
            model_name='physiosession',
            name='prognosis',
            field=models.TextField(blank=True, help_text='Expected recovery timeline and prognosis'),
        ),
        migrations.AddField(
            model_name='physiosession',
            name='progress_notes',
            field=models.TextField(blank=True, help_text='Progress compared to previous sessions'),
        ),
        migrations.AddField(
            model_name='physiosession',
            name='range_of_motion',
            field=models.TextField(blank=True, help_text='Joint ROM measurements'),
        ),
        migrations.AddField(
            model_name='physiosession',
            name='recommendations',
            field=models.JSONField(blank=True, default=list, help_text='Recommendations for other healthcare providers'),
        ),
        migrations.AddField(
            model_name='physiosession',
            name='reflexes',
            field=models.TextField(blank=True, help_text='Reflex testing results'),
        ),
        migrations.AddField(
            model_name='physiosession',
            name='sensation',
            field=models.TextField(blank=True, help_text='Sensory assessment findings'),
        ),
        migrations.AddField(
            model_name='physiosession',
            name='session_notes',
            field=models.TextField(blank=True, help_text='Additional session notes'),
        ),
        migrations.AddField(
            model_name='physiosession',
            name='social_history',
            field=models.TextField(blank=True, help_text='Occupation, lifestyle, support systems'),
        ),
        migrations.AddField(
            model_name='physiosession',
            name='special_tests',
            field=models.TextField(blank=True, help_text='Special orthopedic/neurological tests'),
        ),
        migrations.AddField(
            model_name='physiosession',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physiosession',
            name='surgical_history',
            field=models.TextField(blank=True, help_text='Previous surgeries'),
        ),
        migrations.AddField(
            model_name='physiosession',
            name='treatment_performed',
            field=models.TextField(blank=True, help_text='Treatments administered in this session'),
        ),
        migrations.AddField(
            model_name='physiosession',
            name='vital_signs',
            field=models.JSONField(blank=True, default=dict, help_text='Blood pressure, heart rate, temperature, etc.'),
        ),
    ]
