# Generated by Django 4.2.27 on 2026-01-17 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('physiotherapy', '0004_remove_physiosession_notes_physiosession_allergies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physiosession',
            name='vital_signs',
        ),
    ]
