# Generated by Django 4.2.27 on 2026-01-22 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('physiotherapy', '0005_remove_physiosession_vital_signs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physioorder',
            name='total_sessions',
        ),
    ]
