# Generated by Django 4.2.27 on 2026-01-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physiotherapy', '0006_remove_total_sessions'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='physiosession',
            constraint=models.UniqueConstraint(fields=('order', 'session_number'), name='unique_order_session_number'),
        ),
    ]
