# Generated by Django 4.2.27 on 2026-02-26 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_multi_clinic_support'),
        ('physiotherapy', '0007_add_unique_order_session_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='physioorder',
            name='visit',
            field=models.ForeignKey(blank=True, help_text='Visit this physio order is associated with (for multi-clinic visits)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='physio_orders', to='patients.visit'),
        ),
    ]
