# Generated by Django 4.2.27 on 2026-04-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physiotherapy', '0008_add_visit_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='physioorder',
            name='referral_source',
            field=models.CharField(choices=[('unspecified', 'Unspecified'), ('nursing', 'Nursing'), ('doctor', 'Doctor / clinic'), ('self', 'Self / walk-in'), ('other', 'Other')], db_index=True, default='unspecified', max_length=20),
        ),
    ]
