# Generated by Django 4.2.30 on 2026-05-03 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('physiotherapy', '0009_observation_procedures_referral'),
    ]

    operations = [
    ]
