# Generated by Django 4.2.30 on 2026-05-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physiotherapy', '0011_alter_physiosession_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physioorder',
            name='chief_complaint',
        ),
        migrations.RemoveField(
            model_name='physioorder',
            name='treatment_goal',
        ),
        migrations.AddField(
            model_name='physioorder',
            name='drug_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='physioorder',
            name='history_clinical_findings',
            field=models.TextField(blank=True),
        ),
    ]
