# Generated by Django 4.2.28 on 2026-05-20 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_systemconfig_clinic_default_processing_clinic'),
        ('physiotherapy', '0012_remove_physioorder_chief_complaint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='physioorder',
            name='location_clinic',
            field=models.ForeignKey(blank=True, help_text='Clinic where this physiotherapy order was created', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physio_orders', to='organization.clinic'),
        ),
    ]
