# Generated by Django 4.2.30 on 2026-06-20 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('physiotherapy', '0014_physiosession_status_completed_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='physiosession',
            name='physio_sess_status_completed_idx',
        ),
    ]
