# Generated by Django 4.2.30 on 2026-08-07 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wards', '0012_rename_clinic_ward_location_clinic'),
        ('physiotherapy', '0015_remove_physiosession_physio_sess_status_completed_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='physioorder',
            name='admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physio_orders', to='wards.patientadmission'),
        ),
    ]
