"""
Seed data: employee names with titles for staging/demo.
Format: Title, FirstName, [Middle], Surname.
Gender is inferred from title: Mr/Mallam/Alhaji/Sir->male; Mrs/Miss/Ms/Hajia/Lady->female; others random.
"""

EMPLOYEE_SEED_NAMES = [
    # Male titles: Mr, Mallam, Alhaji, Sir
    {"title": "Mr", "first_name": "Jonathan", "middle_name": "A.", "surname": "Okoro"},
    {"title": "Mr", "first_name": "Chinedu", "middle_name": "K.", "surname": "Nwosu"},
    {"title": "Mr", "first_name": "Ibrahim", "middle_name": "", "surname": "Musa"},
    {"title": "Mr", "first_name": "Adebayo", "middle_name": "O.", "surname": "Adeyemi"},
    {"title": "Mr", "first_name": "Emeka", "middle_name": "C.", "surname": "Nnamdi"},
    {"title": "Mallam", "first_name": "Usman", "middle_name": "B.", "surname": "Suleiman"},
    {"title": "Mallam", "first_name": "Yusuf", "middle_name": "", "surname": "Abubakar"},
    {"title": "Mallam", "first_name": "Ahmad", "middle_name": "I.", "surname": "Ibrahim"},
    {"title": "Alhaji", "first_name": "Bello", "middle_name": "M.", "surname": "Abdullahi"},
    {"title": "Alhaji", "first_name": "Sani", "middle_name": "", "surname": "Mohammed"},
    {"title": "Alhaji", "first_name": "Garba", "middle_name": "U.", "surname": "Yakubu"},
    {"title": "Sir", "first_name": "Patrick", "middle_name": "E.", "surname": "Eze"},
    {"title": "Sir", "first_name": "James", "middle_name": "O.", "surname": "Obi"},
    # Female titles: Mrs, Miss, Ms, Hajia, Lady
    {"title": "Mrs", "first_name": "Jane", "middle_name": "N.", "surname": "Adebayo"},
    {"title": "Mrs", "first_name": "Ngozi", "middle_name": "C.", "surname": "Eze"},
    {"title": "Mrs", "first_name": "Amina", "middle_name": "", "surname": "Hassan"},
    {"title": "Mrs", "first_name": "Funke", "middle_name": "O.", "surname": "Akinyemi"},
    {"title": "Mrs", "first_name": "Chioma", "middle_name": "I.", "surname": "Nwankwo"},
    {"title": "Miss", "first_name": "Blessing", "middle_name": "A.", "surname": "Okafor"},
    {"title": "Miss", "first_name": "Fatima", "middle_name": "", "surname": "Bello"},
    {"title": "Miss", "first_name": "Amaka", "middle_name": "C.", "surname": "Okeke"},
    {"title": "Miss", "first_name": "Zainab", "middle_name": "M.", "surname": "Sani"},
    {"title": "Ms", "first_name": "Oluwaseun", "middle_name": "F.", "surname": "Adewale"},
    {"title": "Ms", "first_name": "Halima", "middle_name": "", "surname": "Umar"},
    {"title": "Hajia", "first_name": "Aisha", "middle_name": "B.", "surname": "Yusuf"},
    {"title": "Hajia", "first_name": "Maimuna", "middle_name": "", "surname": "Ibrahim"},
    {"title": "Hajia", "first_name": "Habiba", "middle_name": "A.", "surname": "Suleiman"},
    {"title": "Lady", "first_name": "Victoria", "middle_name": "E.", "surname": "Okoli"},
    {"title": "Lady", "first_name": "Adaeze", "middle_name": "N.", "surname": "Onwuka"},
    # Professional titles (gender inferred at random in command): Dr, Engr, Prof, Chief, Arch, Pharm, etc.
    {"title": "Dr", "first_name": "John", "middle_name": "A.", "surname": "Okoro"},
    {"title": "Dr", "first_name": "Maryam", "middle_name": "S.", "surname": "Abubakar"},
    {"title": "Dr", "first_name": "Obinna", "middle_name": "C.", "surname": "Nwosu"},
    {"title": "Dr", "first_name": "Aisha", "middle_name": "", "surname": "Ibrahim"},
    {"title": "Engr", "first_name": "Segun", "middle_name": "O.", "surname": "Adeyinka"},
    {"title": "Engr", "first_name": "Ifeanyi", "middle_name": "K.", "surname": "Uche"},
    {"title": "Engr", "first_name": "Tunde", "middle_name": "", "surname": "Ogunleye"},
    {"title": "Prof", "first_name": "Adewale", "middle_name": "B.", "surname": "Ogunlesi"},
    {"title": "Prof", "first_name": "Chinwe", "middle_name": "N.", "surname": "Okonkwo"},
    {"title": "Chief", "first_name": "Olumide", "middle_name": "A.", "surname": "Akinola"},
    {"title": "Chief", "first_name": "Nneka", "middle_name": "E.", "surname": "Nnamdi"},
    {"title": "Arch", "first_name": "Kunle", "middle_name": "O.", "surname": "Oladipo"},
    {"title": "Arch", "first_name": "Folake", "middle_name": "M.", "surname": "Adebayo"},
    {"title": "Barr", "first_name": "Obi", "middle_name": "C.", "surname": "Nwankwo"},
    {"title": "Barr", "first_name": "Amaka", "middle_name": "I.", "surname": "Ezeilo"},
    {"title": "Pharm", "first_name": "Chika", "middle_name": "N.", "surname": "Nwosu"},
    {"title": "Pharm", "first_name": "Zainab", "middle_name": "", "surname": "Yusuf"},
    {"title": "Rev", "first_name": "Daniel", "middle_name": "E.", "surname": "Obi"},
    {"title": "Pastor", "first_name": "Grace", "middle_name": "A.", "surname": "Eze"},
    {"title": "Hon", "first_name": "Yusuf", "middle_name": "B.", "surname": "Garba"},
    {"title": "Hon", "first_name": "Stella", "middle_name": "O.", "surname": "Okonkwo"},
    {"title": "Surv", "first_name": "Temitope", "middle_name": "A.", "surname": "Adeleke"},
    {"title": "Elder", "first_name": "Samuel", "middle_name": "O.", "surname": "Okafor"},
    {"title": "Elder", "first_name": "Esther", "middle_name": "N.", "surname": "Nwosu"},
    {"title": "Comrade", "first_name": "Ikechukwu", "middle_name": "C.", "surname": "Nnamdi"},
    {"title": "QS", "first_name": "Oluwaseun", "middle_name": "F.", "surname": "Akinade"},
    {"title": "ESV", "first_name": "Ademola", "middle_name": "B.", "surname": "Ogunbiyi"},
    {"title": "HRM", "first_name": "Ezenwa", "middle_name": "I.", "surname": "Okoli"},
    # More mix for a longer list
    {"title": "Mr", "first_name": "Oluwole", "middle_name": "A.", "surname": "Ajayi"},
    {"title": "Mr", "first_name": "Tope", "middle_name": "", "surname": "Ogunyemi"},
    {"title": "Mr", "first_name": "Chukwuma", "middle_name": "E.", "surname": "Okoli"},
    {"title": "Mr", "first_name": "Abdullahi", "middle_name": "M.", "surname": "Sani"},
    {"title": "Mr", "first_name": "Kolawole", "middle_name": "O.", "surname": "Adeyemo"},
    {"title": "Mrs", "first_name": "Folake", "middle_name": "A.", "surname": "Ogunlesi"},
    {"title": "Mrs", "first_name": "Rukayat", "middle_name": "", "surname": "Mohammed"},
    {"title": "Mrs", "first_name": "Nkechi", "middle_name": "O.", "surname": "Nwosu"},
    {"title": "Mrs", "first_name": "Bola", "middle_name": "F.", "surname": "Adeyemi"},
    {"title": "Miss", "first_name": "Chidinma", "middle_name": "I.", "surname": "Okeke"},
    {"title": "Miss", "first_name": "Amina", "middle_name": "B.", "surname": "Umar"},
    {"title": "Dr", "first_name": "Chibuzo", "middle_name": "N.", "surname": "Okeke"},
    {"title": "Dr", "first_name": "Hadiza", "middle_name": "", "surname": "Suleiman"},
    {"title": "Engr", "first_name": "Abubakar", "middle_name": "Y.", "surname": "Garba"},
    {"title": "Engr", "first_name": "Ngozi", "middle_name": "C.", "surname": "Obi"},
    {"title": "Prof", "first_name": "Iyabo", "middle_name": "A.", "surname": "Adeyemi"},
    {"title": "Chief", "first_name": "Adeleke", "middle_name": "O.", "surname": "Ogunleye"},
    {"title": "Alhaji", "first_name": "Ibrahim", "middle_name": "A.", "surname": "Abubakar"},
    {"title": "Hajia", "first_name": "Zainab", "middle_name": "M.", "surname": "Bello"},
    {"title": "Mallam", "first_name": "Suleiman", "middle_name": "", "surname": "Yusuf"},
    {"title": "Mr", "first_name": "Chukwuemeka", "middle_name": "I.", "surname": "Nnamdi"},
    {"title": "Mr", "first_name": "Babatunde", "middle_name": "A.", "surname": "Oyedepo"},
    {"title": "Mr", "first_name": "Mohammed", "middle_name": "B.", "surname": "Ibrahim"},
    {"title": "Mrs", "first_name": "Abimbola", "middle_name": "O.", "surname": "Adesanya"},
    {"title": "Mrs", "first_name": "Halima", "middle_name": "A.", "surname": "Sani"},
    {"title": "Miss", "first_name": "Ogechi", "middle_name": "N.", "surname": "Nwankwo"},
    {"title": "Ms", "first_name": "Titilayo", "middle_name": "F.", "surname": "Adeyinka"},
    {"title": "Dr", "first_name": "Adeola", "middle_name": "B.", "surname": "Ogunbiyi"},
    {"title": "Engr", "first_name": "Chukwudi", "middle_name": "E.", "surname": "Okonkwo"},
    {"title": "Prof", "first_name": "Olabode", "middle_name": "A.", "surname": "Akinola"},
    {"title": "Chief", "first_name": "Ngozi", "middle_name": "C.", "surname": "Eze"},
    {"title": "Barr", "first_name": "Adewale", "middle_name": "O.", "surname": "Adekoya"},
    {"title": "Pharm", "first_name": "Chiamaka", "middle_name": "I.", "surname": "Okoli"},
    {"title": "Rev", "first_name": "Emmanuel", "middle_name": "C.", "surname": "Nwankwo"},
    {"title": "Hon", "first_name": "Amina", "middle_name": "", "surname": "Hassan"},
    {"title": "Mr", "first_name": "Kayode", "middle_name": "O.", "surname": "Akinola"},
    {"title": "Mr", "first_name": "Suleiman", "middle_name": "A.", "surname": "Abubakar"},
    {"title": "Mrs", "first_name": "Chiamaka", "middle_name": "N.", "surname": "Nnamdi"},
    {"title": "Mrs", "first_name": "Bilkisu", "middle_name": "", "surname": "Yusuf"},
    {"title": "Miss", "first_name": "Chiamaka", "middle_name": "A.", "surname": "Okeke"},
    {"title": "Dr", "first_name": "Adaeze", "middle_name": "O.", "surname": "Onwuka"},
    {"title": "Engr", "first_name": "Oladapo", "middle_name": "B.", "surname": "Adeleke"},
    {"title": "Alhaji", "first_name": "Abubakar", "middle_name": "M.", "surname": "Sani"},
    {"title": "Hajia", "first_name": "Safiya", "middle_name": "I.", "surname": "Ibrahim"},
    {"title": "Mallam", "first_name": "Musa", "middle_name": "B.", "surname": "Mohammed"},
    {"title": "Lady", "first_name": "Onyinye", "middle_name": "C.", "surname": "Nwosu"},
    {"title": "Sir", "first_name": "Chukwuemeka", "middle_name": "E.", "surname": "Obi"},
    {"title": "Mr", "first_name": "Femi", "middle_name": "A.", "surname": "Ogunleye"},
    {"title": "Mr", "first_name": "Yakubu", "middle_name": "", "surname": "Garba"},
    {"title": "Mrs", "first_name": "Omolara", "middle_name": "F.", "surname": "Adeyemi"},
    {"title": "Mrs", "first_name": "Aisha", "middle_name": "B.", "surname": "Abubakar"},
    {"title": "Miss", "first_name": "Adaeze", "middle_name": "N.", "surname": "Okoli"},
    {"title": "Dr", "first_name": "Ibrahim", "middle_name": "M.", "surname": "Suleiman"},
    {"title": "Prof", "first_name": "Chinwe", "middle_name": "O.", "surname": "Eze"},
    {"title": "Chief", "first_name": "Adebayo", "middle_name": "A.", "surname": "Akinola"},
    {"title": "Arch", "first_name": "Oluwaseun", "middle_name": "B.", "surname": "Oladipo"},
    {"title": "Barr", "first_name": "Nneamaka", "middle_name": "I.", "surname": "Nwankwo"},
    {"title": "Pharm", "first_name": "Amina", "middle_name": "", "surname": "Sani"},
    {"title": "Mr", "first_name": "Olawale", "middle_name": "O.", "surname": "Adeyinka"},
    {"title": "Mr", "first_name": "Chibueze", "middle_name": "C.", "surname": "Okoli"},
    {"title": "Mr", "first_name": "Ishaq", "middle_name": "A.", "surname": "Ibrahim"},
    {"title": "Mrs", "first_name": "Nkeiruka", "middle_name": "E.", "surname": "Nnamdi"},
    {"title": "Mrs", "first_name": "Khadija", "middle_name": "M.", "surname": "Mohammed"},
    {"title": "Miss", "first_name": "Chidinma", "middle_name": "A.", "surname": "Eze"},
    {"title": "Ms", "first_name": "Oluwatoyin", "middle_name": "F.", "surname": "Akinade"},
    {"title": "Dr", "first_name": "Obinna", "middle_name": "K.", "surname": "Nwosu"},
    {"title": "Engr", "first_name": "Temitope", "middle_name": "A.", "surname": "Ogunbiyi"},
    {"title": "Prof", "first_name": "Adewale", "middle_name": "B.", "surname": "Ogunlesi"},
    {"title": "Alhaji", "first_name": "Garba", "middle_name": "U.", "surname": "Yakubu"},
    {"title": "Hajia", "first_name": "Maimuna", "middle_name": "A.", "surname": "Suleiman"},
    {"title": "Mallam", "first_name": "Ahmad", "middle_name": "I.", "surname": "Abubakar"},
    {"title": "Mr", "first_name": "Adewale", "middle_name": "O.", "surname": "Adekoya"},
    {"title": "Mr", "first_name": "Chukwuma", "middle_name": "I.", "surname": "Okonkwo"},
    {"title": "Mrs", "first_name": "Ijeoma", "middle_name": "C.", "surname": "Nwankwo"},
    {"title": "Mrs", "first_name": "Habiba", "middle_name": "", "surname": "Yusuf"},
    {"title": "Miss", "first_name": "Ogechi", "middle_name": "N.", "surname": "Okeke"},
    {"title": "Dr", "first_name": "Chinwe", "middle_name": "O.", "surname": "Okonkwo"},
    {"title": "Engr", "first_name": "Kunle", "middle_name": "A.", "surname": "Adeleke"},
    {"title": "Chief", "first_name": "Olumide", "middle_name": "B.", "surname": "Ogunleye"},
    {"title": "Hon", "first_name": "Adewale", "middle_name": "O.", "surname": "Adeyemi"},
    {"title": "Elder", "first_name": "Grace", "middle_name": "A.", "surname": "Nwosu"},
]

# Model TITLE_CHOICES (value) for mapping. Unknown titles map to ''.
TITLE_TO_MODEL = {
    "mr": "mr", "mrs": "mrs", "ms": "ms", "miss": "miss",
    "dr": "dr", "chief": "chief", "engr": "engr", "prof": "prof",
    "alhaji": "alhaji", "hajia": "hajia", "mallam": "mallam", "lady": "lady",
    "sir": "mr", "arch": "engr", "pharm": "dr", "barr": "", "rev": "",
    "pastor": "", "hon": "", "surv": "", "elder": "", "comrade": "",
    "esv": "", "qs": "", "hrm": "",
}

# Gender inference: male, female, or None (command will randomly assign)
TITLE_TO_GENDER = {
    "mr": "male", "mallam": "male", "alhaji": "male", "sir": "male",
    "mrs": "female", "miss": "female", "ms": "female", "hajia": "female", "lady": "female",
    # dr, engr, prof, chief, arch, pharm, barr, rev, pastor, hon, surv, elder, comrade, esv, qs, hrm -> None
}
