"use client";

import { useState, useMemo, useEffect } from 'react';
import { DashboardLayout } from '@/components/DashboardLayout';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { Label } from '@/components/ui/label';
import { Separator } from '@/components/ui/separator';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { toast } from "sonner";
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { patientService, type Patient as ApiPatient } from '@/lib/services';
import { useAuthRedirect } from '@/hooks/use-auth-redirect';
import { isAuthenticationError } from '@/lib/auth-errors';
import { 
  Search, Filter, Users, Phone, Mail, Eye, 
  UserPlus, Calendar, FileText, Edit, X, MapPin, Loader2,
  Activity, UserCheck, AlertTriangle, Droplets, User, Briefcase, Camera, Upload, Trash2
} from 'lucide-react';
import { StandardPagination } from '@/components/StandardPagination';

// Constants for form fields
const titles = ['Mr', 'Mrs', 'Ms', 'Dr', 'Chief', 'Engr', 'Prof', 'Alhaji', 'Hajia'];
const maritalStatuses = ['Single', 'Married', 'Divorced', 'Widowed'];
const NOK_RELATIONSHIPS = ['Spouse', 'Parent', 'Child', 'Sibling', 'Relative', 'Friend', 'Other'];

// NPA Divisions
const divisions = [
  "Engineering", "Land & Asset Administration", "Marine and Operations", "Monitoring & Regulation",
  "HSE", "Security", "Port Managers", "HR", "Medical", "Admin", "Finance", "Superannuation & Investment",
  "Enterprise Risk Management", "Procurement", "Corporate & Strategic Communications",
  "Corporate & Strategic Planning", "Legal Services", "Audit", "ICT", "PPP",
  "Abuja Liaison Office", "Servicom", "Overseas Liaison Office", "MD's Office"
];

const NIGERIA_STATES = [
  'Abia', 'Adamawa', 'Akwa Ibom', 'Anambra', 'Bauchi', 'Bayelsa', 'Benue', 'Borno',
  'Cross River', 'Delta', 'Ebonyi', 'Edo', 'Ekiti', 'Enugu', 'FCT', 'Gombe', 'Imo',
  'Jigawa', 'Kaduna', 'Kano', 'Katsina', 'Kebbi', 'Kogi', 'Kwara', 'Lagos', 'Nasarawa',
  'Niger', 'Ogun', 'Ondo', 'Osun', 'Oyo', 'Plateau', 'Rivers', 'Sokoto', 'Taraba',
  'Yobe', 'Zamfara'
];

// Patient type
type Patient = {
  id: string;
  name: string;
  category: string;
  personalNumber?: string;
  employeeType?: string;
  division?: string;
  age: number;
  gender: string;
  dob: string;
  phone: string;
  email: string;
  bloodGroup: string;
  address: string;
  emergencyContact: string;
  lastVisit: string;
  totalVisits: number;
  location: string;
  photoUrl: string;
  registeredAt: string;
  primaryPatient?: string;
  relationship?: string;
  nonNpaType?: string;
};

// Transform backend patient to frontend format
const transformPatient = (apiPatient: ApiPatient): Patient => {
  const categoryMap: Record<string, string> = {
    'employee': 'Employee',
    'retiree': 'Retiree',
    'dependent': 'Dependent',
    'nonnpa': 'NonNPA',
  };
  
  // Use patient_id if available, otherwise fallback to numeric ID as string
  // patient_id should always be generated by backend, but handle edge cases
  const patientId = apiPatient.patient_id || String(apiPatient.id);
  
  return {
    id: patientId,
    name: apiPatient.full_name || `${apiPatient.first_name} ${apiPatient.surname}`,
    category: categoryMap[apiPatient.category] || apiPatient.category,
    personalNumber: apiPatient.personal_number || '',
    employeeType: apiPatient.employee_type || '',
    division: apiPatient.division || '',
    age: apiPatient.age || 0,
    gender: apiPatient.gender === 'male' ? 'Male' : 'Female',
    dob: apiPatient.date_of_birth || '',
    phone: apiPatient.phone || '',
    email: apiPatient.email || '',
    bloodGroup: apiPatient.blood_group || '',
    address: apiPatient.residential_address || apiPatient.permanent_address || '',
    emergencyContact: apiPatient.nok_first_name ? `${apiPatient.nok_first_name} ${apiPatient.nok_middle_name || ''} - ${apiPatient.nok_phone || ''}`.trim() : '',
    lastVisit: '', // Will be populated if visit data is available
    totalVisits: 0, // Will be populated if visit data is available
    location: apiPatient.location || '',
    photoUrl: apiPatient.photo || '',
    registeredAt: apiPatient.created_at?.split('T')[0] || '',
    primaryPatient: '', // Will be populated if principal_staff data is available
    relationship: apiPatient.nok_relationship || '',
    nonNpaType: apiPatient.nonnpa_type || '',
  };
};

// Helper component for patient avatar with photo support
const PatientAvatar = ({ patient, size = 'md' }: { patient: Patient, size?: 'sm' | 'md' | 'lg' }) => {
  const sizeClasses = {
    sm: 'w-8 h-8 text-xs',
    md: 'w-10 h-10 text-sm',
    lg: 'w-16 h-16 text-xl'
  };
  
  const initials = patient.name.split(' ').map(n => n[0]).join('');
  
  if (patient.photoUrl) {
    return (
      <div className={`${sizeClasses[size]} rounded-full overflow-hidden bg-muted`}>
        <img 
          src={patient.photoUrl} 
          alt={patient.name}
          className="w-full h-full object-cover"
          onError={(e) => {
            // Fallback to initials if image fails to load
            const target = e.target as HTMLImageElement;
            target.style.display = 'none';
            target.parentElement!.innerHTML = `<div class="${sizeClasses[size]} rounded-full bg-gradient-to-br from-teal-500 to-cyan-500 flex items-center justify-center text-white font-medium">${initials}</div>`;
          }}
        />
      </div>
    );
  }
  
  return (
    <div className={`${sizeClasses[size]} rounded-full bg-gradient-to-br from-teal-500 to-cyan-500 flex items-center justify-center text-white font-medium`}>
      {initials}
    </div>
  );
};

const locations = [
  "All Locations", "Headquarters", "Bode Thomas Clinic", "Lagos Port Complex", "Tincan Island Port Complex",
  "Rivers Port Complex", "Onne Port Complex", "Delta Port Complex", "Calabar Port", "Lekki Deep Sea Port"
];

const categories = ["All Categories", "Employee", "Retiree", "Dependent", "NonNPA"];

export default function PatientsListPage() {
  const router = useRouter();
  const [patients, setPatients] = useState<Patient[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [authError, setAuthError] = useState<unknown | null>(null);
  
  // Handle authentication redirects
  useAuthRedirect(authError);
  const [searchQuery, setSearchQuery] = useState('');
  const [genderFilter, setGenderFilter] = useState('all');
  const [categoryFilter, setCategoryFilter] = useState('all');
  const [locationFilter, setLocationFilter] = useState('all');
  const [isFilterDialogOpen, setIsFilterDialogOpen] = useState(false);
  const [selectedPatient, setSelectedPatient] = useState<Patient | null>(null);
  
  // Modal states
  const [isViewModalOpen, setIsViewModalOpen] = useState(false);
  const [isEditModalOpen, setIsEditModalOpen] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  
  // Edit form state
  const [editForm, setEditForm] = useState({
    title: '',
    firstName: '',
    lastName: '',
    middleName: '',
    dateOfBirth: '',
    maritalStatus: '',
    phone: '',
    email: '',
    residentialAddress: '',
    permanentAddress: '',
    stateOfResidence: '',
    stateOfOrigin: '',
    lga: '',
    bloodGroup: '',
    genotype: '',
    location: '',
    division: '',
    employeeType: '',
    nokFirstName: '',
    nokMiddleName: '',
    nokRelationship: '',
    nokPhone: '',
    nokAddress: '',
  });
  const [editFormLoading, setEditFormLoading] = useState(false);
  const [photoFile, setPhotoFile] = useState<File | null>(null);
  const [photoPreview, setPhotoPreview] = useState<string | null>(null);
  
  // Advanced filters
  const [ageRange, setAgeRange] = useState({ min: '', max: '' });
  const [dateRange, setDateRange] = useState({ from: '', to: '' });
  
  // Pagination state
  const [currentPage, setCurrentPage] = useState(1);
  const [itemsPerPage, setItemsPerPage] = useState(10);

  const filteredPatients = useMemo(() => patients.filter(patient => {
    const matchesSearch = patient.name.toLowerCase().includes(searchQuery.toLowerCase()) || 
      patient.id.toLowerCase().includes(searchQuery.toLowerCase()) || 
      patient.phone.includes(searchQuery);
    const matchesGender = genderFilter === 'all' || patient.gender.toLowerCase() === genderFilter.toLowerCase();
    const matchesCategory = categoryFilter === 'all' || patient.category.toLowerCase() === categoryFilter.toLowerCase();
    const matchesLocation = locationFilter === 'all' || patient.location === locationFilter;
    const matchesAge = (!ageRange.min || patient.age >= parseInt(ageRange.min)) && (!ageRange.max || patient.age <= parseInt(ageRange.max));
    return matchesSearch && matchesGender && matchesCategory && matchesLocation && matchesAge;
  }), [patients, searchQuery, genderFilter, categoryFilter, locationFilter, ageRange]);

  // Paginated patients
  const paginatedPatients = useMemo(() => {
    const startIndex = (currentPage - 1) * itemsPerPage;
    return filteredPatients.slice(startIndex, startIndex + itemsPerPage);
  }, [filteredPatients, currentPage, itemsPerPage]);

  // Load patients from API
  useEffect(() => {
    loadPatients();
  }, [currentPage, itemsPerPage]);

  // Reset to page 1 when filters change
  useEffect(() => {
    setCurrentPage(1);
  }, [searchQuery, genderFilter, categoryFilter, locationFilter, ageRange]);

  const loadPatients = async () => {
    try {
      setLoading(true);
      setError(null);
      const params: any = {
        page: currentPage,
        page_size: itemsPerPage,
      };
      if (categoryFilter !== 'all') {
        const categoryMap: Record<string, string> = {
          'Employee': 'employee',
          'Retiree': 'retiree',
          'Dependent': 'dependent',
          'NonNPA': 'nonnpa',
        };
        params.category = categoryMap[categoryFilter] || categoryFilter.toLowerCase();
      }
      if (genderFilter !== 'all') {
        params.gender = genderFilter;
      }
      if (searchQuery) {
        params.search = searchQuery;
      }
      
      const response = await patientService.getPatients(params);
      
      // Transform patients (visit data will be fetched on-demand when viewing patient details)
      const transformedPatients = response.results.map(transformPatient);
      
      // Optionally fetch visit counts and principal staff names in parallel (but limit to avoid slowdown)
      // For better performance, we'll only fetch these when opening the view modal
      // For now, we'll fetch principal staff names for dependents as it's important info
      await Promise.allSettled(
        transformedPatients.map(async (patient, index) => {
          const apiPatient = response.results[index];
          
          // Fetch principal staff name for dependents only
          if (apiPatient.category === 'dependent' && apiPatient.principal_staff) {
            try {
              const principal = await patientService.getPatient(apiPatient.principal_staff);
              patient.primaryPatient = principal.full_name || `${principal.first_name} ${principal.surname}`;
            } catch (err) {
              // Silently fail - principal staff data is optional
              console.debug('Could not fetch principal staff for dependent', apiPatient.id);
            }
          }
        })
      );
      
      setPatients(transformedPatients);
      setAuthError(null); // Clear any previous auth errors
    } catch (err: any) {
      // Handle authentication errors separately
      if (isAuthenticationError(err)) {
        setAuthError(err);
        setError('Authentication required. Redirecting to login...');
        // Don't show toast for auth errors as we're redirecting
        return;
      }
      
      setError(err.message || 'Failed to load patients');
      toast.error('Failed to load patients. Please try again.');
      console.error('Error loading patients:', err);
      setAuthError(null);
    } finally {
      setLoading(false);
    }
  };

  const stats = useMemo(() => [
    { label: 'Total Patients', value: patients.length, icon: Users, color: 'text-blue-500', bg: 'bg-blue-500/10' },
    { label: 'Employees', value: patients.filter(p => p.category === 'Employee').length, icon: UserCheck, color: 'text-teal-500', bg: 'bg-teal-500/10' },
    { label: 'Retirees', value: patients.filter(p => p.category === 'Retiree').length, icon: Activity, color: 'text-amber-500', bg: 'bg-amber-500/10' },
    { label: 'Dependents', value: patients.filter(p => p.category === 'Dependent').length, icon: Users, color: 'text-violet-500', bg: 'bg-violet-500/10' },
  ], [patients]);

  const openViewModal = async (patient: Patient) => {
    setSelectedPatient(patient);
    setIsViewModalOpen(true);
    
    // Fetch visit data when opening the modal (lazy loading)
    if (patient.totalVisits === 0) {
      try {
        // Look up patient by patient_id to get numeric ID for API calls
        let numericId: number;
        const patientIdStr = patient.id.trim();
        
        // Check if it's a numeric ID
        const parsedId = parseInt(patientIdStr, 10);
        if (!isNaN(parsedId) && parsedId > 0) {
          numericId = parsedId;
        } else {
          // It's a string patient_id (like "E-A2962") - search for it
          const searchResult = await patientService.getPatients({ search: patientIdStr });
          const matchedPatient = searchResult.results.find(
            p => p.patient_id === patientIdStr || p.patient_id.toUpperCase() === patientIdStr.toUpperCase()
          );
          if (!matchedPatient) {
            return; // Could not find patient, skip fetching visits
          }
          numericId = matchedPatient.id;
        }
        
        // Fetch visits for this patient
        const visits = await patientService.getPatientVisits(numericId);
        const updatedPatient = { ...patient };
        updatedPatient.totalVisits = visits.length;
        if (visits.length > 0) {
          const sortedVisits = [...visits].sort((a, b) => 
            new Date(b.date).getTime() - new Date(a.date).getTime()
          );
          updatedPatient.lastVisit = sortedVisits[0].date;
        }
        setSelectedPatient(updatedPatient);
        // Also update in the main list
        setPatients(prev => prev.map(p => p.id === patient.id ? updatedPatient : p));
      } catch (err) {
        console.debug('Could not fetch visit data for patient', patient.id, err);
      }
    }
  };

  const openEditModal = async (patient: Patient) => {
    setSelectedPatient(patient);
    setIsEditModalOpen(true);
    setEditFormLoading(true);
    
    try {
      // Look up patient by patient_id to get numeric ID and full data
      const patientIdStr = patient.id.trim();
      let numericId: number;
      let apiPatient: ApiPatient;
      
      // Check if it's a numeric ID
      const parsedId = parseInt(patientIdStr, 10);
      if (!isNaN(parsedId) && parsedId > 0) {
        numericId = parsedId;
        apiPatient = await patientService.getPatient(numericId);
      } else {
        // It's a string patient_id (like "E-A2962") - search for it
        const searchResult = await patientService.getPatients({ search: patientIdStr });
        const matchedPatient = searchResult.results.find(
          p => p.patient_id === patientIdStr || p.patient_id.toUpperCase() === patientIdStr.toUpperCase()
        );
        if (!matchedPatient) {
          throw new Error(`Patient with ID "${patientIdStr}" not found`);
        }
        numericId = matchedPatient.id;
        apiPatient = matchedPatient;
      }
      
      // Parse date of birth
      let dobFormatted = '';
      if (apiPatient.date_of_birth) {
        try {
          const date = new Date(apiPatient.date_of_birth);
          if (!isNaN(date.getTime())) {
            dobFormatted = date.toISOString().split('T')[0];
          }
        } catch (e) {
          console.warn('Failed to parse date_of_birth:', e);
        }
      }
      
      // Normalize values to match dropdown options
      const normalizedTitle = apiPatient.title ? apiPatient.title.toLowerCase() : '';
      const normalizedMaritalStatus = apiPatient.marital_status ? apiPatient.marital_status.toLowerCase() : '';
      const normalizedEmployeeType = apiPatient.employee_type ? apiPatient.employee_type.charAt(0).toUpperCase() + apiPatient.employee_type.slice(1).toLowerCase() : '';
      const normalizedNokRelationship = apiPatient.nok_relationship ? apiPatient.nok_relationship.charAt(0).toUpperCase() + apiPatient.nok_relationship.slice(1).toLowerCase() : '';
      
      setEditForm({
        title: normalizedTitle,
        firstName: apiPatient.first_name || '',
        lastName: apiPatient.surname || '',
        middleName: apiPatient.middle_name || '',
        dateOfBirth: dobFormatted,
        maritalStatus: normalizedMaritalStatus,
        phone: apiPatient.phone || '',
        email: apiPatient.email || '',
        residentialAddress: apiPatient.residential_address || '',
        permanentAddress: apiPatient.permanent_address || '',
        stateOfResidence: apiPatient.state_of_residence || '',
        stateOfOrigin: apiPatient.state_of_origin || '',
        lga: apiPatient.lga || '',
        bloodGroup: apiPatient.blood_group || '',
        genotype: apiPatient.genotype || '',
        location: apiPatient.location || '',
        division: apiPatient.division || '',
        employeeType: normalizedEmployeeType,
        nokFirstName: apiPatient.nok_first_name || '',
        nokMiddleName: apiPatient.nok_middle_name || '',
        nokRelationship: normalizedNokRelationship,
        nokPhone: apiPatient.nok_phone || '',
        nokAddress: apiPatient.nok_address || '',
      });
      
      // Set photo preview if patient has photo
      if (apiPatient.photo) {
        setPhotoPreview(apiPatient.photo);
      } else {
        setPhotoPreview(null);
      }
      setPhotoFile(null);
    } catch (err: any) {
      console.error('Error loading patient for edit:', err);
      toast.error('Failed to load patient data: ' + (err.message || 'Unknown error'));
      setIsEditModalOpen(false);
    } finally {
      setEditFormLoading(false);
    }
  };

  const handlePhotoSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    
    if (file.size > 5 * 1024 * 1024) {
      toast.error('Photo must be less than 5MB');
      return;
    }
    
    setPhotoFile(file);
    const reader = new FileReader();
    reader.onloadend = () => {
      setPhotoPreview(reader.result as string);
    };
    reader.readAsDataURL(file);
  };

  const handleRemovePhoto = () => {
    setPhotoFile(null);
    setPhotoPreview(null);
  };

  const handleSaveEdit = async () => {
    if (!selectedPatient) return;
    setIsSubmitting(true);

    try {
      // Look up patient by patient_id to get numeric ID
      const patientIdStr = selectedPatient.id.trim();
      let numericId: number;
      
      // Check if it's a numeric ID
      const parsedId = parseInt(patientIdStr, 10);
      if (!isNaN(parsedId) && parsedId > 0) {
        numericId = parsedId;
      } else {
        // It's a string patient_id (like "E-A2962") - search for it
        const searchResult = await patientService.getPatients({ search: patientIdStr });
        const matchedPatient = searchResult.results.find(
          p => p.patient_id === patientIdStr || p.patient_id.toUpperCase() === patientIdStr.toUpperCase()
        );
        if (!matchedPatient) {
          throw new Error(`Patient with ID "${patientIdStr}" not found`);
        }
        numericId = matchedPatient.id;
      }
      
      // Map frontend form fields to backend API fields (snake_case)
      const updateData: Partial<ApiPatient> = {
        title: editForm.title && editForm.title.trim() !== '' ? editForm.title.toLowerCase() : undefined,
        first_name: editForm.firstName.trim() || undefined,
        surname: editForm.lastName.trim() || undefined,
        middle_name: editForm.middleName.trim() || undefined,
        date_of_birth: editForm.dateOfBirth || undefined,
        marital_status: editForm.maritalStatus && editForm.maritalStatus.trim() !== '' 
          ? editForm.maritalStatus.toLowerCase() 
          : undefined,
        phone: editForm.phone.trim() || undefined,
        email: editForm.email.trim() || undefined,
        residential_address: editForm.residentialAddress.trim() || undefined,
        permanent_address: editForm.permanentAddress.trim() || undefined,
        state_of_residence: editForm.stateOfResidence.trim() || undefined,
        state_of_origin: editForm.stateOfOrigin.trim() || undefined,
        lga: editForm.lga.trim() || undefined,
        blood_group: editForm.bloodGroup && editForm.bloodGroup.trim() !== '' ? editForm.bloodGroup : undefined,
        genotype: editForm.genotype && editForm.genotype.trim() !== '' ? editForm.genotype : undefined,
        location: editForm.location.trim() || undefined,
        division: editForm.division.trim() || undefined,
        employee_type: editForm.employeeType && editForm.employeeType.trim() !== '' 
          ? editForm.employeeType.charAt(0).toUpperCase() + editForm.employeeType.slice(1).toLowerCase()
          : undefined,
        nok_first_name: editForm.nokFirstName.trim() || undefined,
        nok_middle_name: editForm.nokMiddleName.trim() || undefined,
        nok_relationship: editForm.nokRelationship && editForm.nokRelationship.trim() !== '' 
          ? editForm.nokRelationship.charAt(0).toUpperCase() + editForm.nokRelationship.slice(1).toLowerCase()
          : undefined,
        nok_address: editForm.nokAddress.trim() || undefined,
        nok_phone: editForm.nokPhone.trim() || undefined,
      };

      // Remove undefined values to avoid sending them
      Object.keys(updateData).forEach(key => {
        if (updateData[key as keyof typeof updateData] === undefined) {
          delete updateData[key as keyof typeof updateData];
        }
      });

      // Handle photo upload if a new photo was selected
      if (photoFile) {
        // Get valid access token using the same method as apiFetch
        const { getStoredAccessToken } = await import('@/lib/api-client');
        let token = getStoredAccessToken();
        
        // If token is expired or missing, try to refresh it
        if (!token) {
          // Try to get refresh token and refresh
          const refreshToken = localStorage.getItem('npa_ecm_refresh_token');
          if (refreshToken) {
            const apiUrl = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8001/api';
            const baseUrl = apiUrl.endsWith('/') ? apiUrl.slice(0, -1) : apiUrl;
            const refreshResponse = await fetch(`${baseUrl}/accounts/auth/token/refresh/`, {
              method: 'POST',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify({ refresh: refreshToken }),
            });
            
            if (refreshResponse.ok) {
              const data = await refreshResponse.json();
              token = data.access;
              localStorage.setItem('npa_ecm_access_token', data.access);
              if (data.refresh) {
                localStorage.setItem('npa_ecm_refresh_token', data.refresh);
              }
            }
          }
        }

        if (!token) {
          throw new Error('Authentication required. Please log in again.');
        }

        const formData = new FormData();
        // Add all update data to FormData for multipart/form-data request
        Object.keys(updateData).forEach(key => {
          const value = updateData[key as keyof typeof updateData];
          if (value !== undefined && value !== null) {
            formData.append(key, String(value));
          }
        });
        formData.append('photo', photoFile);
        
        // Update patient with photo via FormData
        try {
          const apiUrl = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8001/api';
          const baseUrl = apiUrl.endsWith('/') ? apiUrl.slice(0, -1) : apiUrl;
          const photoUrl = `${baseUrl}/patients/${numericId}/`;
          
          const response = await fetch(photoUrl, {
            method: 'PATCH',
            headers: {
              'Authorization': `Bearer ${token}`,
              // Don't set Content-Type - browser will set it with boundary for FormData
            },
            body: formData,
          });
          
          if (!response.ok) {
            const errorData = await response.json().catch(() => ({}));
            throw new Error(errorData.photo?.[0] || errorData.detail || 'Failed to update patient with photo');
          }
        } catch (photoError: any) {
          console.warn('Photo upload failed, trying without photo:', photoError);
          // Fallback to regular update without photo
          await patientService.updatePatient(numericId, updateData);
        }
      } else {
        // Update without photo
        await patientService.updatePatient(numericId, updateData);
      }

      toast.success(`Patient ${editForm.firstName} ${editForm.lastName} updated successfully`);
      
      // Reload patients
      await loadPatients();
      
      setIsEditModalOpen(false);
      setPhotoFile(null);
      setPhotoPreview(null);
    } catch (err: any) {
      toast.error(err.message || 'Failed to update patient');
      console.error('Error updating patient:', err);
    } finally {
      setIsSubmitting(false);
    }
  };

  const clearFilters = () => {
    setGenderFilter('all');
    setCategoryFilter('all');
    setLocationFilter('all');
    setAgeRange({ min: '', max: '' });
    setDateRange({ from: '', to: '' });
    setIsFilterDialogOpen(false);
    toast.info('Filters cleared');
  };

  const getCategoryBadge = (category: string) => {
    const styles: Record<string, string> = {
      'Employee': 'border-teal-500/50 text-teal-600 dark:text-teal-400',
      'Retiree': 'border-amber-500/50 text-amber-600 dark:text-amber-400',
      'Dependent': 'border-violet-500/50 text-violet-600 dark:text-violet-400',
      'NonNPA': 'border-blue-500/50 text-blue-600 dark:text-blue-400',
    };
    return styles[category] || 'border-muted-foreground/50 text-muted-foreground';
  };

  return (
    <DashboardLayout>
      <div className="container mx-auto p-6 space-y-6">
        {/* Header */}
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div>
            <h1 className="text-3xl font-bold text-foreground">Manage Patients</h1>
            <p className="text-muted-foreground mt-1">Search, view, and manage all patient records in the system</p>
          </div>
          <Button className="bg-gradient-to-r from-teal-500 to-cyan-500 hover:from-teal-600 hover:to-cyan-600 text-white" asChild>
            <Link href="/medical-records/patients/new">
              <UserPlus className="h-4 w-4 mr-2" />Register Patient
            </Link>
          </Button>
        </div>

        {/* Stats */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          {stats.map((stat, i) => (
            <Card key={i}>
              <CardContent className="p-4">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-sm text-muted-foreground">{stat.label}</p>
                    <p className={`text-3xl font-bold ${stat.color} mt-1`}>{stat.value}</p>
                  </div>
                  <div className={`p-3 rounded-full ${stat.bg}`}>
                    <stat.icon className={`h-5 w-5 ${stat.color}`} />
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>

        <div className="grid gap-6 lg:grid-cols-4">
          {/* Main Content */}
          <div className="lg:col-span-3 space-y-4">
            {/* Search and Filters */}
            <Card>
              <CardContent className="p-4">
                <div className="flex flex-col gap-4">
                  <div className="flex flex-col md:flex-row gap-3">
                    <div className="relative flex-1">
                      <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                      <Input 
                        placeholder="Search by name, patient ID, or phone..." 
                        value={searchQuery} 
                        onChange={(e) => setSearchQuery(e.target.value)} 
                        className="pl-10" 
                      />
                    </div>
                    <Button variant="outline" onClick={() => setIsFilterDialogOpen(true)}>
                      <Filter className="h-4 w-4 mr-2" />Filters
                    </Button>
                  </div>
                  <div className="flex flex-wrap gap-2">
                    <Select value={categoryFilter} onValueChange={setCategoryFilter}>
                      <SelectTrigger className="w-[140px]"><SelectValue placeholder="Category" /></SelectTrigger>
                      <SelectContent>
                        {categories.map(c => <SelectItem key={c} value={c === 'All Categories' ? 'all' : c.toLowerCase()}>{c}</SelectItem>)}
                      </SelectContent>
                    </Select>
                    <Select value={genderFilter} onValueChange={setGenderFilter}>
                      <SelectTrigger className="w-[120px]"><SelectValue placeholder="Gender" /></SelectTrigger>
                      <SelectContent>
                        <SelectItem value="all">All Gender</SelectItem>
                        <SelectItem value="male">Male</SelectItem>
                        <SelectItem value="female">Female</SelectItem>
                      </SelectContent>
                    </Select>
                    <Select value={locationFilter} onValueChange={setLocationFilter}>
                      <SelectTrigger className="w-[180px]"><SelectValue placeholder="Location" /></SelectTrigger>
                      <SelectContent>
                        {locations.map(l => <SelectItem key={l} value={l === 'All Locations' ? 'all' : l}>{l}</SelectItem>)}
                      </SelectContent>
                    </Select>
                  </div>
                </div>
              </CardContent>
            </Card>


            {/* Patients List */}
            <div className="space-y-3">
              <p className="text-sm text-muted-foreground">Showing <span className="font-medium">{filteredPatients.length}</span> patients</p>
              
              {loading ? (
                <Card><CardContent className="p-8 text-center text-muted-foreground">
                  <Loader2 className="h-12 w-12 mx-auto mb-4 animate-spin opacity-50" />
                  <p>Loading patients...</p>
                </CardContent></Card>
              ) : error ? (
                <Card><CardContent className="p-8 text-center text-muted-foreground">
                  <AlertTriangle className="h-12 w-12 mx-auto mb-4 opacity-50" />
                  <p className="text-red-600 dark:text-red-400">{error}</p>
                  {isAuthenticationError(authError) ? (
                    <div className="mt-4 space-y-2">
                      <p className="text-sm text-muted-foreground">Please log in to continue</p>
                      <Button variant="outline" onClick={() => router.push('/login')}>
                        Go to Login
                      </Button>
                    </div>
                  ) : (
                    <Button variant="outline" className="mt-4" onClick={loadPatients}>Retry</Button>
                  )}
                </CardContent></Card>
              ) : paginatedPatients.length > 0 ? (
                paginatedPatients.map((patient) => (
                  <Card key={patient.id} className={`border-l-4 ${
                    patient.category === 'Employee' ? 'border-l-teal-500' :
                    patient.category === 'Retiree' ? 'border-l-amber-500' :
                    patient.category === 'Dependent' ? 'border-l-violet-500' :
                    'border-l-blue-500'
                  } hover:shadow-md transition-shadow`}>
                    <CardContent className="py-3 px-4">
                      <div className="flex items-center gap-3">
                        {/* Avatar */}
                        <PatientAvatar patient={patient} size="md" />
                        
                        {/* Info */}
                        <div className="flex-1 min-w-0">
                          {/* Row 1: Name + Category + Actions */}
                          <div className="flex items-center justify-between gap-2">
                            <div className="flex items-center gap-2 flex-wrap min-w-0">
                              <Link href={`/medical-records/patients/${patient.id}`} className="font-semibold text-foreground hover:text-primary transition-colors truncate">
                                {patient.name}
                              </Link>
                              <Badge variant="outline" className={`text-[10px] px-1.5 py-0 ${getCategoryBadge(patient.category)}`}>
                                {patient.category}
                              </Badge>
                            </div>
                            <div className="flex items-center gap-1 flex-shrink-0">
                              <Button variant="ghost" size="sm" className="h-7 w-7 p-0" onClick={() => openViewModal(patient)} title="View Patient">
                                <Eye className="h-4 w-4 text-muted-foreground hover:text-primary" />
                              </Button>
                              <Button variant="ghost" size="sm" className="h-7 w-7 p-0" onClick={() => openEditModal(patient)} title="Edit Patient">
                                <Edit className="h-4 w-4 text-muted-foreground hover:text-blue-500" />
                              </Button>
                              <Button variant="ghost" size="sm" className="h-7 w-7 p-0" onClick={() => router.push(`/medical-records/visits/new?patient=${patient.id}`)} title="Create Visit">
                                <Calendar className="h-4 w-4 text-muted-foreground hover:text-teal-500" />
                              </Button>
                            </div>
                          </div>
                          
                          {/* Row 2: Details */}
                          <div className="flex items-center gap-2 text-xs text-muted-foreground mt-1 flex-wrap">
                            <span>{patient.id}</span>
                            <span>•</span>
                            <span>{patient.age}y {patient.gender}</span>
                            <span>•</span>
                            <span className="flex items-center gap-1"><Phone className="h-3 w-3" />{patient.phone}</span>
                            <span>•</span>
                            <span className="truncate max-w-[120px]">{patient.location}</span>
                            <span>•</span>
                            <span>Last: {patient.lastVisit}</span>
                            <span className="text-teal-600 dark:text-teal-400">({patient.totalVisits} visits)</span>
                          </div>
                        </div>
                      </div>
                    </CardContent>
                  </Card>
                ))
              ) : (
                <Card>
                  <CardContent className="p-8 text-center text-muted-foreground">
                    <Users className="h-12 w-12 mx-auto mb-4 opacity-50" />
                    <p>No patients found matching your criteria</p>
                  </CardContent>
                </Card>
              )}
            </div>

            {/* Pagination */}
            {filteredPatients.length > 0 && (
              <Card className="p-4">
                <StandardPagination
                  currentPage={currentPage}
                  totalItems={filteredPatients.length}
                  itemsPerPage={itemsPerPage}
                  onPageChange={setCurrentPage}
                  onItemsPerPageChange={setItemsPerPage}
                  itemName="patients"
                />
              </Card>
            )}
          </div>

          {/* Sidebar */}
          <div className="space-y-4">
            {/* Quick Actions */}
            <Card>
              <CardHeader className="pb-3">
                <CardTitle className="text-lg">Quick Actions</CardTitle>
              </CardHeader>
              <CardContent className="space-y-2">
                <Button variant="ghost" size="sm" className="w-full justify-start" onClick={() => router.push('/medical-records/patients/new')}>
                  <UserPlus className="h-4 w-4 mr-2" />Register New Patient
                </Button>
                <Button variant="ghost" size="sm" className="w-full justify-start" onClick={() => router.push('/medical-records/visits/new')}>
                  <Calendar className="h-4 w-4 mr-2" />Create Visit
                </Button>
                <Button variant="ghost" size="sm" className="w-full justify-start" onClick={() => router.push('/medical-records/dependents')}>
                  <Users className="h-4 w-4 mr-2" />Manage Dependents
                </Button>
                <Button variant="ghost" size="sm" className="w-full justify-start" onClick={() => router.push('/medical-records/reports')}>
                  <FileText className="h-4 w-4 mr-2" />Reports
                </Button>
              </CardContent>
            </Card>

            {/* Categories Breakdown */}
            <Card>
              <CardHeader className="pb-3">
                <CardTitle className="text-lg">By Category</CardTitle>
              </CardHeader>
              <CardContent className="space-y-3">
                {['Employee', 'Retiree', 'Dependent', 'NonNPA'].map((cat) => {
                  const count = patients.filter(p => p.category === cat).length;
                  const percentage = Math.round((count / patients.length) * 100);
                  return (
                    <div key={cat} className="space-y-1">
                      <div className="flex items-center justify-between text-sm">
                        <span className="text-muted-foreground">{cat}</span>
                        <span className="font-medium">{count}</span>
                      </div>
                      <div className="h-2 bg-muted rounded-full overflow-hidden">
                        <div 
                          className={`h-full rounded-full ${cat === 'Employee' ? 'bg-teal-500' : cat === 'Retiree' ? 'bg-amber-500' : cat === 'Dependent' ? 'bg-violet-500' : 'bg-blue-500'}`}
                          style={{ width: `${percentage}%` }}
                        />
                      </div>
                    </div>
                  );
                })}
              </CardContent>
            </Card>
          </div>
        </div>

        {/* Advanced Filters Dialog */}
        <Dialog open={isFilterDialogOpen} onOpenChange={setIsFilterDialogOpen}>
          <DialogContent className="sm:max-w-[500px]">
            <DialogHeader>
              <DialogTitle className="flex items-center gap-2"><Filter className="h-5 w-5 text-primary" />Advanced Filters</DialogTitle>
              <DialogDescription>Apply additional filters to narrow down the patient list.</DialogDescription>
            </DialogHeader>
            <div className="grid gap-4 py-4">
              <div className="space-y-2">
                <Label>Age Range</Label>
                <div className="flex items-center gap-2">
                  <Input type="number" placeholder="Min" value={ageRange.min} onChange={(e) => setAgeRange(prev => ({ ...prev, min: e.target.value }))} />
                  <span className="text-muted-foreground">to</span>
                  <Input type="number" placeholder="Max" value={ageRange.max} onChange={(e) => setAgeRange(prev => ({ ...prev, max: e.target.value }))} />
                </div>
              </div>
              <div className="space-y-2">
                <Label>Last Visit Date Range</Label>
                <div className="flex items-center gap-2">
                  <Input type="date" value={dateRange.from} onChange={(e) => setDateRange(prev => ({ ...prev, from: e.target.value }))} />
                  <span className="text-muted-foreground">to</span>
                  <Input type="date" value={dateRange.to} onChange={(e) => setDateRange(prev => ({ ...prev, to: e.target.value }))} />
                </div>
              </div>
            </div>
            <DialogFooter>
              <Button variant="outline" onClick={clearFilters}><X className="h-4 w-4 mr-2" />Clear All</Button>
              <Button onClick={() => setIsFilterDialogOpen(false)}>Apply Filters</Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>

        {/* Patient Overview Modal */}
        <Dialog open={isViewModalOpen} onOpenChange={setIsViewModalOpen}>
          <DialogContent className="sm:max-w-[600px] max-h-[90vh] overflow-y-auto">
            <DialogHeader>
              <DialogTitle className="flex items-center gap-2">
                <User className="h-5 w-5 text-teal-500" />
                Patient Overview
              </DialogTitle>
              <DialogDescription>Patient registration details and information</DialogDescription>
            </DialogHeader>
            {selectedPatient && (
              <div className="space-y-6 py-4">
                {/* Patient Header */}
                <div className="flex items-center gap-4 p-4 rounded-lg bg-gradient-to-r from-teal-500/10 to-cyan-500/10">
                  <PatientAvatar patient={selectedPatient} size="lg" />
                  <div>
                    <h3 className="text-xl font-bold text-foreground">{selectedPatient.name}</h3>
                    <div className="flex items-center gap-2 mt-1">
                      <Badge variant="outline" className={getCategoryBadge(selectedPatient.category)}>{selectedPatient.category}</Badge>
                      <span className="text-sm text-muted-foreground">{selectedPatient.id}</span>
                    </div>
                    {selectedPatient.personalNumber && (
                      <p className="text-sm text-muted-foreground mt-1">Personal #: {selectedPatient.personalNumber}</p>
                    )}
                  </div>
                </div>

                {/* Basic Info */}
                <div>
                  <h4 className="text-sm font-semibold text-muted-foreground mb-3">BASIC INFORMATION</h4>
                  <div className="grid grid-cols-2 gap-4">
                    <div className="space-y-1">
                      <p className="text-xs text-muted-foreground">Date of Birth</p>
                      <p className="text-sm font-medium">{selectedPatient.dob}</p>
                    </div>
                    <div className="space-y-1">
                      <p className="text-xs text-muted-foreground">Age / Gender</p>
                      <p className="text-sm font-medium">{selectedPatient.age} years • {selectedPatient.gender}</p>
                    </div>
                    <div className="space-y-1">
                      <p className="text-xs text-muted-foreground">Blood Group</p>
                      <p className="text-sm font-medium flex items-center gap-1"><Droplets className="h-3 w-3 text-rose-500" />{selectedPatient.bloodGroup}</p>
                    </div>
                    <div className="space-y-1">
                      <p className="text-xs text-muted-foreground">Registered</p>
                      <p className="text-sm font-medium">{selectedPatient.registeredAt}</p>
                    </div>
                  </div>
                </div>

                <Separator />

                {/* Contact Info */}
                <div>
                  <h4 className="text-sm font-semibold text-muted-foreground mb-3">CONTACT INFORMATION</h4>
                  <div className="space-y-3">
                    <div className="flex items-center gap-3">
                      <Phone className="h-4 w-4 text-muted-foreground" />
                      <span className="text-sm">{selectedPatient.phone}</span>
                    </div>
                    <div className="flex items-center gap-3">
                      <Mail className="h-4 w-4 text-muted-foreground" />
                      <span className="text-sm">{selectedPatient.email}</span>
                    </div>
                    <div className="flex items-start gap-3">
                      <MapPin className="h-4 w-4 text-muted-foreground mt-0.5" />
                      <span className="text-sm">{selectedPatient.address}</span>
                    </div>
                    <div className="flex items-center gap-3">
                      <AlertTriangle className="h-4 w-4 text-amber-500" />
                      <span className="text-sm"><strong>Emergency:</strong> {selectedPatient.emergencyContact}</span>
                    </div>
                  </div>
                </div>

                <Separator />

                {/* Category Specific Info */}
                <div>
                  <h4 className="text-sm font-semibold text-muted-foreground mb-3">
                    {selectedPatient.category === 'Employee' ? 'EMPLOYMENT DETAILS' : 
                     selectedPatient.category === 'Dependent' ? 'DEPENDENT DETAILS' :
                     selectedPatient.category === 'Retiree' ? 'RETIREE DETAILS' : 'NON-NPA DETAILS'}
                  </h4>
                  <div className="grid grid-cols-2 gap-4">
                    <div className="space-y-1">
                      <p className="text-xs text-muted-foreground">Location</p>
                      <p className="text-sm font-medium flex items-center gap-1"><MapPin className="h-3 w-3" />{selectedPatient.location}</p>
                    </div>
                    {selectedPatient.category === 'Employee' && (
                      <>
                        <div className="space-y-1">
                          <p className="text-xs text-muted-foreground">Employee Type</p>
                          <p className="text-sm font-medium">{selectedPatient.employeeType}</p>
                        </div>
                        <div className="space-y-1">
                          <p className="text-xs text-muted-foreground">Division</p>
                          <p className="text-sm font-medium flex items-center gap-1"><Briefcase className="h-3 w-3" />{selectedPatient.division}</p>
                        </div>
                      </>
                    )}
                    {selectedPatient.category === 'Dependent' && (
                      <>
                        <div className="space-y-1">
                          <p className="text-xs text-muted-foreground">Primary Patient</p>
                          <p className="text-sm font-medium">{selectedPatient.primaryPatient}</p>
                        </div>
                        <div className="space-y-1">
                          <p className="text-xs text-muted-foreground">Relationship</p>
                          <p className="text-sm font-medium">{selectedPatient.relationship}</p>
                        </div>
                      </>
                    )}
                    {selectedPatient.category === 'NonNPA' && (
                      <div className="space-y-1">
                        <p className="text-xs text-muted-foreground">Non-NPA Type</p>
                        <p className="text-sm font-medium">{selectedPatient.nonNpaType}</p>
                      </div>
                    )}
                  </div>
                </div>

                <Separator />

                {/* Visit Stats */}
                <div className="flex items-center justify-between p-3 rounded-lg bg-muted/50">
                  <div>
                    <p className="text-xs text-muted-foreground">Total Visits</p>
                    <p className="text-lg font-bold text-teal-600">{selectedPatient.totalVisits}</p>
                  </div>
                  <div>
                    <p className="text-xs text-muted-foreground">Last Visit</p>
                    <p className="text-sm font-medium">{selectedPatient.lastVisit}</p>
                  </div>
                </div>
              </div>
            )}
            <DialogFooter>
              <Button variant="outline" onClick={() => setIsViewModalOpen(false)}>Close</Button>
              <Button onClick={() => { setIsViewModalOpen(false); if (selectedPatient) openEditModal(selectedPatient); }}>
                <Edit className="h-4 w-4 mr-2" />Edit Patient
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>

        {/* Edit Patient Modal */}
        <Dialog open={isEditModalOpen} onOpenChange={setIsEditModalOpen}>
          <DialogContent className="sm:max-w-[700px] max-h-[85vh] overflow-y-auto">
            <DialogHeader>
              <DialogTitle className="flex items-center gap-2">
                <Edit className="h-5 w-5 text-blue-500" />
                Edit Patient
              </DialogTitle>
              <DialogDescription>Update patient registration information</DialogDescription>
            </DialogHeader>
            {selectedPatient && (
              <div className="space-y-4 py-4">
                {editFormLoading ? (
                  <div className="flex items-center justify-center py-12">
                    <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
                    <span className="ml-3 text-muted-foreground">Loading patient data...</span>
                  </div>
                ) : (
                  <>
                    {/* Patient ID (Read-only) */}
                    <div className="p-3 rounded-lg bg-muted/50">
                      <p className="text-xs text-muted-foreground">Patient ID (Cannot be changed)</p>
                      <p className="font-medium">{selectedPatient.id}</p>
                    </div>

                    {/* Photo Upload */}
                    <div className="space-y-2">
                      <Label>Patient Photo</Label>
                      <div className="flex items-center gap-4">
                        <div className="w-20 h-20 rounded-lg border-2 border-dashed border-border bg-muted/30 flex items-center justify-center overflow-hidden">
                          {photoPreview ? (
                            <img src={photoPreview} alt="Preview" className="w-full h-full object-cover" />
                          ) : (
                            <Camera className="h-6 w-6 text-muted-foreground" />
                          )}
                        </div>
                        <div className="flex-1 space-y-2">
                          <div className="flex gap-2">
                            <input 
                              type="file" 
                              id="edit-photo-upload" 
                              accept="image/*" 
                              onChange={handlePhotoSelect} 
                              className="hidden" 
                            />
                            <Button 
                              variant="outline" 
                              size="sm" 
                              type="button"
                              onClick={() => document.getElementById('edit-photo-upload')?.click()}
                            >
                              <Upload className="h-4 w-4 mr-2" />
                              {photoPreview ? 'Change Photo' : 'Upload Photo'}
                            </Button>
                            {photoPreview && (
                              <Button 
                                variant="outline" 
                                size="sm" 
                                type="button"
                                onClick={handleRemovePhoto}
                              >
                                <Trash2 className="h-4 w-4 mr-2" />
                                Remove
                              </Button>
                            )}
                          </div>
                          <p className="text-xs text-muted-foreground">JPG, PNG. Max 5MB</p>
                        </div>
                      </div>
                    </div>

                    <Separator />

                    {/* Personal Information */}
                    <div className="space-y-4">
                      <h3 className="text-sm font-semibold text-foreground">Personal Information</h3>
                      <div className="grid grid-cols-4 gap-4">
                        <div className="space-y-2">
                          <Label>Title</Label>
                          <Select value={editForm.title || undefined} onValueChange={(v) => setEditForm(prev => ({ ...prev, title: v === 'none' ? '' : v }))}>
                            <SelectTrigger><SelectValue placeholder="Select" /></SelectTrigger>
                            <SelectContent>
                              <SelectItem value="none">None</SelectItem>
                              {titles.map(title => <SelectItem key={title} value={title.toLowerCase()}>{title}</SelectItem>)}
                            </SelectContent>
                          </Select>
                        </div>
                        <div className="space-y-2">
                          <Label>First Name *</Label>
                          <Input value={editForm.firstName} onChange={(e) => setEditForm(prev => ({ ...prev, firstName: e.target.value }))} />
                        </div>
                        <div className="space-y-2">
                          <Label>Middle Name</Label>
                          <Input value={editForm.middleName} onChange={(e) => setEditForm(prev => ({ ...prev, middleName: e.target.value }))} />
                        </div>
                        <div className="space-y-2">
                          <Label>Surname *</Label>
                          <Input value={editForm.lastName} onChange={(e) => setEditForm(prev => ({ ...prev, lastName: e.target.value }))} />
                        </div>
                      </div>
                      <div className="grid grid-cols-2 gap-4">
                        <div className="space-y-2">
                          <Label>Date of Birth</Label>
                          <Input type="date" value={editForm.dateOfBirth} onChange={(e) => setEditForm(prev => ({ ...prev, dateOfBirth: e.target.value }))} />
                        </div>
                        <div className="space-y-2">
                          <Label>Marital Status</Label>
                          <Select value={editForm.maritalStatus || undefined} onValueChange={(v) => setEditForm(prev => ({ ...prev, maritalStatus: v === 'not-specified' ? '' : v }))}>
                            <SelectTrigger><SelectValue placeholder="Select" /></SelectTrigger>
                            <SelectContent>
                              <SelectItem value="not-specified">Not specified</SelectItem>
                              {maritalStatuses.map(status => <SelectItem key={status} value={status.toLowerCase()}>{status}</SelectItem>)}
                            </SelectContent>
                          </Select>
                        </div>
                      </div>
                    </div>

                    <Separator />

                    {/* Contact Information */}
                    <div className="space-y-4">
                      <h3 className="text-sm font-semibold text-foreground">Contact Information</h3>
                      <div className="grid grid-cols-2 gap-4">
                        <div className="space-y-2">
                          <Label>Phone *</Label>
                          <Input value={editForm.phone} onChange={(e) => setEditForm(prev => ({ ...prev, phone: e.target.value }))} placeholder="+234..." />
                        </div>
                        <div className="space-y-2">
                          <Label>Email</Label>
                          <Input type="email" value={editForm.email} onChange={(e) => setEditForm(prev => ({ ...prev, email: e.target.value }))} placeholder="email@example.com" />
                        </div>
                      </div>
                      <div className="space-y-2">
                        <Label>Residential Address</Label>
                        <Input value={editForm.residentialAddress} onChange={(e) => setEditForm(prev => ({ ...prev, residentialAddress: e.target.value }))} placeholder="Street address" />
                      </div>
                      <div className="space-y-2">
                        <Label>Permanent Address</Label>
                        <Input value={editForm.permanentAddress} onChange={(e) => setEditForm(prev => ({ ...prev, permanentAddress: e.target.value }))} placeholder="Permanent address (if different)" />
                      </div>
                      <div className="grid grid-cols-3 gap-4">
                        <div className="space-y-2">
                          <Label>LGA</Label>
                          <Input value={editForm.lga} onChange={(e) => setEditForm(prev => ({ ...prev, lga: e.target.value }))} placeholder="Local Government Area" />
                        </div>
                        <div className="space-y-2">
                          <Label>State of Residence</Label>
                          <Select value={editForm.stateOfResidence || undefined} onValueChange={(v) => setEditForm(prev => ({ ...prev, stateOfResidence: v === 'not-specified' ? '' : v }))}>
                            <SelectTrigger><SelectValue placeholder="Select state" /></SelectTrigger>
                            <SelectContent>
                              <SelectItem value="not-specified">Not specified</SelectItem>
                              {NIGERIA_STATES.map(state => <SelectItem key={state} value={state}>{state}</SelectItem>)}
                            </SelectContent>
                          </Select>
                        </div>
                        <div className="space-y-2">
                          <Label>State of Origin</Label>
                          <Select value={editForm.stateOfOrigin || undefined} onValueChange={(v) => setEditForm(prev => ({ ...prev, stateOfOrigin: v === 'not-specified' ? '' : v }))}>
                            <SelectTrigger><SelectValue placeholder="Select state" /></SelectTrigger>
                            <SelectContent>
                              <SelectItem value="not-specified">Not specified</SelectItem>
                              {NIGERIA_STATES.map(state => <SelectItem key={state} value={state}>{state}</SelectItem>)}
                            </SelectContent>
                          </Select>
                        </div>
                      </div>
                    </div>

                    <Separator />

                    {/* Medical Information */}
                    <div className="space-y-4">
                      <h3 className="text-sm font-semibold text-foreground">Medical Information</h3>
                      <div className="grid grid-cols-2 gap-4">
                        <div className="space-y-2">
                          <Label>Blood Group</Label>
                          <Select value={editForm.bloodGroup || undefined} onValueChange={(v) => setEditForm(prev => ({ ...prev, bloodGroup: v === 'not-specified' ? '' : v }))}>
                            <SelectTrigger><SelectValue placeholder="Select" /></SelectTrigger>
                            <SelectContent>
                              <SelectItem value="not-specified">Not specified</SelectItem>
                              {['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'].map(bg => <SelectItem key={bg} value={bg}>{bg}</SelectItem>)}
                            </SelectContent>
                          </Select>
                        </div>
                        <div className="space-y-2">
                          <Label>Genotype</Label>
                          <Select value={editForm.genotype || undefined} onValueChange={(v) => setEditForm(prev => ({ ...prev, genotype: v === 'not-specified' ? '' : v }))}>
                            <SelectTrigger><SelectValue placeholder="Select" /></SelectTrigger>
                            <SelectContent>
                              <SelectItem value="not-specified">Not specified</SelectItem>
                              {['AA', 'AS', 'SS', 'AC', 'SC'].map(g => <SelectItem key={g} value={g}>{g}</SelectItem>)}
                            </SelectContent>
                          </Select>
                        </div>
                      </div>
                    </div>

                    {/* Work Information (if Employee) */}
                    {selectedPatient.category === 'Employee' && (
                      <>
                        <Separator />
                        <div className="space-y-4">
                          <h3 className="text-sm font-semibold text-foreground">Employment Details</h3>
                          <div className="grid grid-cols-3 gap-4">
                            <div className="space-y-2">
                              <Label>Employee Type</Label>
                              <Select value={editForm.employeeType || undefined} onValueChange={(v) => setEditForm(prev => ({ ...prev, employeeType: v === 'not-specified' ? '' : v }))}>
                                <SelectTrigger><SelectValue placeholder="Select" /></SelectTrigger>
                                <SelectContent>
                                  <SelectItem value="not-specified">Not specified</SelectItem>
                                  <SelectItem value="Officer">Officer</SelectItem>
                                  <SelectItem value="Staff">Staff</SelectItem>
                                </SelectContent>
                              </Select>
                            </div>
                            <div className="space-y-2">
                              <Label>Division</Label>
                              <Select value={editForm.division || undefined} onValueChange={(v) => setEditForm(prev => ({ ...prev, division: v === 'not-specified' ? '' : v }))}>
                                <SelectTrigger><SelectValue placeholder="Select division" /></SelectTrigger>
                                <SelectContent>
                                  <SelectItem value="not-specified">Not specified</SelectItem>
                                  {divisions.map(div => <SelectItem key={div} value={div}>{div}</SelectItem>)}
                                </SelectContent>
                              </Select>
                            </div>
                            <div className="space-y-2">
                              <Label>Location</Label>
                              <Select value={editForm.location || undefined} onValueChange={(v) => setEditForm(prev => ({ ...prev, location: v === 'not-specified' ? '' : v }))}>
                                <SelectTrigger><SelectValue placeholder="Select" /></SelectTrigger>
                                <SelectContent>
                                  <SelectItem value="not-specified">Not specified</SelectItem>
                                  {locations.filter(l => l !== 'All Locations').map(l => (
                                    <SelectItem key={l} value={l}>{l}</SelectItem>
                                  ))}
                                </SelectContent>
                              </Select>
                            </div>
                          </div>
                        </div>
                      </>
                    )}

                    <Separator />

                    {/* Next of Kin */}
                    <div className="space-y-4">
                      <h3 className="text-sm font-semibold text-foreground">Next of Kin</h3>
                      <div className="grid grid-cols-2 gap-4">
                        <div className="space-y-2">
                          <Label>First Name</Label>
                          <Input value={editForm.nokFirstName} onChange={(e) => setEditForm(prev => ({ ...prev, nokFirstName: e.target.value }))} />
                        </div>
                        <div className="space-y-2">
                          <Label>Middle Name</Label>
                          <Input value={editForm.nokMiddleName} onChange={(e) => setEditForm(prev => ({ ...prev, nokMiddleName: e.target.value }))} />
                        </div>
                      </div>
                      <div className="grid grid-cols-2 gap-4">
                        <div className="space-y-2">
                          <Label>Relationship</Label>
                          <Select value={editForm.nokRelationship || undefined} onValueChange={(v) => setEditForm(prev => ({ ...prev, nokRelationship: v === 'not-specified' ? '' : v }))}>
                            <SelectTrigger><SelectValue placeholder="Select" /></SelectTrigger>
                            <SelectContent>
                              <SelectItem value="not-specified">Not specified</SelectItem>
                              {NOK_RELATIONSHIPS.map(rel => <SelectItem key={rel} value={rel}>{rel}</SelectItem>)}
                            </SelectContent>
                          </Select>
                        </div>
                        <div className="space-y-2">
                          <Label>Phone</Label>
                          <Input value={editForm.nokPhone} onChange={(e) => setEditForm(prev => ({ ...prev, nokPhone: e.target.value }))} placeholder="+234..." />
                        </div>
                      </div>
                      <div className="space-y-2">
                        <Label>Address</Label>
                        <Input value={editForm.nokAddress} onChange={(e) => setEditForm(prev => ({ ...prev, nokAddress: e.target.value }))} placeholder="Next of kin address" />
                      </div>
                    </div>
                  </>
                )}
              </div>
            )}
            <DialogFooter>
              <Button variant="outline" onClick={() => setIsEditModalOpen(false)}>Cancel</Button>
              <Button onClick={handleSaveEdit} disabled={isSubmitting || editFormLoading || !editForm.firstName || !editForm.lastName || !editForm.phone}>
                {isSubmitting ? <Loader2 className="h-4 w-4 mr-2 animate-spin" /> : <Edit className="h-4 w-4 mr-2" />}
                Save Changes
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      </div>
    </DashboardLayout>
  );
}
