"""
URL configuration for the Reports app.
"""
from django.urls import path
from .views import (
    PatientDemographicsReportView,
    TopDiagnosesReportView,
    LabPerformanceReportView,
    PharmacyPerformanceReportView,
    ExportDataView,
    AttendanceSummaryReportView,
    AttendanceStatisticsReportView,
    VisitStatisticsReportView,
    DispensedPrescriptionsReportView,
    LaboratoryAttendanceReportView,
    ServicesActivitiesReportView,
    ComprehensiveReportView,
    ClinicAttendanceReportView,
    RadiologicalServicesReportView,
    ReferralTrackingReportView,
    DiseasePatternReportView,
    DiseasePatternComparedReportView,
    ObservationAdmissionsReportView,
    PhysioClinicalDiagnosisReportView,
    EyeClinicalDiagnosisReportView,
    GOPAttendanceReportView,
    WeekendCallDutyReportView,
    EscortLogReportView,
    NewRegistrationsReportView,
    DrugExpiryWatchReportView,
    TopPrescribedDrugsReportView,
    StaffProductivityReportView,
    CriticalLabResultsReportView,
    NotifiableDiseasesReportView,
)

urlpatterns = [
    path('reports/patient-demographics/', PatientDemographicsReportView.as_view(), name='patient-demographics-report'),
    path('reports/top-diagnoses/', TopDiagnosesReportView.as_view(), name='top-diagnoses-report'),
    path('reports/lab-performance/', LabPerformanceReportView.as_view(), name='lab-performance-report'),
    path('reports/pharmacy-performance/', PharmacyPerformanceReportView.as_view(), name='pharmacy-performance-report'),
    path('reports/export/', ExportDataView.as_view(), name='export-data'),
    path('reports/attendance-summary/', AttendanceSummaryReportView.as_view(), name='attendance-summary-report'),
    path('reports/attendance-statistics/', AttendanceStatisticsReportView.as_view(), name='attendance-statistics-report'),
    path('reports/visit-statistics/', VisitStatisticsReportView.as_view(), name='visit-statistics-report'),
    path('reports/dispensed-prescriptions/', DispensedPrescriptionsReportView.as_view(), name='dispensed-prescriptions-report'),
    path('reports/laboratory-attendance/', LaboratoryAttendanceReportView.as_view(), name='laboratory-attendance-report'),
    path('reports/services-activities/', ServicesActivitiesReportView.as_view(), name='services-activities-report'),
    path('reports/comprehensive/', ComprehensiveReportView.as_view(), name='comprehensive-report'),
    path('reports/clinic-attendance/', ClinicAttendanceReportView.as_view(), name='clinic-attendance-report'),
    path('reports/radiological-services/', RadiologicalServicesReportView.as_view(), name='radiological-services-report'),
    path('reports/referral-tracking/', ReferralTrackingReportView.as_view(), name='referral-tracking-report'),
    path('reports/disease-pattern/', DiseasePatternReportView.as_view(), name='disease-pattern-report'),
    path('reports/disease-pattern-compared/', DiseasePatternComparedReportView.as_view(), name='disease-pattern-compared-report'),
    path('reports/observation-admissions/', ObservationAdmissionsReportView.as_view(), name='observation-admissions-report'),
    path('reports/physio-clinical-diagnosis/', PhysioClinicalDiagnosisReportView.as_view(), name='physio-clinical-diagnosis-report'),
    path('reports/eye-clinical-diagnosis/', EyeClinicalDiagnosisReportView.as_view(), name='eye-clinical-diagnosis-report'),
    path('reports/gop-attendance/', GOPAttendanceReportView.as_view(), name='gop-attendance-report'),
    path('reports/weekend-duty/', WeekendCallDutyReportView.as_view(), name='weekend-duty-report'),
    path('reports/escort-log/', EscortLogReportView.as_view(), name='escort-log-report'),
    path('reports/new-registrations/', NewRegistrationsReportView.as_view(), name='new-registrations-report'),
    path('reports/drug-expiry/', DrugExpiryWatchReportView.as_view(), name='drug-expiry-report'),
    path('reports/top-drugs/', TopPrescribedDrugsReportView.as_view(), name='top-drugs-report'),
    path('reports/staff-productivity/', StaffProductivityReportView.as_view(), name='staff-productivity-report'),
    path('reports/critical-lab/', CriticalLabResultsReportView.as_view(), name='critical-lab-report'),
    path('reports/notifiable-diseases/', NotifiableDiseasesReportView.as_view(), name='notifiable-diseases-report'),
]

