# Generated by Django 4.2.27 on 2025-12-05 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('read', 'Read'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('export', 'Export'), ('import', 'Import'), ('verify', 'Verify'), ('approve', 'Approve'), ('reject', 'Reject')], db_index=True, max_length=20)),
                ('result', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('error', 'Error')], db_index=True, default='success', max_length=10)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], db_index=True, default='info', max_length=10)),
                ('object_type', models.CharField(db_index=True, help_text='patient, visit, prescription, etc.', max_length=50)),
                ('object_id', models.CharField(db_index=True, max_length=255)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('module', models.CharField(db_index=True, help_text='patients, laboratory, pharmacy, etc.', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context data')),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='activity_lo_user_id_d23b30_idx'), models.Index(fields=['object_type', 'object_id'], name='activity_lo_object__9db1e3_idx'), models.Index(fields=['module', 'action'], name='activity_lo_module_9e6d2a_idx'), models.Index(fields=['created_at'], name='activity_lo_created_166e11_idx'), models.Index(fields=['severity', 'result'], name='activity_lo_severit_5c960d_idx')],
            },
        ),
    ]
