# Generated by Django 4.2.27 on 2026-06-04 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('read', 'Read'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('export', 'Export'), ('import', 'Import'), ('verify', 'Verify'), ('approve', 'Approve'), ('reject', 'Reject'), ('merge', 'Merge'), ('promote', 'Promote'), ('convert_to_csr', 'Convert to CSR')], db_index=True, max_length=20),
        ),
    ]
