# Generated by Django 4.2.27 on 2025-12-05 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RadiologyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('stat', 'STAT')], default='routine', max_length=20)),
                ('clinic', models.CharField(blank=True, max_length=100)),
                ('clinical_notes', models.TextField(blank=True)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_radiology_orders', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_radiology', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radiology_orders', to='patients.patient')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radiology_orders', to='patients.visit')),
            ],
            options={
                'db_table': 'radiology_orders',
                'ordering': ['-ordered_at'],
            },
        ),
        migrations.CreateModel(
            name='RadiologyStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure', models.CharField(max_length=200)),
                ('body_part', models.CharField(blank=True, max_length=100)),
                ('modality', models.CharField(blank=True, help_text='X-Ray, CT, MRI, Ultrasound, etc.', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('acquired', 'Acquired'), ('processing', 'Processing'), ('reported', 'Reported'), ('verified', 'Verified')], default='pending', max_length=20)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('processing_method', models.CharField(blank=True, choices=[('in_house', 'In-house'), ('outsourced', 'Outsourced')], max_length=20, null=True)),
                ('outsourced_facility', models.CharField(blank=True, max_length=200)),
                ('images_count', models.IntegerField(default=0)),
                ('technical_notes', models.TextField(blank=True)),
                ('acquired_at', models.DateTimeField(blank=True, null=True)),
                ('report', models.TextField(blank=True)),
                ('findings', models.TextField(blank=True)),
                ('impression', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acquired_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acquired_studies', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studies', to='radiology.radiologyorder')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_studies', to=settings.AUTH_USER_MODEL)),
                ('scheduled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_studies', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_studies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Radiology Studies',
                'db_table': 'radiology_studies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RadiologyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_status', models.CharField(blank=True, choices=[('normal', 'Normal'), ('abnormal', 'Abnormal'), ('critical', 'Critical')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_records', to='radiology.radiologyorder')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radiology_reports', to='patients.patient')),
                ('study', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_record', to='radiology.radiologystudy')),
            ],
            options={
                'db_table': 'radiology_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
