# Generated by Django 4.2.27 on 2025-12-19 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0004_remove_chief_complaint'),
        ('radiology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiologyorder',
            name='consultation_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radiology_orders', to='consultation.consultationsession'),
        ),
    ]
