# Generated by Django 4.2.27 on 2025-01-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0002_add_consultation_session_to_radiology_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadiologyTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full procedure name', max_length=200)),
                ('code', models.CharField(db_index=True, help_text='Procedure code (e.g., XR-ABD, CT-CHEST)', max_length=50, unique=True)),
                ('category', models.CharField(choices=[('xray', 'X-Ray'), ('ct', 'CT Scan'), ('mri', 'MRI'), ('ultrasound', 'Ultrasound'), ('mammography', 'Mammography'), ('fluoroscopy', 'Fluoroscopy'), ('angiography', 'Angiography'), ('nuclear', 'Nuclear Medicine'), ('dental', 'Dental Imaging'), ('interventional', 'Interventional Radiology')], default='xray', max_length=50)),
                ('subcategory', models.CharField(blank=True, choices=[('plain_film', 'Plain Film'), ('contrast_studies', 'Contrast Studies'), ('special_procedures', 'Special Procedures'), ('doppler', 'Doppler Studies'), ('abdominal', 'Abdominal'), ('cardiac', 'Cardiac'), ('musculoskeletal', 'Musculoskeletal'), ('neurological', 'Neurological'), ('thoracic', 'Thoracic'), ('vascular', 'Vascular'), ('oncological', 'Oncological'), ('cytology', 'Cytology')], max_length=50)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the procedure')),
                ('body_part', models.CharField(blank=True, help_text='Primary body part/area', max_length=100)),
                ('modality', models.CharField(blank=True, help_text='Imaging modality', max_length=50)),
                ('contrast_required', models.BooleanField(default=False, help_text='Requires contrast media')),
                ('radiation_exposure', models.CharField(choices=[('none', 'No Radiation'), ('low', 'Low Radiation'), ('moderate', 'Moderate Radiation'), ('high', 'High Radiation')], default='moderate', max_length=20)),
                ('preparation_required', models.TextField(blank=True, help_text='Patient preparation instructions')),
                ('indications', models.TextField(blank=True, help_text='Clinical indications')),
                ('contraindications', models.TextField(blank=True, help_text='Contraindications')),
                ('turnaround_time', models.CharField(blank=True, help_text='Expected turnaround time', max_length=50)),
                ('report_template', models.JSONField(blank=True, default=dict, help_text='Structured reporting template')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'radiology_templates',
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['category'], name='radiology_te_category_idx'), models.Index(fields=['modality'], name='radiology_te_modality_idx'), models.Index(fields=['is_active'], name='radiology_te_is_acti_idx')],
            },
        ),
        migrations.AddField(
            model_name='radiologystudy',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Standard procedure template', null=True, on_delete=models.SET_NULL, related_name='studies', to='radiology.radiologytemplate'),
        ),
    ]