# Generated by Django 4.2.27 on 2026-01-16 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('radiology', '0003_create_radiology_template'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='radiologytemplate',
            new_name='radiology_t_categor_b51052_idx',
            old_name='radiology_te_category_idx',
        ),
        migrations.RenameIndex(
            model_name='radiologytemplate',
            new_name='radiology_t_modalit_f0f1fd_idx',
            old_name='radiology_te_modality_idx',
        ),
        migrations.RenameIndex(
            model_name='radiologytemplate',
            new_name='radiology_t_is_acti_ab79a6_idx',
            old_name='radiology_te_is_acti_idx',
        ),
        migrations.AddField(
            model_name='radiologyorder',
            name='critical',
            field=models.BooleanField(default=False, help_text='Critical findings flag'),
        ),
        migrations.AddField(
            model_name='radiologyorder',
            name='findings',
            field=models.TextField(blank=True, help_text='Radiological findings'),
        ),
        migrations.AddField(
            model_name='radiologyorder',
            name='impression',
            field=models.TextField(blank=True, help_text='Clinical impression/diagnosis'),
        ),
        migrations.AddField(
            model_name='radiologyorder',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='radiologyorder',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_radiology_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='radiologyorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('results_ready', 'Results Ready'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='radiologytemplate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='radiologytemplate',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('plain_film', 'Plain Film'), ('contrast_studies', 'Contrast Studies'), ('special_procedures', 'Special Procedures'), ('doppler', 'Doppler Studies'), ('abdominal', 'Abdominal'), ('cardiac', 'Cardiac'), ('musculoskeletal', 'Musculoskeletal'), ('neurological', 'Neurological'), ('thoracic', 'Thoracic'), ('vascular', 'Vascular'), ('oncological', 'Oncological')], max_length=50),
        ),
    ]
