# Generated by Django 4.2.27 on 2026-01-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0005_add_rejection_fields_to_radiologystudy'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiologystudy',
            name='critical',
            field=models.BooleanField(default=False, help_text='Critical findings flag'),
        ),
    ]
