# Generated by Django 4.2.27 on 2026-01-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0006_add_critical_field_to_radiology_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiologystudy',
            name='report_file',
            field=models.FileField(blank=True, help_text='Uploaded report file', null=True, upload_to='radiology_reports/'),
        ),
    ]
