# Generated by Django 4.2.27 on 2026-02-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0007_add_report_file_field_to_radiology_study'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radiologytemplate',
            name='contrast_required',
        ),
        migrations.AddField(
            model_name='radiologyorder',
            name='provisional_diagnosis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='radiologyorder',
            name='lmp',
            field=models.DateField(blank=True, null=True),
        ),
    ]

