# Generated by Django 4.2.27 on 2026-04-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0011_other_template_match_others_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagingPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(blank=True, help_text='Optional short code (e.g. for reports)', max_length=50)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Imaging partner (outsourced)',
                'verbose_name_plural': 'Imaging partners (outsourced)',
                'db_table': 'radiology_outsourced_partners',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
