# Generated by Django 4.2.30 on 2026-04-30 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0014_external_manual_radiology_orders'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='radiologyorder',
            new_name='radiology_o_source__0107cb_idx',
            old_name='radiology_o_source__94b0ef_idx',
        ),
    ]
