# Generated by Django 4.2.30 on 2026-08-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0022_radiology_study_routing'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='radiologystudyroutingevent',
            constraint=models.CheckConstraint(
                check=(
                    models.Q(destination_type='external')
                    | (models.Q(to_clinic__isnull=False) & models.Q(external_destination=''))
                ),
                name='radiology_route_internal_requires_clinic',
            ),
        ),
        migrations.AddConstraint(
            model_name='radiologystudyroutingevent',
            constraint=models.CheckConstraint(
                check=(
                    models.Q(destination_type='internal')
                    | (models.Q(to_clinic__isnull=True) & ~models.Q(external_destination=''))
                ),
                name='radiology_route_external_requires_destination',
            ),
        ),
    ]
