# Generated by Django 4.2.30 on 2026-08-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0023_radiology_routing_event_constraints'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='radiologystudy',
            index=models.Index(fields=['status', 'reported_at'], name='radiology_s_status_96c0e5_idx'),
        ),
        migrations.AddIndex(
            model_name='radiologystudy',
            index=models.Index(fields=['status', 'verified_at'], name='radiology_s_status_1fd739_idx'),
        ),
        migrations.AddIndex(
            model_name='radiologystudy',
            index=models.Index(fields=['processing_clinic', 'status'], name='radiology_s_process_38c3da_idx'),
        ),
    ]
