# Generated by Django 4.2.27 on 2025-12-05 16:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('generic_name', models.CharField(blank=True, max_length=200)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('unit', models.CharField(help_text='tablet, capsule, ml, etc.', max_length=50)),
                ('strength', models.CharField(blank=True, help_text='e.g., 500mg', max_length=100)),
                ('form', models.CharField(blank=True, help_text='tablet, syrup, injection, etc.', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'medications',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dispensing', 'Dispensing'), ('partially_dispensed', 'Partially Dispensed'), ('dispensed', 'Dispensed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('diagnosis', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('prescribed_at', models.DateTimeField(auto_now_add=True)),
                ('dispensed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prescriptions', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.patient')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='patients.visit')),
            ],
            options={
                'db_table': 'prescriptions',
                'ordering': ['-prescribed_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(max_length=50)),
                ('dosage', models.CharField(blank=True, help_text='e.g., 1 tablet twice daily', max_length=200)),
                ('frequency', models.CharField(blank=True, max_length=100)),
                ('duration', models.CharField(blank=True, help_text='e.g., 7 days', max_length=100)),
                ('instructions', models.TextField(blank=True)),
                ('dispensed_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_dispensed', models.BooleanField(default=False)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescription_items', to='pharmacy.medication')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='pharmacy.prescription')),
            ],
            options={
                'db_table': 'prescription_items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MedicationInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(db_index=True, max_length=100)),
                ('expiry_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(max_length=50)),
                ('min_stock_level', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='pharmacy.medication')),
            ],
            options={
                'db_table': 'medication_inventory',
                'ordering': ['expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='Dispense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispense_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(max_length=50)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('dispensed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('dispensed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensed_medications', to=settings.AUTH_USER_MODEL)),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispenses', to='pharmacy.medicationinventory')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispenses', to='pharmacy.medication')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispenses', to='pharmacy.prescription')),
                ('prescription_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispenses', to='pharmacy.prescriptionitem')),
            ],
            options={
                'db_table': 'dispenses',
                'ordering': ['-dispensed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['prescription_id'], name='prescriptio_prescri_aa4c67_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['patient', '-prescribed_at'], name='prescriptio_patient_b0e195_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['status'], name='prescriptio_status_1d7db8_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationinventory',
            index=models.Index(fields=['medication', 'batch_number'], name='medication__medicat_c818f9_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationinventory',
            index=models.Index(fields=['expiry_date'], name='medication__expiry__80e7eb_idx'),
        ),
        migrations.AddIndex(
            model_name='dispense',
            index=models.Index(fields=['dispense_id'], name='dispenses_dispens_3867d8_idx'),
        ),
        migrations.AddIndex(
            model_name='dispense',
            index=models.Index(fields=['prescription', '-dispensed_at'], name='dispenses_prescri_62502e_idx'),
        ),
    ]
