# Generated by Django 4.2.27 on 2025-12-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='category',
            field=models.CharField(blank=True, choices=[('Antibiotics', 'Antibiotics'), ('Analgesics', 'Analgesics'), ('Cardiovascular', 'Cardiovascular'), ('Diabetes', 'Diabetes'), ('Gastrointestinal', 'Gastrointestinal'), ('Vitamins & Supplements', 'Vitamins & Supplements'), ('Oncology', 'Oncology'), ('Respiratory', 'Respiratory'), ('Other', 'Other')], help_text='Medication category', max_length=50),
        ),
        migrations.AddField(
            model_name='medication',
            name='manufacturer',
            field=models.CharField(blank=True, help_text='Manufacturer name', max_length=200),
        ),
        migrations.AddField(
            model_name='medication',
            name='pack_size',
            field=models.IntegerField(blank=True, help_text='Number of units per pack', null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='prescription_required',
            field=models.BooleanField(default=False, help_text='Requires prescription'),
        ),
        migrations.AddField(
            model_name='medicationinventory',
            name='max_stock_level',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum stock level', max_digits=10, null=True),
        ),
    ]
