# Generated by Django 4.2.27 on 2025-12-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_medication_category_medication_manufacturer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='category',
            field=models.CharField(blank=True, choices=[('Antibiotics', 'Antibiotics'), ('Analgesics', 'Analgesics'), ('Antimalarials', 'Antimalarials'), ('Antifungals', 'Antifungals'), ('Antivirals', 'Antivirals'), ('Anticonvulsants', 'Anticonvulsants'), ('Antipsychotics', 'Antipsychotics'), ('Antidepressants', 'Antidepressants'), ('Antihistamines', 'Antihistamines'), ('Cardiovascular', 'Cardiovascular'), ('Corticosteroids', 'Corticosteroids'), ('Dermatology', 'Dermatology'), ('Diabetes', 'Diabetes'), ('Diuretics', 'Diuretics'), ('Emergency/Critical Care', 'Emergency/Critical Care'), ('Gastrointestinal', 'Gastrointestinal'), ('Hormones', 'Hormones'), ('Ophthalmology', 'Ophthalmology'), ('Oncology', 'Oncology'), ('Pediatrics', 'Pediatrics'), ('Respiratory', 'Respiratory'), ('Vitamins & Supplements', 'Vitamins & Supplements'), ('Other', 'Other')], help_text='Medication category', max_length=50),
        ),
    ]
