# Generated by Django 4.2.27 on 2025-12-15 19:57

from django.db import migrations
from datetime import datetime
import random


def fix_empty_dispense_ids(apps, schema_editor):
    """Generate dispense_id for existing records with empty dispense_id."""
    Dispense = apps.get_model('pharmacy', 'Dispense')
    
    dispenses_without_id = Dispense.objects.filter(dispense_id='') | Dispense.objects.filter(dispense_id__isnull=True)
    
    for dispense in dispenses_without_id:
        timestamp = datetime.now().strftime('%Y%m%d-%H%M%S')
        suffix = f"{random.randint(1000, 9999)}"
        dispense_id = f"DISP-{timestamp}-{suffix}"
        
        # Ensure uniqueness by checking if it already exists
        while Dispense.objects.filter(dispense_id=dispense_id).exists():
            suffix = f"{random.randint(1000, 9999)}"
            dispense_id = f"DISP-{timestamp}-{suffix}"
        
        dispense.dispense_id = dispense_id
        dispense.save(update_fields=['dispense_id'])


def reverse_fix(apps, schema_editor):
    """Reverse migration - set dispense_id back to empty (not needed but required)."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_alter_medication_category'),
    ]

    operations = [
        migrations.RunPython(fix_empty_dispense_ids, reverse_fix),
    ]
