# Generated by Django 4.2.27 on 2025-12-19 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0004_remove_chief_complaint'),
        ('pharmacy', '0004_fix_empty_dispense_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='consultation_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='consultation.consultationsession'),
        ),
    ]
