# Generated by Django 4.2.27 on 2026-01-07 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_add_consultation_session_to_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionitem',
            name='dosage_form',
            field=models.CharField(blank=True, help_text='e.g., tablet, capsule, syrup', max_length=100),
        ),
    ]
