# Generated by Django 4.2.28 on 2026-02-03 20:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacy', '0007_alter_medication_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_stock', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stock_issues',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='StockRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('partially_fulfilled', 'Partially Fulfilled'), ('fulfilled', 'Fulfilled'), ('received', 'Received'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('from_location', models.CharField(max_length=100)),
                ('to_location', models.CharField(max_length=100)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_notes', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_stock_requests', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_stock', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stock_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('fulfilled_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacy.medication')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.stockrequest')),
            ],
            options={
                'db_table': 'stock_request_items',
            },
        ),
        migrations.CreateModel(
            name='StockIssueLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('destination_inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues_to', to='pharmacy.medicationinventory')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pharmacy.stockissue')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacy.medication')),
                ('source_inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues_from', to='pharmacy.medicationinventory')),
            ],
            options={
                'db_table': 'stock_issue_lines',
            },
        ),
        migrations.AddField(
            model_name='stockissue',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='pharmacy.stockrequest'),
        ),
        migrations.AddIndex(
            model_name='stockrequest',
            index=models.Index(fields=['request_id'], name='stock_reque_request_d395b3_idx'),
        ),
        migrations.AddIndex(
            model_name='stockrequest',
            index=models.Index(fields=['status'], name='stock_reque_status_535a3c_idx'),
        ),
        migrations.AddIndex(
            model_name='stockrequest',
            index=models.Index(fields=['from_location', 'to_location'], name='stock_reque_from_lo_bfe7ff_idx'),
        ),
    ]
