# Generated by Django 4.2.28 on 2026-02-04 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0008_stockissue_stockrequest_stockrequestitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('active_ingredient', models.CharField(blank=True, max_length=200)),
                ('strength', models.CharField(blank=True, max_length=100)),
                ('dosage_form', models.CharField(blank=True, max_length=50)),
                ('route', models.CharField(blank=True, max_length=50)),
                ('atc_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'generic_medications',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='generic_med_name_c1e998_idx'), models.Index(fields=['atc_code'], name='generic_med_atc_cod_88a064_idx')],
            },
        ),
        migrations.AddField(
            model_name='medication',
            name='generic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brands', to='pharmacy.genericmedication'),
        ),
    ]
