# Generated by Django 4.2.28 on 2026-02-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0009_genericmedication_medication_generic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericmedication',
            name='atc_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
