# Generated by Django 4.2.28 on 2026-02-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0010_alter_genericmedication_atc_code'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='medication',
            constraint=models.UniqueConstraint(fields=('name', 'generic'), name='uniq_brand_per_generic'),
        ),
    ]
