# Generated by Django 4.2.28 on 2026-02-05 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0015_default_generic_category_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionitem',
            name='generic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prescription_items', to='pharmacy.genericmedication'),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='medication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prescription_items', to='pharmacy.medication'),
        ),
    ]
