# Generated by Django 4.2.28 on 2026-02-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0016_prescriptionitem_generic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionitem',
            name='route',
            field=models.CharField(blank=True, help_text='e.g., Oral, IV', max_length=50),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='strength',
            field=models.CharField(blank=True, help_text='e.g., 20/120mg', max_length=100),
        ),
    ]
