# Generated by Django 4.2.28 on 2026-02-13 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0017_prescriptionitem_strength_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionitem',
            name='generic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescription_items', to='pharmacy.genericmedication'),
        ),
    ]
