# Generated by Django 4.2.27 on 2026-03-06 05:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0022_backfill_genericmedication_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionitem',
            name='dose',
            field=models.CharField(blank=True, help_text='e.g., 1 tablet', max_length=200),
        ),
        migrations.AlterField(
            model_name='stockissueline',
            name='destination_inventory_item',
            field=models.ForeignKey(blank=True, help_text='Null when issued to Dispensary (stock tracked in DispensaryReceiptLine).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issues_to', to='pharmacy.medicationinventory'),
        ),
        migrations.CreateModel(
            name='DispensaryReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Total received', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity_remaining', models.DecimalField(decimal_places=2, help_text='Remaining after dispensing', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('received_at', models.DateTimeField()),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensary_receipt_lines', to='pharmacy.stockissue')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispensary_receipt_lines', to='pharmacy.medication')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensary_receipt_lines', to='pharmacy.stockrequest')),
                ('stock_issue_line', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensary_receipt_line', to='pharmacy.stockissueline')),
            ],
            options={
                'db_table': 'dispensary_receipt_lines',
                'ordering': ['received_at'],
                'indexes': [models.Index(fields=['medication'], name='dispensary__medicat_0abafd_idx'), models.Index(fields=['received_at'], name='dispensary__receive_e090f2_idx')],
            },
        ),
    ]
