# Generated by Django 4.2.27 on 2026-03-06 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0023_dispensary_receipt_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispense',
            name='dispensary_receipt_line',
            field=models.ForeignKey(blank=True, help_text='Set when dispensed from Dispensary (receipt-centric inventory).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispenses', to='pharmacy.dispensaryreceiptline'),
        ),
    ]
