# Generated by Django 4.2.30 on 2026-04-30 20:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0029_genericmedication_catalogue_hygiene'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AddConstraint(
            model_name='prescriptionitem',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='prescription_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='prescriptionitem',
            constraint=models.CheckConstraint(check=models.Q(('medication__isnull', False), ('generic__isnull', False), _connector='OR'), name='prescription_item_medication_or_generic_required'),
        ),
    ]
