# Generated by Django 4.2.27 on 2026-05-20 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_backfill_multi_clinic'),
        ('pharmacy', '0031_prescription_location_clinic'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationinventory',
            name='location_clinic',
            field=models.ForeignKey(blank=True, help_text='Care facility this inventory belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medication_inventories', to='organization.clinic'),
        ),
        migrations.AddField(
            model_name='stockrequest',
            name='clinic',
            field=models.ForeignKey(blank=True, help_text='Care facility this stock request belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_requests', to='organization.clinic'),
        ),
    ]
