# Generated by Django 4.2.28 on 2026-05-21 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_backfill_multi_clinic'),
        ('pharmacy', '0032_add_clinic_fks'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispensaryreceiptline',
            name='location_clinic',
            field=models.ForeignKey(blank=True, help_text='Care facility this receipt line belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensary_receipt_lines', to='organization.clinic'),
        ),
    ]
