# Generated by Django 4.2.30 on 2026-06-20 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0035_medication_dispense_mode'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='hodstockissue',
            new_name='hod_stock_i_issue_i_6c4728_idx',
            old_name='hod_stock_i_issue_i_6f0f0d_idx',
        ),
        migrations.RenameIndex(
            model_name='hodstockissue',
            new_name='hod_stock_i_issued__a1158e_idx',
            old_name='hod_stock_i_issued__8a2f1e_idx',
        ),
        migrations.RenameIndex(
            model_name='hodstockissue',
            new_name='hod_stock_i_medicat_1326f5_idx',
            old_name='hod_stock_i_medicat_0c4b2a_idx',
        ),
    ]
