# Generated by Django 4.2.30 on 2026-08-06 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0043_medicationinventory_received_metadata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockrequest',
            old_name='clinic',
            new_name='location_clinic',
        ),
    ]
